export const KLINIKOS_EXPERIENCE_ENVELOPE_CANON = {
  name: "active-experience-envelope",
  purpose: "continuously-compose-the-minimum-relevant-governed-klinikos-experience",
  stateLadder: [
    "exists",
    "discoverable",
    "promoted",
    "eligible",
    "entitled",
    "authorized",
    "visible-data",
    "actionable-now",
  ],
  inputs: [
    "identity",
    "active-relationship",
    "organization",
    "location",
    "role",
    "verified-credentials",
    "authority",
    "purpose",
    "entitlements",
    "current-intent",
    "current-workflow",
    "current-resource",
    "authorized-patient-or-case-context",
    "network-state",
    "temporal-context",
    "jurisdiction",
    "policy",
    "risk-state",
  ],
  outputs: [
    "primary-workspace",
    "primary-action",
    "navigation",
    "secondary-capabilities",
    "data-projection",
    "actions",
    "zumi-tools",
    "notifications",
    "promotions",
    "verification-requests",
    "blocked-states",
    "context-switches",
    "audit-requirements",
  ],
  laws: [
    "signup-seeds-envelope-not-permanent-classification",
    "envelope-recomputes-when-context-changes",
    "least-privilege-and-minimum-necessary",
    "promotion-does-not-grant-entitlement-or-authority",
    "same-identity-may-switch-contexts-without-data-bleed",
    "clinical-context-cannot-leak-into-grid-or-commercial-targeting",
    "visibility-is-not-authority",
    "zumi-interprets-context-policy-engines-authorize",
    "role-is-one-signal-not-the-experience-definition",
    "active-organization-and-purpose-bound-data-scope",
    "current-work-object-can-further-narrow-visible-data",
    "context-switch-must-recompute-permissions-data-and-zumi-scope",
  ],
  recomputeTriggers: [
    "sign-in",
    "sign-out",
    "context-switch",
    "organization-switch",
    "relationship-created-updated-or-revoked",
    "credential-state-change",
    "authority-change",
    "entitlement-change",
    "purpose-change",
    "workflow-change",
    "resource-change",
    "jurisdiction-or-policy-change",
    "risk-state-change",
    "material-network-state-change",
  ],
  authorityOrder: [
    "identity",
    "relationship",
    "organization",
    "location",
    "credential",
    "role",
    "privilege-or-delegation",
    "purpose",
    "resource-or-object",
    "consent",
    "policy",
    "time",
    "decision",
  ],
  privacyBoundaries: [
    "minimum-necessary-data-projection",
    "organization-context-isolation",
    "patient-or-case-context-only-when-authorized",
    "no-clinical-data-in-grid-by-default",
    "no-phi-in-commercial-targeting-by-default",
    "no-cross-organization-context-reuse-without-lawful-basis",
    "zumi-context-is-bounded-by-the-active-envelope",
  ],
} as const;

export type KlinikosExperienceEnvelopeCanon = typeof KLINIKOS_EXPERIENCE_ENVELOPE_CANON;
