export const navigation = [
  {
    label: "Command",
    items: [
      { href: "/dashboard", label: "Command center", icon: "LayoutDashboard" },
      { href: "/front-desk", label: "Front desk", icon: "Headphones" },
      { href: "/provider", label: "Provider workspace", icon: "Stethoscope" },
    ],
  },
  {
    label: "Care",
    items: [
      { href: "/patients", label: "Patients", icon: "Users" },
      { href: "/schedule", label: "Schedule", icon: "CalendarDays" },
      { href: "/encounters", label: "Encounters", icon: "ClipboardPlus" },
      { href: "/labs", label: "Labs", icon: "FlaskConical" },
      { href: "/imaging", label: "Imaging", icon: "ScanLine" },
      { href: "/medications", label: "Medications", icon: "Pill" },
      { href: "/documents", label: "Documents", icon: "Files" },
      { href: "/telemedicine", label: "Telemedicine", icon: "Video" },
      { href: "/forms", label: "Intake & forms", icon: "ClipboardList" },
    ],
  },
  {
    label: "Coordination",
    items: [
      { href: "/referrals", label: "Referrals", icon: "Waypoints" },
      { href: "/network", label: "Network", icon: "Network" },
      { href: "/grid", label: "GRID", icon: "Orbit" },
      { href: "/messages", label: "Messages", icon: "MessagesSquare" },
    ],
  },
  {
    label: "Revenue",
    items: [
      { href: "/billing", label: "Billing", icon: "ReceiptText" },
      { href: "/claim-readiness", label: "Claim readiness", icon: "Calculator" },
      { href: "/insurance", label: "Insurance", icon: "ShieldCheck" },
      { href: "/cases", label: "No-fault / WC", icon: "BriefcaseMedical" },
      { href: "/crm", label: "Revenue recovery", icon: "CircleDollarSign" },
      { href: "/quality", label: "Quality", icon: "ChartNoAxesCombined" },
      { href: "/luxe-medi", label: "Luxe Medi", icon: "Sparkles" },
    ],
  },
  {
    label: "Operations",
    items: [
      { href: "/tasks", label: "Tasks", icon: "ListChecks" },
      { href: "/escalations", label: "Escalations", icon: "Siren" },
      { href: "/inventory", label: "Inventory", icon: "Boxes" },
      { href: "/patient-navigation", label: "Patient navigation", icon: "Route" },
      { href: "/remote-monitoring", label: "Remote monitoring", icon: "Activity" },
      { href: "/ai-assistants", label: "Zumi Copilot", icon: "Sparkles" },
      { href: "/voice-assistant", label: "Talk to Zumi", icon: "AudioLines" },
    ],
  },
  {
    label: "Admin",
    items: [
      { href: "/admin/sales", label: "Sales command", icon: "CircleDollarSign" },
      { href: "/owner/founding-program", label: "Founding program", icon: "BriefcaseMedical" },
      { href: "/portal-admin", label: "Portal administration", icon: "MonitorSmartphone" },
      { href: "/integrations", label: "Connections", icon: "Blocks" },
      { href: "/settings", label: "Settings & audit", icon: "Settings2" },
      { href: "/system-health", label: "System health", icon: "Gauge" },
    ],
  },
] as const;

export const workspaceMeta: Record<string, { title: string; eyebrow: string }> = {
  dashboard: { title: "Command center", eyebrow: "Practice overview" },
  "front-desk": { title: "Front desk", eyebrow: "Today at a glance" },
  provider: { title: "Provider workspace", eyebrow: "Clinical priority queue" },
  patients: { title: "Patient charts", eyebrow: "Unified record" },
  schedule: { title: "Schedule", eyebrow: "Multi-location calendar" },
  encounters: { title: "Encounters", eyebrow: "Documentation workspace" },
  telemedicine: { title: "Telemedicine", eyebrow: "Virtual care operations" },
  labs: { title: "Labs", eyebrow: "Review and release" },
  imaging: { title: "Imaging", eyebrow: "Orders and reports" },
  medications: { title: "Medications", eyebrow: "Reconcile, review, transmit" },
  documents: { title: "Documents", eyebrow: "Controlled clinical records" },
  forms: { title: "Intake & forms", eyebrow: "Consent and readiness" },
  knowledge: { title: "Medical Knowledge Engine", eyebrow: "Governed reference layer" },
  "remote-monitoring": { title: "Remote monitoring", eyebrow: "Consent-bound home observations" },
  inventory: { title: "Inventory", eyebrow: "Supply and custody intelligence" },
  billing: { title: "Billing", eyebrow: "Revenue cycle" },
  "claim-readiness": { title: "Claim readiness", eyebrow: "Coding and revenue intelligence" },
  "luxe-medi": { title: "Luxe Medi Studio", eyebrow: "Med-spa operations" },
  insurance: { title: "Insurance", eyebrow: "Eligibility and authorization" },
  cases: { title: "No-fault / workers' comp", eyebrow: "Case operations" },
  quality: { title: "Quality & HEDIS", eyebrow: "Care-gap intelligence" },
  crm: { title: "CRM & revenue recovery", eyebrow: "Lead conversion and follow-up" },
  messages: { title: "Messages", eyebrow: "Secure communication" },
  tasks: { title: "Tasks", eyebrow: "Work queue" },
  escalations: { title: "Escalations", eyebrow: "Human review required" },
  "ai-assistants": { title: "Zumi Copilot", eyebrow: "Safe workflow automation" },
  "patient-navigation": { title: "Patient navigation", eyebrow: "Administrative next steps" },
  grid: { title: "The Grid", eyebrow: "Provider and service network" },
  network: { title: "Network command", eyebrow: "Connected-care mission control" },
  referrals: { title: "Referral relay", eyebrow: "Closed-loop care coordination" },
  "access-controls": { title: "Access controls", eyebrow: "Consent-bound record exchange" },
  "identity-resolution": { title: "Identity resolution", eyebrow: "Master patient index" },
  "care-teams": { title: "Care Constellation", eyebrow: "Virtual care team" },
  "capacity-exchange": { title: "Capacity Exchange", eyebrow: "Network availability" },
  "provider-network": { title: "Provider network", eyebrow: "Consultation marketplace" },
  "injury-episodes": { title: "Injury Episode Room", eyebrow: "Case command center" },
  "health-passport": { title: "Health Passport", eyebrow: "Patient-controlled portability" },
  "intake-passport": { title: "Intake Passport", eyebrow: "Reusable patient-confirmed intake" },
  "voice-assistant": { title: "Talk to Zumi", eyebrow: "Voice-first Copilot" },
  "feature-registry": { title: "Priority Zero registry", eyebrow: "Klinikos product constitution" },
  "portal-admin": { title: "Patient portal administration", eyebrow: "Patient experience controls" },
  integrations: { title: "Connections", eyebrow: "Standards and partners" },
  settings: { title: "Settings & audit", eyebrow: "Organization controls" },
  "system-health": { title: "System health", eyebrow: "Reliability and recovery" },
  admin: { title: "Sales command", eyebrow: "Founding clinic pipeline" },
  owner: { title: "Founding clinic program", eyebrow: "Evaluation and contribution" },
};
