export const navigation = [
  {
    label: "Home",
    items: [
      { href: "/dashboard", label: "Home", icon: "LayoutDashboard", description: "Your daily overview, priorities, and shortcuts." },
      { href: "/paths", label: "Routes", icon: "Route", description: "See governed journeys from current state to a desired healthcare outcome." },
      { href: "/ecosystem", label: "Ecosystem", icon: "Orbit", description: "See how EDU, Grid, Clinic OS, capacity, and Network compound across the healthcare lifecycle." },
      { href: "/front-desk", label: "Front desk", icon: "Headphones", description: "Appointments, arrivals, readiness, and patient requests." },
      { href: "/provider", label: "Provider workspace", icon: "Stethoscope", description: "Clinical priorities, encounters, and review work." },
    ],
  },
  {
    label: "Patients & care",
    items: [
      { href: "/patients", label: "Patients", icon: "Users", description: "Find and manage patient records." },
      { href: "/schedule", label: "Schedule", icon: "CalendarDays", description: "See visits and availability across locations." },
      { href: "/encounters", label: "Encounters", icon: "ClipboardPlus", description: "Open, document, review, and close encounters." },
      { href: "/telemedicine", label: "Telemedicine", icon: "Video", description: "Coordinate virtual visits and follow-through." },
      { href: "/labs", label: "Labs", icon: "FlaskConical", description: "Track orders, results, review, and release." },
      { href: "/imaging", label: "Imaging", icon: "ScanLine", description: "Manage imaging orders, reports, and next steps." },
      { href: "/medications", label: "Medications", icon: "Pill", description: "Reconcile and manage medication workflows." },
      { href: "/documents", label: "Documents", icon: "Files", description: "Keep clinical records and supporting documents together." },
      { href: "/forms", label: "Intake & forms", icon: "ClipboardList", description: "Manage intake, consent, signatures, and readiness." },
      { href: "/knowledge", label: "Medical knowledge", icon: "BookOpenCheck", description: "Use the governed clinical reference workspace." },
      { href: "/remote-monitoring", label: "Remote monitoring", icon: "Activity", description: "Review consent-bound observations from home." },
    ],
  },
  {
    label: "Connected care",
    items: [
      { href: "/referrals", label: "Referrals", icon: "Waypoints", description: "Track referrals until the care loop is closed." },
      { href: "/network", label: "Care network", icon: "Network", description: "See connected organizations, handoffs, and activity." },
      { href: "/care-teams", label: "Care teams", icon: "HeartHandshake", description: "Coordinate the people responsible for a patient." },
      { href: "/capacity-exchange", label: "Capacity exchange", icon: "CalendarDays", description: "Find and coordinate available care capacity." },
      { href: "/provider-network", label: "Provider network", icon: "Users", description: "Find providers and coordinate consultations." },
      { href: "/health-passport", label: "Health passport", icon: "HeartHandshake", description: "Support patient-controlled continuity across care." },
      { href: "/intake-passport", label: "Intake passport", icon: "ClipboardCheck", description: "Reuse patient-confirmed intake information safely." },
      { href: "/patient-navigation", label: "Patient navigation", icon: "Route", description: "Guide administrative next steps and follow-up." },
      { href: "/messages", label: "Messages", icon: "MessagesSquare", description: "Keep secure communication connected to the work." },
    ],
  },
  {
    label: "Grid",
    items: [
      { href: "/grid", label: "The Grid", icon: "Orbit", description: "Open the universal healthcare opportunity and capacity network." },
    ],
  },
  {
    label: "Revenue & quality",
    items: [
      { href: "/billing", label: "Billing", icon: "ReceiptText", description: "Follow payment and revenue-cycle work." },
      { href: "/claim-readiness", label: "Claim readiness", icon: "Calculator", description: "See what needs attention before claim submission." },
      { href: "/insurance", label: "Insurance", icon: "ShieldCheck", description: "Track eligibility and authorization workflows." },
      { href: "/cases", label: "No-fault / workers’ comp", icon: "BriefcaseMedical", description: "Coordinate injury cases, documents, and follow-up." },
      { href: "/injury-episodes", label: "Injury episode", icon: "BriefcaseMedical", description: "Keep one injury episode, its evidence, and its next steps together." },
      { href: "/crm", label: "Revenue recovery", icon: "CircleDollarSign", description: "Turn missed opportunities into owned next actions." },
      { href: "/quality", label: "Quality & HEDIS", icon: "ChartNoAxesCombined", description: "Track care gaps and quality work." },
      { href: "/luxe-medi", label: "Luxe Medi", icon: "Sparkles", description: "Run med-spa leads, services, packages, and follow-up." },
      { href: "/luxe-medi/acquisition", label: "Luxe acquisition", icon: "CircleDollarSign", description: "See unanswered demand, source attribution, response speed, and at-risk opportunity." },
    ],
  },
  {
    label: "Work",
    items: [
      { href: "/tasks", label: "Tasks", icon: "ListChecks", description: "See assigned work and what needs action next." },
      { href: "/escalations", label: "Escalations", icon: "Siren", description: "Review work that requires human attention." },
      { href: "/inventory", label: "Inventory", icon: "Boxes", description: "Track supplies, stock, and custody." },
    ],
  },
  {
    label: "Learning",
    items: [
      { href: "/edu", label: "Klinikos EDU", icon: "BookOpenCheck", description: "Open the virtual clinic lab, courses, simulations, competency, and readiness experience." },
    ],
  },
  {
    label: "Organization",
    items: [
      { href: "/owner/founding-program", label: "Founding clinic program", icon: "BriefcaseMedical", description: "Review your clinic’s evaluation and implementation pathway." },
      { href: "/portal-admin", label: "Patient portal", icon: "MonitorSmartphone", description: "Manage the patient-facing portal experience." },
      { href: "/access-controls", label: "Access & sharing", icon: "LockKeyhole", description: "Manage consent-bound record access and sharing." },
      { href: "/identity-resolution", label: "Patient matching", icon: "Fingerprint", description: "Review potential duplicate or matching identities." },
      { href: "/integrations", label: "Connections", icon: "Blocks", description: "Manage the systems and partners Klinikos connects to." },
      { href: "/settings", label: "Settings", icon: "Settings2", description: "Manage organization preferences and audit controls." },
    ],
  },
] as const;

export const workspaceMeta: Record<string, { title: string; eyebrow: string }> = {
  dashboard: { title: "Home", eyebrow: "Your Klinikos workspace" },
  zumi: { title: "Conversation", eyebrow: "Zumi" },
  paths: { title: "Routes", eyebrow: "Current state → desired state" },
  ecosystem: { title: "Ecosystem", eyebrow: "Healthcare lifecycle" },
  "front-desk": { title: "Front desk", eyebrow: "Today at a glance" },
  provider: { title: "Provider workspace", eyebrow: "Clinical priority queue" },
  patients: { title: "Patient charts", eyebrow: "Unified record" },
  schedule: { title: "Schedule", eyebrow: "Multi-location calendar" },
  encounters: { title: "Encounters", eyebrow: "Documentation workspace" },
  telemedicine: { title: "Telemedicine", eyebrow: "Virtual care operations" },
  labs: { title: "Labs", eyebrow: "Review and release" },
  imaging: { title: "Imaging", eyebrow: "Orders and reports" },
  medications: { title: "Medications", eyebrow: "Reconcile, review, transmit" },
  documents: { title: "Documents", eyebrow: "Controlled clinical records" },
  forms: { title: "Intake & forms", eyebrow: "Consent and readiness" },
  knowledge: { title: "Medical knowledge", eyebrow: "Governed reference" },
  "remote-monitoring": { title: "Remote monitoring", eyebrow: "Consent-bound home observations" },
  inventory: { title: "Inventory", eyebrow: "Supply and custody intelligence" },
  billing: { title: "Billing", eyebrow: "Revenue cycle" },
  "claim-readiness": { title: "Claim readiness", eyebrow: "Coding and revenue intelligence" },
  "luxe-medi": { title: "Luxe Medi Studio", eyebrow: "Med-spa operations" },
  insurance: { title: "Insurance", eyebrow: "Eligibility and authorization" },
  cases: { title: "No-fault / workers' comp", eyebrow: "Case operations" },
  quality: { title: "Quality & HEDIS", eyebrow: "Care-gap intelligence" },
  crm: { title: "CRM & revenue recovery", eyebrow: "Lead conversion and follow-up" },
  messages: { title: "Messages", eyebrow: "Secure communication" },
  tasks: { title: "Tasks", eyebrow: "Work queue" },
  escalations: { title: "Escalations", eyebrow: "Human review required" },
  "ai-assistants": { title: "Zumi Copilot", eyebrow: "Safe workflow automation" },
  "patient-navigation": { title: "Patient navigation", eyebrow: "Administrative next steps" },
  grid: { title: "The Grid", eyebrow: "Opportunity and capacity network" },
  network: { title: "Care network", eyebrow: "Connected-care coordination" },
  referrals: { title: "Referrals", eyebrow: "Closed-loop care coordination" },
  "access-controls": { title: "Access & sharing", eyebrow: "Consent-bound record exchange" },
  "identity-resolution": { title: "Patient matching", eyebrow: "Identity continuity" },
  "care-teams": { title: "Care teams", eyebrow: "People around the patient" },
  "capacity-exchange": { title: "Capacity exchange", eyebrow: "Network availability" },
  "provider-network": { title: "Provider network", eyebrow: "Consultation marketplace" },
  "injury-episodes": { title: "Injury episode", eyebrow: "Case coordination" },
  "health-passport": { title: "Health passport", eyebrow: "Patient-controlled portability" },
  "intake-passport": { title: "Intake passport", eyebrow: "Reusable patient-confirmed intake" },
  "voice-assistant": { title: "Talk to Zumi", eyebrow: "Voice-first assistance" },
  "feature-registry": { title: "Priority Zero registry", eyebrow: "Internal product controls" },
  "portal-admin": { title: "Patient portal", eyebrow: "Patient experience controls" },
  integrations: { title: "Connections", eyebrow: "Systems and partners" },
  settings: { title: "Settings", eyebrow: "Organization controls" },
  "system-health": { title: "System health", eyebrow: "Internal reliability" },
  admin: { title: "Sales command", eyebrow: "Internal clinic pipeline" },
  owner: { title: "Founding clinic program", eyebrow: "Evaluation and contribution" },
};
