export const KLINIKOS_OPERATING_NETWORK_CANON = {
  brand: "Klinikos. The clinic operations ecosystem, powered by Zumi.",
  parentDefinition: "governed-healthcare-operating-network",
  experienceLaw: "complexity-belongs-in-klinikos-not-in-the-users-hands",
  laws: [
    "free-participation-is-distribution-infrastructure",
    "land-without-displacement",
    "expand-by-usefulness",
    "replace-by-earned-trust",
    "founder-omission-does-not-equal-engineering-omission",
    "no-known-failure-disappears-silently",
    "customer-dependence-comes-from-value-not-lock-in",
    "interface-is-the-signature",
    "market-category-terms-are-capability-labels-not-parent-definitions",
    "one-identity-many-governed-experiences",
    "signup-promotes-relevant-experience-not-the-whole-platform",
  ],
  marketCapabilityLabels: [
    "ehr-emr",
    "practice-management",
    "scheduling",
    "telemedicine",
    "billing-revenue-cycle",
    "patient-portal",
    "crm",
    "staffing-marketplace",
    "professional-network",
    "education-workforce",
    "ai-copilot",
    "analytics",
    "provider-directory",
    "payments",
    "resource-marketplace",
  ],
  experienceRouting: {
    identityModel: "one-person-one-persistent-identity-many-contextual-relationships",
    signupPurpose: "resolve-and-promote-the-most-relevant-starting-experience",
    defaultOperationalAccess: "locked-unless-authorized",
    promotionIsAuthority: false,
    routingSignals: [
      "entry-route",
      "expressed-intent",
      "self-declared-relationship",
      "verified-relationship",
      "organization-membership",
      "role",
      "credential-state",
      "entitlement",
      "current-purpose",
    ],
    rules: [
      "show-only-what-is-relevant-now",
      "hide-irrelevant-systems-from-primary-experience",
      "deny-operational-access-without-authority",
      "promotion-may-invite-a-claim-or-verification-step-but-cannot-grant-authority",
      "preserve-safe-intent-through-signup-and-authentication",
      "expand-experience-when-new-relationships-needs-or-entitlements-justify-it",
      "a-user-may-have-multiple-experiences-without-separate-identities",
      "navigation-discovery-and-authorization-remain-separate-controls",
    ],
  },
  userOrder: [
    "discover",
    "receive-value",
    "express-intent",
    "create-identity-when-persistence-matters",
    "build-profile-and-claims",
    "verify-only-what-next-action-requires",
    "enter-grid-or-relevant-network",
    "receive-opportunity-connection-work-or-learning-value",
    "build-evidence-and-relationships",
    "return",
    "invite-refer-or-connect-others",
    "organization-enters-or-deepens",
    "operating-map-identifies-friction",
    "solve-one-workflow",
    "paid-implementation-subscription-or-contract",
    "care-money-and-operations-expand",
    "more-work-runs-through-klinikos",
    "more-grid-supply-and-demand-is-created",
    "network-becomes-more-useful",
    "return-and-expansion-feed-distribution",
  ],
  truthSeparations: [
    "claim!=verified-fact!=authority",
    "match!=offer!=acceptance!=reservation",
    "booking!=fulfillment",
    "payment-intent!=payment",
    "financial-obligation!=settlement",
    "order-created!=external-acceptance",
    "result-received!=provider-review",
    "referral-created!=referral-closed",
    "course-completed!=professional-authority",
    "code-exists!=deployed",
    "deployed!=production-verified",
    "ai-interpretation!=authoritative-fact",
  ],
  roleSurface: {
    provider: "one-visit",
    staff: "one-handoff",
    patient: "one-next-action",
    biller: "one-truthful-exception-queue",
    owner: "one-operating-picture",
    student: "one-next-step-toward-opportunity",
    professional: "one-evolving-identity-and-opportunity-network",
    enterprise: "one-governed-operating-picture",
  },
  backendKernels: [
    "identity",
    "organization",
    "trust-authority",
    "intent",
    "work-obligation",
    "grid",
    "network-relationship",
    "clinical",
    "financial",
    "evidence-audit",
    "communication",
    "integration",
    "zumi",
    "edu",
    "entitlement",
    "analytics",
    "search-knowledge",
    "reliability",
    "security-privacy",
  ],
} as const;

export type KlinikosOperatingNetworkCanon = typeof KLINIKOS_OPERATING_NETWORK_CANON;
