export type PublicCapabilityExposure = "PUBLIC_REQUIRED" | "PUBLIC_OPTIONAL" | "PRIVATE_ONLY";
export type PublicCapabilityMaturity = "CURRENT_ROUTE" | "PRODUCT_EXISTS_PUBLIC_GAP" | "PLANNED" | "VENDOR_DEPENDENT" | "GOVERNANCE_ONLY";

export interface PublicCapabilityDefinition {
  id: string;
  label: string;
  category: string;
  canonicalRoute: string;
  exposure: PublicCapabilityExposure;
  maturity: PublicCapabilityMaturity;
  personas: string[];
  connectedDomains: string[];
  primaryIntent: string;
  primaryCta: string;
}

function capability(input: PublicCapabilityDefinition) {
  return input;
}

/**
 * Canonical public-discovery registry.
 *
 * IMPORTANT:
 * - A record here does NOT mean the route is implemented or production-ready.
 * - `maturity` must remain truthful and be reconciled against current `src/app` routes.
 * - The registry exists so major Klinikos capabilities cannot disappear from public discovery
 *   merely because they live inside a broader backend domain.
 * - Public SEO category != separate commercial SKU.
 */
export const publicCapabilityRegistry = [
  capability({ id: "platform", label: "Healthcare Operating Network", category: "platform", canonicalRoute: "/platform", exposure: "PUBLIC_REQUIRED", maturity: "PLANNED", personas: ["all"], connectedDomains: ["kernel", "zumi", "care", "revenue", "grid", "edu", "enterprise"], primaryIntent: "Understand the complete Klinikos platform", primaryCta: "Map my clinic" }),
  capability({ id: "ehr-emr", label: "EHR / EMR", category: "clinical", canonicalRoute: "/ehr-emr", exposure: "PUBLIC_REQUIRED", maturity: "PRODUCT_EXISTS_PUBLIC_GAP", personas: ["clinic_owner", "provider", "enterprise"], connectedDomains: ["care", "patient", "identity", "integration"], primaryIntent: "Evaluate Klinikos as an EHR/EMR and clinical operating environment", primaryCta: "See Klinikos in action" }),
  capability({ id: "practice-management", label: "Practice Management", category: "clinical", canonicalRoute: "/practice-management", exposure: "PUBLIC_REQUIRED", maturity: "PRODUCT_EXISTS_PUBLIC_GAP", personas: ["clinic_owner", "practice_manager", "front_desk"], connectedDomains: ["care", "scheduling", "revenue", "communications"], primaryIntent: "Run clinic operations in one system", primaryCta: "Map my clinic" }),
  capability({ id: "current-visit", label: "Current Visit", category: "clinical", canonicalRoute: "/current-visit", exposure: "PUBLIC_REQUIRED", maturity: "PRODUCT_EXISTS_PUBLIC_GAP", personas: ["provider", "clinic_owner"], connectedDomains: ["care", "clinical_change", "orders", "coding", "revenue"], primaryIntent: "See the unified provider encounter experience", primaryCta: "See the Current Visit" }),
  capability({ id: "clinical-documentation", label: "Clinical Documentation", category: "clinical", canonicalRoute: "/clinical-documentation", exposure: "PUBLIC_REQUIRED", maturity: "PRODUCT_EXISTS_PUBLIC_GAP", personas: ["provider", "clinical_staff"], connectedDomains: ["care", "zumi", "coding"], primaryIntent: "Document patient care efficiently", primaryCta: "See documentation workflow" }),
  capability({ id: "ai-medical-scribe", label: "AI Medical Scribe", category: "clinical", canonicalRoute: "/ai-medical-scribe", exposure: "PUBLIC_REQUIRED", maturity: "PLANNED", personas: ["provider"], connectedDomains: ["zumi", "care", "clinical_evidence", "coding"], primaryIntent: "Use governed ambient documentation", primaryCta: "See Zumi for clinicians" }),
  capability({ id: "clinical-change", label: "Clinical Change", category: "clinical", canonicalRoute: "/clinical-change", exposure: "PUBLIC_REQUIRED", maturity: "PRODUCT_EXISTS_PUBLIC_GAP", personas: ["provider", "clinical_staff"], connectedDomains: ["care", "evidence", "bodymap"], primaryIntent: "Understand what changed since prior visits", primaryCta: "See Clinical Change" }),
  capability({ id: "body-map", label: "BodyMap", category: "clinical", canonicalRoute: "/body-map", exposure: "PUBLIC_REQUIRED", maturity: "PRODUCT_EXISTS_PUBLIC_GAP", personas: ["provider", "clinical_staff"], connectedDomains: ["care", "clinical_change"], primaryIntent: "Track longitudinal body-region findings", primaryCta: "See BodyMap" }),
  capability({ id: "telemedicine", label: "Telemedicine", category: "virtual-care", canonicalRoute: "/telemedicine", exposure: "PUBLIC_REQUIRED", maturity: "PRODUCT_EXISTS_PUBLIC_GAP", personas: ["clinic_owner", "provider", "patient"], connectedDomains: ["scheduling", "patient", "identity", "consent", "insurance", "care", "coding", "revenue", "communications"], primaryIntent: "Run the full virtual-care workflow without leaving Klinikos", primaryCta: "See telemedicine workflow" }),
  capability({ id: "medical-scheduling", label: "Medical Scheduling", category: "operations", canonicalRoute: "/medical-scheduling", exposure: "PUBLIC_REQUIRED", maturity: "PRODUCT_EXISTS_PUBLIC_GAP", personas: ["front_desk", "provider", "patient", "owner"], connectedDomains: ["scheduling", "capacity", "grid", "communications", "insurance"], primaryIntent: "Coordinate patients, providers, rooms and resources", primaryCta: "See scheduling" }),
  capability({ id: "patient-portal", label: "Patient Portal", category: "patient", canonicalRoute: "/patient-portal", exposure: "PUBLIC_REQUIRED", maturity: "PRODUCT_EXISTS_PUBLIC_GAP", personas: ["patient", "clinic_owner"], connectedDomains: ["patient", "care", "payments", "communications", "telemedicine"], primaryIntent: "Give patients one place for next actions", primaryCta: "See patient experience" }),
  capability({ id: "patient-intake", label: "Digital Patient Intake", category: "patient", canonicalRoute: "/digital-patient-intake", exposure: "PUBLIC_REQUIRED", maturity: "PRODUCT_EXISTS_PUBLIC_GAP", personas: ["patient", "front_desk"], connectedDomains: ["patient", "forms", "consent", "care"], primaryIntent: "Complete reusable digital intake", primaryCta: "See intake workflow" }),
  capability({ id: "forms-consents", label: "Forms, Consents & E-sign", category: "patient", canonicalRoute: "/medical-forms-consents", exposure: "PUBLIC_REQUIRED", maturity: "PRODUCT_EXISTS_PUBLIC_GAP", personas: ["patient", "clinic_staff", "owner"], connectedDomains: ["documents", "consent", "patient", "care"], primaryIntent: "Create governed forms, signatures and consent workflows", primaryCta: "See forms and consent" }),
  capability({ id: "secure-messaging", label: "Secure Medical Messaging", category: "communications", canonicalRoute: "/secure-medical-messaging", exposure: "PUBLIC_REQUIRED", maturity: "PRODUCT_EXISTS_PUBLIC_GAP", personas: ["patient", "provider", "staff"], connectedDomains: ["communications", "patient", "care"], primaryIntent: "Keep healthcare communication inside governed workflows", primaryCta: "See communications" }),
  capability({ id: "front-desk-automation", label: "Front Desk Automation", category: "operations", canonicalRoute: "/front-desk-automation", exposure: "PUBLIC_REQUIRED", maturity: "PRODUCT_EXISTS_PUBLIC_GAP", personas: ["front_desk", "practice_manager", "owner"], connectedDomains: ["living_home", "scheduling", "communications", "insurance", "payments"], primaryIntent: "Reduce manual front-desk work", primaryCta: "Map my front desk" }),
  capability({ id: "ai-receptionist", label: "AI Medical Receptionist", category: "operations", canonicalRoute: "/ai-medical-receptionist", exposure: "PUBLIC_REQUIRED", maturity: "PLANNED", personas: ["owner", "front_desk"], connectedDomains: ["zumi", "communications", "crm", "scheduling"], primaryIntent: "Capture and route patient inquiries", primaryCta: "See AI receptionist" }),
  capability({ id: "healthcare-crm", label: "Healthcare CRM", category: "growth", canonicalRoute: "/healthcare-crm", exposure: "PUBLIC_REQUIRED", maturity: "PRODUCT_EXISTS_PUBLIC_GAP", personas: ["owner", "practice_manager", "sales_coordinator"], connectedDomains: ["crm", "communications", "scheduling", "payments"], primaryIntent: "Convert and retain patients/clients", primaryCta: "Map my growth workflow" }),
  capability({ id: "missed-call-recovery", label: "Missed-call Recovery", category: "growth", canonicalRoute: "/missed-call-recovery", exposure: "PUBLIC_REQUIRED", maturity: "PRODUCT_EXISTS_PUBLIC_GAP", personas: ["owner", "front_desk"], connectedDomains: ["communications", "crm", "scheduling", "revenue"], primaryIntent: "Recover missed patient opportunities", primaryCta: "See recovery workflow" }),
  capability({ id: "insurance-eligibility", label: "Insurance Eligibility", category: "insurance", canonicalRoute: "/insurance-eligibility", exposure: "PUBLIC_REQUIRED", maturity: "PRODUCT_EXISTS_PUBLIC_GAP", personas: ["front_desk", "biller", "owner"], connectedDomains: ["insurance", "patient", "scheduling", "revenue", "integration"], primaryIntent: "Verify coverage before care", primaryCta: "See insurance workflow" }),
  capability({ id: "prior-authorization", label: "Prior Authorization", category: "insurance", canonicalRoute: "/prior-authorization", exposure: "PUBLIC_REQUIRED", maturity: "PRODUCT_EXISTS_PUBLIC_GAP", personas: ["front_desk", "clinical_staff", "biller", "provider"], connectedDomains: ["insurance", "care", "payer", "revenue", "zumi"], primaryIntent: "Prepare, submit and monitor authorization work", primaryCta: "See authorization workflow" }),
  capability({ id: "medical-coding", label: "Medical Coding", category: "revenue", canonicalRoute: "/medical-coding", exposure: "PUBLIC_REQUIRED", maturity: "PRODUCT_EXISTS_PUBLIC_GAP", personas: ["provider", "coder", "biller"], connectedDomains: ["care", "evidence", "coding", "revenue", "zumi"], primaryIntent: "Link coding candidates to documentation evidence", primaryCta: "See coding workflow" }),
  capability({ id: "medical-billing", label: "Medical Billing", category: "revenue", canonicalRoute: "/medical-billing", exposure: "PUBLIC_REQUIRED", maturity: "PRODUCT_EXISTS_PUBLIC_GAP", personas: ["biller", "owner", "practice_manager"], connectedDomains: ["revenue", "financial", "claims", "insurance"], primaryIntent: "Operate billing from Klinikos", primaryCta: "See billing workflow" }),
  capability({ id: "revenue-cycle", label: "Revenue Cycle Management", category: "revenue", canonicalRoute: "/revenue-cycle-management", exposure: "PUBLIC_REQUIRED", maturity: "PRODUCT_EXISTS_PUBLIC_GAP", personas: ["biller", "owner", "enterprise"], connectedDomains: ["revenue", "claims", "insurance", "financial", "zumi"], primaryIntent: "Track clinical work toward payment", primaryCta: "Map my revenue cycle" }),
  capability({ id: "revenue-integrity", label: "Revenue Integrity", category: "revenue", canonicalRoute: "/revenue-integrity", exposure: "PUBLIC_REQUIRED", maturity: "PRODUCT_EXISTS_PUBLIC_GAP", personas: ["owner", "biller"], connectedDomains: ["care", "coding", "claims", "financial"], primaryIntent: "Find where legitimate payment progression stopped", primaryCta: "See revenue integrity" }),
  capability({ id: "claims", label: "Medical Claims", category: "revenue", canonicalRoute: "/medical-claims", exposure: "PUBLIC_REQUIRED", maturity: "PRODUCT_EXISTS_PUBLIC_GAP", personas: ["biller", "owner"], connectedDomains: ["claims", "clearinghouse", "payer", "financial"], primaryIntent: "Prepare and track claims", primaryCta: "See claims workflow" }),
  capability({ id: "clearinghouse", label: "Clearinghouse Connectivity", category: "revenue", canonicalRoute: "/clearinghouse-connectivity", exposure: "PUBLIC_REQUIRED", maturity: "VENDOR_DEPENDENT", personas: ["biller", "enterprise"], connectedDomains: ["claims", "integration", "payer"], primaryIntent: "Use clearinghouse rails without living in another portal", primaryCta: "See connectivity" }),
  capability({ id: "denials", label: "Denial Management", category: "revenue", canonicalRoute: "/denial-management", exposure: "PUBLIC_REQUIRED", maturity: "PRODUCT_EXISTS_PUBLIC_GAP", personas: ["biller", "owner"], connectedDomains: ["claims", "revenue", "zumi"], primaryIntent: "Resolve denials and prepare appeals", primaryCta: "See denial workflow" }),
  capability({ id: "payment-posting", label: "Payment Posting & Reconciliation", category: "revenue", canonicalRoute: "/payment-posting", exposure: "PUBLIC_REQUIRED", maturity: "PLANNED", personas: ["biller", "owner"], connectedDomains: ["financial", "revenue", "remittance"], primaryIntent: "Reconcile payer and patient payments", primaryCta: "See reconciliation" }),
  capability({ id: "patient-payments", label: "Patient Payments", category: "financial", canonicalRoute: "/patient-payments", exposure: "PUBLIC_REQUIRED", maturity: "PRODUCT_EXISTS_PUBLIC_GAP", personas: ["patient", "front_desk", "owner"], connectedDomains: ["financial", "patient", "scheduling", "commerce"], primaryIntent: "Collect and reconcile patient payments", primaryCta: "See payment workflow" }),
  capability({ id: "lab-results", label: "Labs & Results", category: "diagnostics", canonicalRoute: "/lab-results", exposure: "PUBLIC_REQUIRED", maturity: "PRODUCT_EXISTS_PUBLIC_GAP", personas: ["provider", "clinical_staff", "patient"], connectedDomains: ["orders", "results", "integration", "care"], primaryIntent: "Manage lab orders through review and follow-up", primaryCta: "See lab workflow" }),
  capability({ id: "medical-imaging", label: "Medical Imaging", category: "diagnostics", canonicalRoute: "/medical-imaging", exposure: "PUBLIC_REQUIRED", maturity: "PRODUCT_EXISTS_PUBLIC_GAP", personas: ["provider", "clinical_staff", "patient"], connectedDomains: ["orders", "results", "integration", "care"], primaryIntent: "Manage imaging orders, reports and follow-up", primaryCta: "See imaging workflow" }),
  capability({ id: "referrals", label: "Referral Management", category: "care-coordination", canonicalRoute: "/referral-management", exposure: "PUBLIC_REQUIRED", maturity: "PRODUCT_EXISTS_PUBLIC_GAP", personas: ["provider", "referral_coordinator", "patient"], connectedDomains: ["care", "network", "grid", "insurance", "documents"], primaryIntent: "Close referral loops across organizations", primaryCta: "See referral workflow" }),
  capability({ id: "medications", label: "Medication Management", category: "medication", canonicalRoute: "/medication-management", exposure: "PUBLIC_REQUIRED", maturity: "PRODUCT_EXISTS_PUBLIC_GAP", personas: ["provider", "clinical_staff", "patient"], connectedDomains: ["care", "pharmacy", "insurance", "integration"], primaryIntent: "Manage medication history and workflows", primaryCta: "See medication workflow" }),
  capability({ id: "population-health", label: "Population Health", category: "payer-enterprise", canonicalRoute: "/population-health", exposure: "PUBLIC_REQUIRED", maturity: "PLANNED", personas: ["enterprise", "payer", "care_manager"], connectedDomains: ["payer", "quality", "data", "care"], primaryIntent: "Operate care gaps and population workflows", primaryCta: "Talk to enterprise" }),
  capability({ id: "value-based-care", label: "Value-Based Care", category: "payer-enterprise", canonicalRoute: "/value-based-care", exposure: "PUBLIC_REQUIRED", maturity: "PLANNED", personas: ["enterprise", "payer", "owner"], connectedDomains: ["payer", "quality", "revenue", "data"], primaryIntent: "Connect operational work to value-based performance", primaryCta: "Talk to enterprise" }),
  capability({ id: "payer-operations", label: "Payer Operations", category: "payer-enterprise", canonicalRoute: "/payer-operations", exposure: "PUBLIC_REQUIRED", maturity: "PLANNED", personas: ["payer", "enterprise"], connectedDomains: ["payer", "interoperability", "authorization", "quality"], primaryIntent: "Improve payer-provider operations", primaryCta: "Talk to enterprise" }),
  capability({ id: "grid", label: "Grid", category: "network", canonicalRoute: "/grid", exposure: "PUBLIC_REQUIRED", maturity: "CURRENT_ROUTE", personas: ["professional", "organization", "student", "vendor"], connectedDomains: ["grid", "identity", "financial", "network", "edu"], primaryIntent: "Find or offer healthcare opportunities and resources", primaryCta: "Join Grid" }),
  capability({ id: "healthcare-jobs", label: "Healthcare Jobs", category: "network", canonicalRoute: "/healthcare-jobs", exposure: "PUBLIC_REQUIRED", maturity: "PLANNED", personas: ["professional", "employer"], connectedDomains: ["grid", "identity", "credentials"], primaryIntent: "Find and post healthcare work", primaryCta: "Join Grid" }),
  capability({ id: "healthcare-shifts", label: "Healthcare Shifts", category: "network", canonicalRoute: "/healthcare-shifts", exposure: "PUBLIC_REQUIRED", maturity: "PLANNED", personas: ["professional", "clinic"], connectedDomains: ["grid", "scheduling", "credentials"], primaryIntent: "Fill and find eligible shifts", primaryCta: "Join Grid" }),
  capability({ id: "provider-network", label: "Provider Network", category: "network", canonicalRoute: "/provider-network", exposure: "PUBLIC_REQUIRED", maturity: "PRODUCT_EXISTS_PUBLIC_GAP", personas: ["provider", "clinic"], connectedDomains: ["network", "grid", "identity", "credentials"], primaryIntent: "Build governed professional relationships", primaryCta: "Create profile" }),
  capability({ id: "medical-office-space", label: "Medical Office & Room Marketplace", category: "network", canonicalRoute: "/medical-office-space", exposure: "PUBLIC_REQUIRED", maturity: "PLANNED", personas: ["owner", "professional"], connectedDomains: ["grid", "scheduling", "financial"], primaryIntent: "Offer and discover clinical space/capacity", primaryCta: "List or find space" }),
  capability({ id: "provider-credentialing", label: "Provider Credentialing", category: "identity", canonicalRoute: "/provider-credentialing", exposure: "PUBLIC_REQUIRED", maturity: "PRODUCT_EXISTS_PUBLIC_GAP", personas: ["professional", "clinic", "enterprise"], connectedDomains: ["identity", "credentials", "grid", "enterprise"], primaryIntent: "Track verified professional eligibility", primaryCta: "Create professional profile" }),
  capability({ id: "edu", label: "Klinikos EDU", category: "education", canonicalRoute: "/edu", exposure: "PUBLIC_REQUIRED", maturity: "CURRENT_ROUTE", personas: ["student", "instructor", "institution", "employer"], connectedDomains: ["edu", "grid", "identity"], primaryIntent: "Train healthcare workers through governed simulation and evidence", primaryCta: "Explore EDU" }),
  capability({ id: "virtual-clinic", label: "Virtual Clinic Simulation", category: "education", canonicalRoute: "/virtual-clinic-simulation", exposure: "PUBLIC_REQUIRED", maturity: "PRODUCT_EXISTS_PUBLIC_GAP", personas: ["student", "instructor", "institution"], connectedDomains: ["edu", "care", "synthetic-data"], primaryIntent: "Practice healthcare workflows safely", primaryCta: "Explore the Virtual Clinic" }),
  capability({ id: "clinical-placements", label: "Clinical Placements", category: "education", canonicalRoute: "/clinical-placements", exposure: "PUBLIC_REQUIRED", maturity: "PLANNED", personas: ["student", "school", "preceptor", "clinic"], connectedDomains: ["edu", "grid", "network", "credentials"], primaryIntent: "Connect training to supervised opportunities", primaryCta: "Join Grid" }),
  capability({ id: "no-fault", label: "No-Fault Medical Software", category: "specialty", canonicalRoute: "/no-fault-medical-software", exposure: "PUBLIC_REQUIRED", maturity: "PRODUCT_EXISTS_PUBLIC_GAP", personas: ["provider", "case_manager", "biller", "owner"], connectedDomains: ["care", "cases", "clinical_change", "bodymap", "revenue"], primaryIntent: "Run longitudinal No-Fault clinical and case operations", primaryCta: "See No-Fault workflow" }),
  capability({ id: "workers-comp", label: "Workers' Compensation Medical Software", category: "specialty", canonicalRoute: "/workers-comp-medical-software", exposure: "PUBLIC_REQUIRED", maturity: "PRODUCT_EXISTS_PUBLIC_GAP", personas: ["provider", "case_manager", "biller", "owner"], connectedDomains: ["care", "cases", "revenue"], primaryIntent: "Manage Workers' Compensation clinical and administrative workflow", primaryCta: "See Workers' Comp workflow" }),
  capability({ id: "med-spa", label: "Med Spa Software", category: "specialty", canonicalRoute: "/med-spa-software", exposure: "PUBLIC_REQUIRED", maturity: "PRODUCT_EXISTS_PUBLIC_GAP", personas: ["med_spa_owner", "injector", "front_desk"], connectedDomains: ["luxe-medi", "crm", "inventory", "payments", "grid"], primaryIntent: "Run med spa clinical, client, inventory and growth workflows", primaryCta: "Map my med spa" }),
  capability({ id: "inventory", label: "Healthcare Inventory Management", category: "operations", canonicalRoute: "/healthcare-inventory-management", exposure: "PUBLIC_REQUIRED", maturity: "PRODUCT_EXISTS_PUBLIC_GAP", personas: ["owner", "clinical_staff"], connectedDomains: ["inventory", "procedures", "procurement", "financial"], primaryIntent: "Track stock, lots, expiration and use", primaryCta: "See inventory workflow" }),
  capability({ id: "practice-launch", label: "Practice Launch", category: "business", canonicalRoute: "/practice-launch", exposure: "PUBLIC_REQUIRED", maturity: "PLANNED", personas: ["new_owner", "professional"], connectedDomains: ["commercial", "onboarding", "care", "grid", "financial", "communications"], primaryIntent: "Launch a healthcare practice with Klinikos as operating foundation", primaryCta: "Plan my practice" }),
  capability({ id: "enterprise", label: "Enterprise Healthcare Software", category: "enterprise", canonicalRoute: "/enterprise-healthcare-software", exposure: "PUBLIC_REQUIRED", maturity: "PLANNED", personas: ["enterprise", "it", "security", "executive"], connectedDomains: ["enterprise", "identity", "integration", "security", "analytics"], primaryIntent: "Operate multi-organization healthcare networks", primaryCta: "Talk to enterprise" }),
  capability({ id: "interoperability", label: "Healthcare Interoperability", category: "enterprise", canonicalRoute: "/healthcare-interoperability", exposure: "PUBLIC_REQUIRED", maturity: "PRODUCT_EXISTS_PUBLIC_GAP", personas: ["enterprise", "it", "provider"], connectedDomains: ["integration", "care", "payer", "patient"], primaryIntent: "Exchange healthcare information through governed standards and adapters", primaryCta: "See interoperability" }),
  capability({ id: "healthcare-security", label: "Healthcare Security", category: "trust", canonicalRoute: "/healthcare-security", exposure: "PUBLIC_REQUIRED", maturity: "GOVERNANCE_ONLY", personas: ["enterprise", "security", "owner"], connectedDomains: ["security", "trust", "platform"], primaryIntent: "Understand verified Klinikos security controls", primaryCta: "Visit Trust Center" }),
  capability({ id: "developer-platform", label: "Developer Platform", category: "developer", canonicalRoute: "/developer-platform", exposure: "PUBLIC_REQUIRED", maturity: "PLANNED", personas: ["developer", "partner", "enterprise"], connectedDomains: ["integration", "api", "partners"], primaryIntent: "Build governed extensions and integrations", primaryCta: "Explore developer platform" }),
  capability({ id: "remote-monitoring", label: "Remote Patient Monitoring", category: "remote-care", canonicalRoute: "/remote-patient-monitoring", exposure: "PUBLIC_REQUIRED", maturity: "PLANNED", personas: ["provider", "patient", "enterprise"], connectedDomains: ["devices", "patient", "care", "zumi"], primaryIntent: "Bring governed home observations into care workflows", primaryCta: "Explore remote care" }),
  capability({ id: "research", label: "Clinical Research Workflows", category: "research", canonicalRoute: "/clinical-research-workflows", exposure: "PUBLIC_REQUIRED", maturity: "PLANNED", personas: ["researcher", "site", "sponsor", "enterprise"], connectedDomains: ["research", "data", "consent", "identity"], primaryIntent: "Coordinate separately governed research workflows", primaryCta: "Talk to enterprise" }),
  capability({ id: "public-health", label: "Public Health Interoperability", category: "government", canonicalRoute: "/public-health-interoperability", exposure: "PUBLIC_REQUIRED", maturity: "PLANNED", personas: ["public_health", "enterprise", "government"], connectedDomains: ["integration", "public-health", "care"], primaryIntent: "Support governed public-health exchange workflows", primaryCta: "Talk to enterprise" }),
] as const satisfies readonly PublicCapabilityDefinition[];

export function getPublicCapabilityById(id: string) {
  return publicCapabilityRegistry.find((item) => item.id === id);
}

export function getPublicCapabilityByRoute(route: string) {
  return publicCapabilityRegistry.find((item) => item.canonicalRoute === route);
}

export function getPublicCapabilitiesByCategory(category: string) {
  return publicCapabilityRegistry.filter((item) => item.category === category);
}
