export type PhiGate = "forbidden" | "hipaa-gated" | "minimum-necessary";

export type ScreenExperienceContract = {
  id: string;
  screenFamily: string;
  routePatterns: readonly string[];
  audiences: readonly string[];
  contextRequirements: readonly string[];
  visibleByDefault: readonly string[];
  intentionallyHidden: readonly string[];
  discoverable: readonly string[];
  promotable: readonly string[];
  eligibility: readonly string[];
  entitlement: readonly string[];
  authority: readonly string[];
  dataProjection: readonly string[];
  minimumNecessary: readonly string[];
  actions: readonly string[];
  zumi: {
    readScope: readonly string[];
    inferScope: readonly string[];
    recommend: readonly string[];
    prepareDraft: readonly string[];
    executeViaAuthorizedTools: readonly string[];
    forbidden: readonly string[];
  };
  aiProcessing: {
    allowedDataClasses: readonly string[];
    prohibitedDataClasses: readonly string[];
    purpose: readonly string[];
    processingBasis: readonly string[];
    agreementKey: string;
    phiGate: PhiGate;
    modelTraining: "not-permitted-by-default";
  };
  audit: readonly string[];
  provenance: readonly string[];
  promotionPolicy: readonly string[];
  commercialTargetingBoundary: readonly string[];
  states: {
    denied: string;
    blocked: string;
    loading: string;
    empty: string;
    error: string;
  };
  mobile: string;
  accessibility: string;
};

export const REQUIRED_SCREEN_FAMILIES = [
  "public-discovery",
  "auth-signup",
  "person-home",
  "grid-professional",
  "grid-organization",
  "edu-learner",
  "edu-instructor",
  "patient-home",
  "provider-home",
  "current-visit",
  "clinical-handoff",
  "biller-money-readiness",
  "clinic-owner-operations",
  "enterprise-admin",
  "organization-claim-verification",
  "telemedicine-encounter",
] as const;

const COMMON_ZUMI_FORBIDDEN = [
  "grant-authority",
  "manufacture-verified-facts",
  "override-deterministic-eligibility",
  "override-server-side-permissions",
  "invent-payment-or-settlement-state",
  "silently-cross-organization-context",
  "silently-expand-data-scope",
] as const;

const COMMON_STATES = {
  denied: "explain-the-boundary-without-revealing-protected-data-and-offer-a-lawful-next-step",
  blocked: "show-the-specific-blocker-owner-and-next-permitted-action",
  loading: "preserve-context-and-show-progress-without-inventing-completion",
  empty: "explain-what-can-appear-here-and-the-next-useful-action",
  error: "preserve-user-work-surface-a-correlation-reference-and-a-retry-or-support-path",
} as const;

const COMMON_PROVENANCE = [
  "actor",
  "organization-or-public-context",
  "source-system",
  "source-object-when-applicable",
  "timestamp",
  "agreement-version-when-ai-processing-is-involved",
  "zumi-model-or-tool-provenance-when-applicable",
] as const;

const COMMON_AUDIT = [
  "context-selection",
  "authority-decision-for-consequential-actions",
  "zumi-tool-execution",
  "material-data-disclosure",
  "agreement-and-consent-basis-when-required",
] as const;

const COMMON_MOBILE = "compose-the-primary-task-for-mobile-first-use; do-not-shrink-a-desktop-dashboard";
const COMMON_ACCESSIBILITY = "keyboard-screen-reader-focus-zoom-reflow-status-announcement-and-non-color-state-contract-required";

function contract(value: ScreenExperienceContract): ScreenExperienceContract {
  return value;
}

export const KLINIKOS_SCREEN_EXPERIENCE_CONTRACTS = [
  contract({
    id: "public-discovery",
    screenFamily: "public acquisition, problem routes, public Grid discovery and Public Zumi",
    routePatterns: ["/", "/ehr*", "/telemedicine*", "/no-fault*", "/billing-readiness*", "/specialties/*", "/grid/public*", "/edu/public*"],
    audiences: ["anonymous-visitor", "prospect", "student", "professional", "patient", "organization-buyer"],
    contextRequirements: ["entry-route", "public-safe-intent", "locale-or-jurisdiction-when-required"],
    visibleByDefault: ["problem-specific-value", "public-safe-proof", "public-safe-discovery", "ask-klinikos", "next-useful-action"],
    intentionallyHidden: ["private-account-data", "clinical-records", "organization-internals", "private-grid-data", "restricted-product-secrets", "unverified-personalization"],
    discoverable: ["relevant-public-routes", "public-grid-supply-or-demand", "public-education", "sign-up-when-persistence-matters"],
    promotable: ["create-free-identity", "save-intent", "continue-into-grid", "request-clinic-conversation", "join-education-opportunity"],
    eligibility: ["public-safe-content-policy", "jurisdictional-availability-when-applicable"],
    entitlement: ["public-access-only-until-authenticated-entitlement-exists"],
    authority: ["no-operational-authority-from-public-use"],
    dataProjection: ["public-content", "public-safe-resource-data", "bounded-intent-classification"],
    minimumNecessary: ["do-not-request-sensitive-data-to-answer-a-public-question", "persist-only-safe-structured-intent-when-needed"],
    actions: ["search", "ask-public-zumi", "view-public-safe-detail", "begin-signup", "request-contact"],
    zumi: {
      readScope: ["public-page-context", "current-public-prompt", "public-safe-catalog"],
      inferScope: ["bounded-intent-class", "likely-next-public-route", "whether-persistence-would-create-value"],
      recommend: ["public-safe-next-step", "relevant-capability", "signup-only-when-action-or-persistence-benefits-user"],
      prepareDraft: ["public-safe-answer", "public-safe-comparison-summary", "safe-signup-handoff-summary"],
      executeViaAuthorizedTools: ["public-search-and-routing-only"],
      forbidden: [...COMMON_ZUMI_FORBIDDEN, "accept-phi", "represent-public-answer-as-clinical-advice-or-professional-truth"],
    },
    aiProcessing: {
      allowedDataClasses: ["public-content", "user-supplied-non-sensitive-intent", "public-safe-resource-metadata"],
      prohibitedDataClasses: ["phi", "private-clinical-record", "credentials-or-secrets", "private-organization-records"],
      purpose: ["public-navigation", "intent-understanding", "public-information-assistance"],
      processingBasis: ["public-ai-notice", "user-request-to-use-public-zumi", "service-delivery-purpose-limitation"],
      agreementKey: "public-zumi-ai-service-notice",
      phiGate: "forbidden",
      modelTraining: "not-permitted-by-default",
    },
    audit: ["abuse-and-security-events", "authenticated-handoff-when-created"],
    provenance: [...COMMON_PROVENANCE],
    promotionPolicy: ["promote-only-capabilities-relevant-to-current-intent", "promotion-never-implies-eligibility-entitlement-or-authority"],
    commercialTargetingBoundary: ["public-intent-may-inform-relevant-product-education", "no-clinical-or-phi-context-for-commercial-targeting", "no-sale-of-conversation-content-as-a-product"],
    states: { ...COMMON_STATES },
    mobile: COMMON_MOBILE,
    accessibility: COMMON_ACCESSIBILITY,
  }),

  contract({
    id: "auth-signup",
    screenFamily: "identity creation, sign-in and progressive relationship routing",
    routePatterns: ["/login*", "/signup*", "/register*", "/auth/*", "/onboarding*"],
    audiences: ["new-user", "returning-user", "invited-user"],
    contextRequirements: ["safe-handoff-intent", "identity-session", "entry-source", "claimed-relationship-when-supplied"],
    visibleByDefault: ["minimum-necessary-identity-fields", "why-this-information-is-needed", "relevant-terms-and-ai-processing-notice", "continue-action"],
    intentionallyHidden: ["unrelated-product-enrollment", "irrelevant-role-fields", "private-organization-data-before-authority", "all-platform-navigation"],
    discoverable: ["supported-relationship-types", "privacy-and-terms", "organization-claim-path", "professional-claim-path"],
    promotable: ["the-starting-experience-implied-by-intent", "claim-a-relevant-relationship", "verify-only-when-next-action-requires-it"],
    eligibility: ["account-eligibility", "age-or-jurisdiction-rules-when-applicable", "invitation-validity-when-used"],
    entitlement: ["free-identity-default", "invited-or-purchased-entitlement-after-server-verification"],
    authority: ["authentication-establishes-session-not-professional-or-organization-authority", "claims-remain-unverified-until-evidence-satisfies-policy"],
    dataProjection: ["identity-fields", "safe-intent-class", "agreement-version", "relationship-claim-state"],
    minimumNecessary: ["ask-only-fields-needed-for-current-next-step", "defer-credential-or-organization-proof-until-required"],
    actions: ["create-account", "sign-in", "accept-applicable-agreement", "claim-relationship", "continue-to-promoted-experience"],
    zumi: {
      readScope: ["safe-handoff-intent", "non-sensitive-onboarding-answers", "public-entry-context"],
      inferScope: ["likely-starting-experience", "next-minimum-question", "whether-verification-is-required-for-requested-action"],
      recommend: ["next-onboarding-step", "relevant-free-experience", "verification-when-action-requires-it"],
      prepareDraft: ["plain-language-explanation-of-why-a-field-or-verification-is-needed"],
      executeViaAuthorizedTools: ["route-after-authentication", "create-non-authoritative-onboarding-state"],
      forbidden: [...COMMON_ZUMI_FORBIDDEN, "invent-identity", "mark-self-claim-as-verified", "bind-an-organization-without-authorized-signature"],
    },
    aiProcessing: {
      allowedDataClasses: ["safe-intent-class", "onboarding-preferences", "non-sensitive-role-or-goal-claims"],
      prohibitedDataClasses: ["passwords", "authentication-secrets", "payment-secrets", "phi-unless-separate-approved-workflow"],
      purpose: ["experience-routing", "onboarding-assistance", "plain-language-explanation"],
      processingBasis: ["accepted-applicable-terms", "ai-service-processing-notice", "user-requested-onboarding-assistance"],
      agreementKey: "global_terms_ai_service_processing",
      phiGate: "forbidden",
      modelTraining: "not-permitted-by-default",
    },
    audit: [...COMMON_AUDIT, "agreement-version-hash-and-signature-evidence"],
    provenance: [...COMMON_PROVENANCE],
    promotionPolicy: ["signup-seeds-not-permanently-classifies", "promote-starting-experience-from-intent-and-relationship", "do-not-upsell-unrelated-systems-during-identity-creation"],
    commercialTargetingBoundary: ["onboarding-goal-may-shape-product-education", "identity-or-sensitive-data-not-used-as-unrestricted-ad-targeting", "no-clinical-or-phi-context-for-commercial-targeting"],
    states: { ...COMMON_STATES },
    mobile: COMMON_MOBILE,
    accessibility: COMMON_ACCESSIBILITY,
  }),

  contract({
    id: "person-home",
    screenFamily: "person-level Living Home, basic profile and governed ecosystem entry",
    routePatterns: ["/member*"],
    audiences: ["authenticated-person", "new-free-member", "person-with-multiple-contexts"],
    contextRequirements: ["authenticated-person-account", "active-person-record", "safe-restored-intent-when-present"],
    visibleByDefault: ["own-basic-profile", "claimed-versus-verified-state", "real-next-actions", "public-safe-grid-path-and-education-discovery", "active-membership-summaries-only-when-authorized"],
    intentionallyHidden: ["patient-records-without-separate-patient-or-proxy-authority", "organization-internals-without-active-membership-and-purpose", "professional-authority-not-established-by-account", "private-ranking-policy-or-security-logic", "other-people-private-data"],
    discoverable: ["public-safe-grid", "relevant-paths", "public-or-entitled-education", "governed-organization-connection", "profile-and-verification-next-steps"],
    promotable: ["complete-own-basic-profile", "explore-public-safe-grid", "continue-relevant-path", "begin-governed-relationship-or-verification-when-needed"],
    eligibility: ["active-person-account-for-this-screen", "action-specific-eligibility-remains-server-owned", "discovery-never-implies-regulated-eligibility"],
    entitlement: ["person-level-living-home-is-free-by-default", "paid-capability-requires-separate-explicit-entitlement"],
    authority: ["authentication-proves-account-control-not-professional-organization-patient-or-clinical-authority", "organization-context-requires-separate-active-membership-and-authorized-context-selection"],
    dataProjection: ["own-basic-person-profile", "own-claim-and-verification-summaries", "effective-membership-summary-when-authorized", "public-safe-path-grid-and-education-metadata"],
    minimumNecessary: ["project-only-the-current-person-and-safe-next-action", "summarize-evidence-state-without-raw-documents-or-hidden-policy", "exclude-patient-and-organization-data-without-separate-authority"],
    actions: ["view-own-profile-state", "explore-public-safe-grid", "continue-safe-path", "begin-governed-relationship-or-verification", "sign-out"],
    zumi: {
      readScope: ["minimum-necessary-person-home-projection", "safe-restored-intent", "public-safe-path-grid-and-education-metadata"],
      inferScope: ["likely-next-safe-path", "missing-non-authoritative-profile-context", "whether-a-requested-action-needs-separate-verification-or-organization-context"],
      recommend: ["public-safe-next-step", "profile-completion", "governed-verification-or-relationship-step-when-required"],
      prepareDraft: ["user-reviewable-goal-or-profile-summary", "relationship-or-verification-request-without-asserting-approval"],
      executeViaAuthorizedTools: ["route-to-public-safe-destination", "save-user-confirmed-non-authoritative-preference-through-an-authorized-tool"],
      forbidden: [...COMMON_ZUMI_FORBIDDEN, "read-patient-records-from-person-account-alone", "invent-organization-membership", "promote-a-claim-to-verified-authority", "treat-free-account-or-payment-as-grid-eligibility"],
    },
    aiProcessing: {
      allowedDataClasses: ["own-basic-profile", "safe-intent", "claimed-goals-and-preferences", "public-safe-path-grid-and-education-metadata"],
      prohibitedDataClasses: ["phi", "patient-records", "other-people-private-data", "organization-private-data-without-membership-and-purpose", "authentication-secrets", "raw-high-risk-identity-or-credential-documents"],
      purpose: ["person-level-navigation", "first-value-guidance", "profile-and-path-assistance"],
      processingBasis: ["accepted-applicable-terms", "ai-service-processing-notice", "user-requested-person-home-assistance"],
      agreementKey: "global_terms_ai_service_processing",
      phiGate: "forbidden",
      modelTraining: "not-permitted-by-default",
    },
    audit: [...COMMON_AUDIT, "person-home-context-selection", "relationship-or-verification-handoff"],
    provenance: [...COMMON_PROVENANCE, "person-account-session"],
    promotionPolicy: ["promote-from-current-purpose-and-real-state", "free-account-never-implies-verification-eligibility-entitlement-or-authority", "do-not-force-a-permanent-persona"],
    commercialTargetingBoundary: ["declared-goals-may-shape-contextual-product-education", "no-clinical-or-phi-context-for-commercial-targeting", "identity-evidence-and-private-relationship-data-are-not-ad-audiences"],
    states: { ...COMMON_STATES },
    mobile: "keep-the-active-object-and-next-action-primary; present-the-inspector-as-an-accessible-drawer-without-removing-authority-or-evidence-context",
    accessibility: COMMON_ACCESSIBILITY,
  }),

  contract({
    id: "grid-professional",
    screenFamily: "individual professional opportunity, availability and network experience",
    routePatterns: ["/grid*", "/professional*", "/opportunities*", "/availability*"],
    audiences: ["student", "professional", "contractor", "clinician-seeking-opportunity"],
    contextRequirements: ["identity", "active-professional-or-student-relationship", "current-intent", "jurisdiction", "credential-state-when-required"],
    visibleByDefault: ["relevant-opportunities", "availability", "professional-profile-summary", "eligibility-blockers", "next-career-or-income-action"],
    intentionallyHidden: ["patient-records", "employer-private-data", "other-users-private-eligibility-evidence", "organization-clinical-workspaces", "irrelevant-admin-tools"],
    discoverable: ["jobs", "shifts", "services", "spaces", "training", "placements", "professional-connections"],
    promotable: ["complete-profile", "verify-required-credential", "add-availability", "relevant-education", "practice-formation-or-organization-tools-when-intent-supports-it"],
    eligibility: ["hard-credential-rules-before-ranking", "jurisdiction", "scope", "availability", "organization-specific-requirements"],
    entitlement: ["basic-individual-grid-participation-free-by-default", "paid-capabilities-only-when-explicitly-entitled"],
    authority: ["may-act-only-for-own-profile-or-authorized-representation", "match-does-not-create-professional-authority"],
    dataProjection: ["public-or-consented-professional-profile", "eligibility-result", "opportunity-requirements", "availability"],
    minimumNecessary: ["share-only-fields-required-for-discovery-or-eligibility", "do-not-expose-clinical-employment-context-from-another-organization"],
    actions: ["express-i-need", "express-i-have", "update-availability", "view-opportunity", "apply-or-offer-when-eligible"],
    zumi: {
      readScope: ["professional-profile", "declared-goals", "availability", "credential-status", "grid-opportunity-metadata"],
      inferScope: ["intent", "career-or-income-goal", "potential-fit-subject-to-deterministic-eligibility"],
      recommend: ["eligible-opportunities", "profile-improvements", "training-that-addresses-a-known-gap"],
      prepareDraft: ["application-message", "professional-introduction", "availability-summary"],
      executeViaAuthorizedTools: ["save-search", "update-user-authorized-availability", "submit-user-confirmed-grid-action"],
      forbidden: [...COMMON_ZUMI_FORBIDDEN, "bypass-credential-or-jurisdiction-rule", "expose-clinic-patient-context", "fabricate-experience-or-credentials"],
    },
    aiProcessing: {
      allowedDataClasses: ["professional-profile", "career-goals", "availability", "credential-status", "grid-opportunity-metadata"],
      prohibitedDataClasses: ["phi", "other-organization-private-clinical-data", "authentication-secrets"],
      purpose: ["grid-discovery", "opportunity-matching-assistance", "career-navigation"],
      processingBasis: ["accepted-grid-or-global-terms", "ai-service-processing-notice", "user-requested-grid-assistance"],
      agreementKey: "global_terms_ai_service_processing",
      phiGate: "forbidden",
      modelTraining: "not-permitted-by-default",
    },
    audit: [...COMMON_AUDIT, "eligibility-decision-source", "offer-acceptance-reservation-and-fulfillment-state-transitions"],
    provenance: [...COMMON_PROVENANCE],
    promotionPolicy: ["promote-income-career-and-network-value-before-unrelated-saas", "education-promotion-must-map-to-a-real-user-goal-or-eligibility-gap"],
    commercialTargetingBoundary: ["professional-goals-may-support-contextual-product-promotion", "no-clinical-or-phi-context-for-commercial-targeting", "do-not-sell-private-grid-profile-data-as-an-ad-audience"],
    states: { ...COMMON_STATES },
    mobile: COMMON_MOBILE,
    accessibility: COMMON_ACCESSIBILITY,
  }),

  contract({
    id: "grid-organization",
    screenFamily: "organization demand, capacity, staffing, referral and resource exchange",
    routePatterns: ["/grid/organization*", "/organization/*/grid*", "/clinic/grid*"],
    audiences: ["clinic-owner", "organization-admin", "authorized-recruiter", "authorized-operations-user"],
    contextRequirements: ["verified-organization-context", "organization-membership", "role", "authority", "current-demand-or-capacity-intent"],
    visibleByDefault: ["organization-demand", "eligible-supply", "capacity-opportunities", "open-grid-work", "operational-next-actions"],
    intentionallyHidden: ["patient-clinical-details", "unrelated-departments", "private-candidate-data-before-permitted-stage", "enterprise-settings-without-authority"],
    discoverable: ["professionals", "services", "space", "equipment", "referral-capacity", "education-and-placement-supply"],
    promotable: ["post-demand", "offer-capacity", "automate-repeated-grid-workflow", "connect-organization-operations-when-demonstrably-relevant"],
    eligibility: ["organization-authorization", "resource-specific-policy", "hard-professional-or-facility-eligibility"],
    entitlement: ["organization-grid-plan-or-contract", "transaction-specific-entitlement-where-applicable"],
    authority: ["organization-scoped-authority", "financial-or-contractual-actions-require-specific-authority"],
    dataProjection: ["organization-demand", "candidate-or-resource-eligibility-view", "capacity", "transaction-state"],
    minimumNecessary: ["candidate-data-limited-to-stage-and-purpose", "patient-identifiers-excluded-from-grid-unless-separate-governed-referral-workflow"],
    actions: ["post-demand", "review-eligible-supply", "make-offer", "reserve", "confirm-fulfillment", "manage-authorized-grid-work"],
    zumi: {
      readScope: ["authorized-organization-grid-context", "demand", "capacity", "eligibility-results", "transaction-state"],
      inferScope: ["operational-need", "capacity-opportunity", "repeat-workflow-pattern"],
      recommend: ["eligible-supply", "capacity-use", "workflow-automation-opportunity"],
      prepareDraft: ["opportunity-posting", "offer-message", "resource-request", "internal-grid-summary"],
      executeViaAuthorizedTools: ["create-user-confirmed-demand", "send-user-confirmed-offer", "update-authorized-grid-state"],
      forbidden: [...COMMON_ZUMI_FORBIDDEN, "rank-ineligible-supply-as-eligible", "use-patient-clinical-data-as-general-grid-ranking-signal", "create-contractual-authority"],
    },
    aiProcessing: {
      allowedDataClasses: ["organization-operational-data", "grid-demand-and-capacity", "professional-eligibility-metadata", "transaction-metadata"],
      prohibitedDataClasses: ["phi-unrelated-to-approved-referral-workflow", "authentication-secrets", "restricted-clinical-records"],
      purpose: ["organization-grid-orchestration", "capacity-discovery", "staffing-and-resource-assistance"],
      processingBasis: ["organization-service-agreement", "ai-service-processing-notice", "authorized-user-request"],
      agreementKey: "global_terms_ai_service_processing",
      phiGate: "forbidden",
      modelTraining: "not-permitted-by-default",
    },
    audit: [...COMMON_AUDIT, "organization-scope", "financial-and-transaction-state-transitions"],
    provenance: [...COMMON_PROVENANCE],
    promotionPolicy: ["promote-operational-capabilities-from-observed-non-clinical-friction", "do-not-force-clinical-system-replacement-to-use-grid"],
    commercialTargetingBoundary: ["organization-operational-patterns-may-support-contextual-product-education-under-contract", "no-clinical-or-phi-context-for-commercial-targeting", "no-cross-customer-data-sharing"],
    states: { ...COMMON_STATES },
    mobile: COMMON_MOBILE,
    accessibility: COMMON_ACCESSIBILITY,
  }),

  contract({
    id: "edu-learner",
    screenFamily: "learner, simulation, competency and career progression",
    routePatterns: ["/edu*", "/learn*", "/student*", "/programs/*"],
    audiences: ["student", "learner", "career-transition-user"],
    contextRequirements: ["identity", "program-or-learning-intent", "enrollment-when-required", "current-learning-state"],
    visibleByDefault: ["next-learning-action", "assigned-or-chosen-content", "progress", "feedback", "eligible-career-or-grid-next-step"],
    intentionallyHidden: ["instructor-only-rubrics-before-release", "other-learners-private-data", "clinic-patient-data", "professional-authority-not-yet-earned-or-verified"],
    discoverable: ["courses", "programs", "simulations", "career-readiness", "eligible-grid-pathways"],
    promotable: ["next-module", "relevant-practice", "career-opportunity-after-eligibility", "credential-verification-when-lifecycle-requires-it"],
    eligibility: ["program-enrollment-or-public-course-rules", "prerequisites", "institution-policy"],
    entitlement: ["free-or-program-funded-learning", "paid-course-or-institutional-entitlement-where-applicable"],
    authority: ["learner-authority-only", "completion-does-not-create-professional-authority"],
    dataProjection: ["learner-profile", "progress", "assessment-evidence", "released-feedback", "career-goal"],
    minimumNecessary: ["synthetic-data-first-for-clinical-simulation", "no-real-patient-data-in-learning-environment-by-default"],
    actions: ["learn", "practice", "submit-assessment", "review-feedback", "declare-career-goal", "enter-eligible-grid-next-step"],
    zumi: {
      readScope: ["authorized-learning-content", "learner-progress", "submitted-work", "career-goal"],
      inferScope: ["learning-gap", "next-practice-area", "career-intent"],
      recommend: ["next-learning-action", "practice-exercise", "career-readiness-step"],
      prepareDraft: ["study-plan", "practice-feedback-explanation", "resume-or-application-support-without-fabrication"],
      executeViaAuthorizedTools: ["save-learning-plan", "launch-authorized-simulation", "route-to-human-review"],
      forbidden: [...COMMON_ZUMI_FORBIDDEN, "mark-human-reviewed-competency-without-authorized-review", "manufacture-credential", "fabricate-career-history"],
    },
    aiProcessing: {
      allowedDataClasses: ["learning-record", "synthetic-simulation-data", "learner-submissions", "career-goals"],
      prohibitedDataClasses: ["real-phi-by-default", "other-learners-private-data", "authentication-secrets"],
      purpose: ["learning-assistance", "simulation-feedback", "career-readiness"],
      processingBasis: ["learner-or-program-agreement", "ai-service-processing-notice", "education-purpose-limitation"],
      agreementKey: "global_terms_ai_service_processing",
      phiGate: "forbidden",
      modelTraining: "not-permitted-by-default",
    },
    audit: [...COMMON_AUDIT, "assessment-submission", "human-review-and-completion-evidence"],
    provenance: [...COMMON_PROVENANCE],
    promotionPolicy: ["career-promotion-follows-demonstrated-goal-and-eligibility", "do-not-represent-training-as-licensure"],
    commercialTargetingBoundary: ["learning-and-career-goal-may-drive-contextual-program-recommendations", "no-clinical-or-phi-context-for-commercial-targeting", "no-sale-of-assessment-responses-as-ad-data"],
    states: { ...COMMON_STATES },
    mobile: COMMON_MOBILE,
    accessibility: COMMON_ACCESSIBILITY,
  }),

  contract({
    id: "edu-instructor",
    screenFamily: "instructor cohort, session, assessment and evidence review",
    routePatterns: ["/edu/instructor*", "/instructor*", "/cohorts/*", "/assessments/review*"],
    audiences: ["instructor", "program-admin", "authorized-workforce-reviewer"],
    contextRequirements: ["verified-program-relationship", "instructor-or-review-authority", "active-cohort-or-session"],
    visibleByDefault: ["roster-status", "session-plan", "participant-progress", "assessment-queue", "completion-evidence"],
    intentionallyHidden: ["unrelated-cohorts", "private-clinical-data", "learner-data-outside-program-purpose", "hidden-answer-keys-when-not-needed"],
    discoverable: ["assigned-cohorts", "authorized-curriculum", "rubrics", "reporting"],
    promotable: ["review-queue", "session-adjustment", "program-improvement", "placement-network-when-program-authorizes-it"],
    eligibility: ["program-assignment", "instructor-role", "review-scope"],
    entitlement: ["institution-or-program-license", "assigned-program-access"],
    authority: ["human-review-authority-as-assigned", "model-cannot-finalize-human-review-requirement"],
    dataProjection: ["assigned-learner-progress", "submitted-evidence", "rubric", "attendance", "program-reporting-fields"],
    minimumNecessary: ["only-assigned-program-participant-data", "synthetic-clinical-simulation-data-by-default"],
    actions: ["launch-session", "review-submission", "score-rubric", "give-feedback", "record-attendance", "authorize-completion-when-policy-allows"],
    zumi: {
      readScope: ["assigned-program-data", "rubric", "learner-submission", "session-notes"],
      inferScope: ["common-learning-gap", "items-needing-human-review", "session-risk"],
      recommend: ["feedback-focus", "session-adjustment", "review-priority"],
      prepareDraft: ["feedback-draft", "session-summary", "program-report-draft"],
      executeViaAuthorizedTools: ["queue-review", "save-draft-feedback", "prepare-report-export"],
      forbidden: [...COMMON_ZUMI_FORBIDDEN, "finalize-human-required-rubric-score-without-authorized-review", "create-professional-credential", "expose-learner-data-outside-program-scope"],
    },
    aiProcessing: {
      allowedDataClasses: ["education-record", "synthetic-simulation-data", "assessment-submission", "program-reporting-data"],
      prohibitedDataClasses: ["real-phi-by-default", "unassigned-learner-data", "authentication-secrets"],
      purpose: ["instructional-assistance", "review-prioritization", "program-reporting"],
      processingBasis: ["institution-or-program-agreement", "ai-service-processing-notice", "authorized-education-purpose"],
      agreementKey: "global_terms_ai_service_processing",
      phiGate: "forbidden",
      modelTraining: "not-permitted-by-default",
    },
    audit: [...COMMON_AUDIT, "rubric-and-completion-authority", "report-export"],
    provenance: [...COMMON_PROVENANCE],
    promotionPolicy: ["promote-only-program-relevant-tools", "placement-promotion-respects-program-and-participant-consent"],
    commercialTargetingBoundary: ["program-usage-may-support-contractual-product-improvement-analytics", "no-clinical-or-phi-context-for-commercial-targeting", "learner-data-not-an-ad-audience"],
    states: { ...COMMON_STATES },
    mobile: COMMON_MOBILE,
    accessibility: COMMON_ACCESSIBILITY,
  }),

  contract({
    id: "patient-home",
    screenFamily: "patient-facing home, appointments, forms, messages and released information",
    routePatterns: ["/patient*", "/portal*", "/my-care*"],
    audiences: ["patient", "authorized-proxy-or-caregiver"],
    contextRequirements: ["authenticated-identity", "patient-or-proxy-relationship", "consent-and-access-policy", "active-patient-context"],
    visibleByDefault: ["next-appointment", "required-forms", "authorized-messages", "released-results-or-instructions", "next-patient-action"],
    intentionallyHidden: ["clinic-internal-operations", "unreleased-results", "internal-staff-notes", "other-patients", "billing-operations-beyond-patient-responsibility"],
    discoverable: ["appointments", "forms", "messages", "authorized-documents", "payments", "provider-or-referral-navigation-when-permitted"],
    promotable: ["complete-form", "schedule-or-confirm", "pay-patient-responsibility", "authorized-care-navigation"],
    eligibility: ["verified-patient-or-proxy-relationship", "release-policy", "service-availability"],
    entitlement: ["patient-access-under-applicable-clinic-service", "separate-paid-service-only-when-explicit"],
    authority: ["self-or-valid-proxy-scope", "proxy-scope-can-differ-by-record-or-action"],
    dataProjection: ["patient-facing-released-data", "appointments", "forms", "messages", "patient-financial-responsibility"],
    minimumNecessary: ["only-current-patient-or-valid-proxy-scope", "internal-clinic-data-excluded", "release-status-enforced-before-ai-or-ui"],
    actions: ["view-released-information", "complete-form", "message", "schedule-or-confirm", "make-authorized-payment"],
    zumi: {
      readScope: ["patient-visible-data-projection", "current-patient-question", "authorized-instructions-and-released-results"],
      inferScope: ["navigation-intent", "missing-patient-action", "plain-language-information-need"],
      recommend: ["next-authorized-patient-action", "where-to-find-released-information", "contact-clinic-when-human-review-is-needed"],
      prepareDraft: ["message-to-care-team", "plain-language-summary-of-released-information-with-safety-qualification"],
      executeViaAuthorizedTools: ["patient-confirmed-scheduling-or-message-action", "patient-confirmed-form-or-payment-workflow"],
      forbidden: [...COMMON_ZUMI_FORBIDDEN, "diagnose-or-prescribe", "reveal-unreleased-or-internal-clinical-data", "act-as-emergency-service"],
    },
    aiProcessing: {
      allowedDataClasses: ["patient-visible-phi-within-approved-ai-rail", "appointments", "released-instructions", "patient-messages"],
      prohibitedDataClasses: ["unreleased-clinical-data", "other-patient-data", "authentication-secrets"],
      purpose: ["patient-navigation", "authorized-care-communication-assistance", "plain-language-support"],
      processingBasis: ["applicable-patient-privacy-and-service-agreement", "approved-hipaa-gated-workflow", "ai-service-processing-notice"],
      agreementKey: "global_terms_ai_service_processing",
      phiGate: "hipaa-gated",
      modelTraining: "not-permitted-by-default",
    },
    audit: [...COMMON_AUDIT, "proxy-context", "released-data-status", "patient-facing-ai-disclosure-when-required"],
    provenance: [...COMMON_PROVENANCE],
    promotionPolicy: ["promote-care-actions-not-unrelated-clinic-products", "commercial-promotion-must-not-use-sensitive-clinical-inference"],
    commercialTargetingBoundary: ["no-clinical-or-phi-context-for-commercial-targeting", "care-navigation-is-not-ad-targeting", "patient-data-not-sold-to-create-ad-audiences"],
    states: { ...COMMON_STATES },
    mobile: COMMON_MOBILE,
    accessibility: COMMON_ACCESSIBILITY,
  }),

  contract({
    id: "provider-home",
    screenFamily: "provider operational briefing and assigned clinical work",
    routePatterns: ["/home*", "/today*", "/provider*"],
    audiences: ["provider"],
    contextRequirements: ["authenticated-provider", "active-organization", "active-location-when-required", "provider-authority", "assigned-work"],
    visibleByDefault: ["highest-priority-clinical-work", "assigned-patient-or-result-attention", "documentation-blockers", "next-provider-action", "ask-klinikos"],
    intentionallyHidden: ["unrelated-patients", "organization-financial-admin-unless-entitled-and-authorized", "enterprise-config", "irrelevant-grid-or-edu-modules"],
    discoverable: ["assigned-patients", "current-visits", "results", "clinical-tasks", "relevant-care-resources"],
    promotable: ["complete-documentation", "review-result", "enter-current-visit", "relevant-grid-or-learning-capability-only-when-context-supports-it"],
    eligibility: ["provider-relationship", "credential-and-privilege-policy", "patient-or-work-assignment"],
    entitlement: ["organization-clinical-product-entitlement"],
    authority: ["organization-location-role-purpose-and-patient-scope", "signing-requires-provider-sign-authority"],
    dataProjection: ["assigned-work-summary", "minimum-clinical-context", "result-status", "documentation-state"],
    minimumNecessary: ["home-shows-only-data-needed-to-identify-and-enter-authorized-work", "full-chart-details-remain-inside-authorized-patient-context"],
    actions: ["open-current-visit", "review-result", "complete-assigned-task", "open-documentation", "ask-klinikos"],
    zumi: {
      readScope: ["authorized-assigned-work", "minimum-clinical-context", "documentation-state", "released-results-within-provider-scope"],
      inferScope: ["priority", "unfinished-work", "documented-change-needing-review"],
      recommend: ["next-provider-action", "items-requiring-human-review", "documentation-follow-up"],
      prepareDraft: ["work-summary", "documentation-draft-from-evidence", "patient-message-draft"],
      executeViaAuthorizedTools: ["open-context", "save-draft", "create-authorized-task", "send-only-after-required-human-confirmation"],
      forbidden: [...COMMON_ZUMI_FORBIDDEN, "invent-clinical-finding", "sign-clinical-document", "autonomously-order-diagnose-or-prescribe"],
    },
    aiProcessing: {
      allowedDataClasses: ["minimum-necessary-phi-within-approved-ai-rail", "clinical-work-state", "documentation-evidence"],
      prohibitedDataClasses: ["unrelated-patient-data", "other-organization-clinical-data", "authentication-secrets"],
      purpose: ["clinical-workflow-assistance", "documentation-support", "priority-surfacing"],
      processingBasis: ["organization-service-agreement", "baa-when-required", "approved-hipaa-ai-rail", "authorized-user-purpose"],
      agreementKey: "global_terms_ai_service_processing",
      phiGate: "minimum-necessary",
      modelTraining: "not-permitted-by-default",
    },
    audit: [...COMMON_AUDIT, "patient-context", "clinical-source-evidence", "provider-review-or-signature"],
    provenance: [...COMMON_PROVENANCE],
    promotionPolicy: ["clinical-work-first", "promote-adjacent-capability-only-when-it-removes-current-friction"],
    commercialTargetingBoundary: ["no-clinical-or-phi-context-for-commercial-targeting", "workflow-analytics-may-support-contracted-product-improvement-in-deidentified-or-permitted-form", "patient-condition-cannot-drive-upsell"],
    states: { ...COMMON_STATES },
    mobile: COMMON_MOBILE,
    accessibility: COMMON_ACCESSIBILITY,
  }),

  contract({
    id: "current-visit",
    screenFamily: "continuous provider encounter including longitudinal change, documentation, orders/results and close",
    routePatterns: ["/patients/*/current-visit*", "/encounters/*", "/care/current-visit*"],
    audiences: ["provider", "authorized-clinical-staff-with-narrowed-scope"],
    contextRequirements: ["patient-context", "encounter-context", "organization", "location", "role", "purpose-of-use", "patient-relationship", "authority"],
    visibleByDefault: ["patient-snapshot", "what-changed", "staff-handoff", "today", "clinical", "assessment-and-plan", "orders-and-results", "documentation-and-coding", "close-visit-state"],
    intentionallyHidden: ["unrelated-patient-records", "nonessential-historical-detail-until-requested", "organization-admin", "Grid", "EDU", "commercial-promotions-during-clinical-decision-making"],
    discoverable: ["history-on-demand", "body-map-history", "specialty-context", "authorized-labs-imaging-referrals", "telemedicine-inside-encounter"],
    promotable: ["missing-documentation-resolution", "authorized-follow-up", "relevant-integrated-workflow-not-commercial-advertising"],
    eligibility: ["authorized-clinical-relationship", "active-or-reviewable-encounter", "credential-and-privilege-policy"],
    entitlement: ["organization-care-entitlement"],
    authority: ["role-and-patient-specific", "provider-signature-or-order-authority-remains-explicit", "staff-scope-narrows-authorship-and-actions"],
    dataProjection: ["current-patient-minimum-necessary-chart", "initial-previous-today-change-model", "encounter-evidence", "authorized-results", "coding-readiness-evidence"],
    minimumNecessary: ["patient-and-encounter-scoped", "progressive-disclosure-of-history", "special-category-data-only-when-purpose-and-policy-permit"],
    actions: ["document", "review", "compare-change", "prepare-order", "review-result", "prepare-code", "sign-when-authorized", "close-when-completion-rules-satisfied"],
    zumi: {
      readScope: ["authorized-current-patient-evidence", "encounter-state", "longitudinal-evidence", "authorized-results-and-consults"],
      inferScope: ["documented-change", "missing-documentation", "candidate-coding-support", "items-needing-human-review"],
      recommend: ["evidence-grounded-next-clinical-workflow-action", "documentation-completion", "coding-candidate-for-review"],
      prepareDraft: ["structured-note-draft", "patient-instruction-draft", "referral-or-order-draft", "coding-support-draft"],
      executeViaAuthorizedTools: ["save-draft", "create-authorized-task", "stage-order-or-referral-for-authorized-review", "open-telemedicine-context"],
      forbidden: [...COMMON_ZUMI_FORBIDDEN, "invent-clinical-finding", "invent-longitudinal-change", "change-laterality-without-evidence", "sign-note", "autonomously-order-diagnose-prescribe-or-finalize-code"],
    },
    aiProcessing: {
      allowedDataClasses: ["minimum-necessary-phi-within-approved-ai-rail", "encounter-evidence", "longitudinal-clinical-evidence", "authorized-results-and-consults"],
      prohibitedDataClasses: ["unrelated-patient-data", "other-tenant-clinical-data", "authentication-secrets", "data-outside-authorized-purpose"],
      purpose: ["clinical-documentation-assistance", "longitudinal-context", "workflow-assistance", "coding-readiness-support"],
      processingBasis: ["organization-service-agreement", "baa-when-required", "approved-hipaa-ai-rail", "authorized-treatment-or-operational-purpose"],
      agreementKey: "global_terms_ai_service_processing",
      phiGate: "minimum-necessary",
      modelTraining: "not-permitted-by-default",
    },
    audit: [...COMMON_AUDIT, "clinical-authorship", "source-evidence", "draft-vs-signed-state", "order-result-and-close-state"],
    provenance: [...COMMON_PROVENANCE],
    promotionPolicy: ["no-unrelated-commercial-upsell-inside-active-clinical-decision-surface", "workflow-capability-may-be-surfaced-only-to-complete-current-care-work"],
    commercialTargetingBoundary: ["no-clinical-or-phi-context-for-commercial-targeting", "clinical-condition-never-becomes-upsell-signal", "product-improvement-analytics-require-permitted-governed-data-path"],
    states: { ...COMMON_STATES },
    mobile: "mobile-preserves-the-continuous-encounter-and-primary-action-with-progressive-disclosure; never-compress-the-full-chart-into-a-dashboard",
    accessibility: COMMON_ACCESSIBILITY,
  }),

  contract({
    id: "clinical-handoff",
    screenFamily: "MA LPN RN provider and care-team preparation and handoff",
    routePatterns: ["/today/handoff*", "/patients/*/handoff*", "/care/handoff*"],
    audiences: ["medical-assistant", "licensed-practical-nurse", "registered-nurse", "provider", "authorized-care-team"],
    contextRequirements: ["patient-context", "assigned-work", "role", "scope", "organization", "location", "purpose"],
    visibleByDefault: ["assigned-patient", "role-specific-preparation", "what-is-complete", "what-is-missing", "handoff-owner", "next-action"],
    intentionallyHidden: ["functions-outside-role-scope", "unrelated-patients", "billing-admin", "enterprise-admin", "commercial-promotions"],
    discoverable: ["role-permitted-intake", "vitals", "forms", "documents", "care-coordination", "escalation"],
    promotable: ["complete-missing-preparation", "escalate-to-correct-role", "enter-current-visit-when-authorized"],
    eligibility: ["assigned-or-authorized-care-team-relationship", "role-scope", "patient-context"],
    entitlement: ["organization-care-entitlement"],
    authority: ["action-level-scope-by-role", "handoff-attribution-preserved", "clinical-signature-not-inherited-through-handoff"],
    dataProjection: ["role-specific-patient-data", "task-state", "handoff-evidence"],
    minimumNecessary: ["only-data-needed-for-assigned-preparation-or-coordination", "sensitive-clinical-sections-hidden-unless-role-and-purpose-require-them"],
    actions: ["record-role-permitted-data", "complete-task", "handoff", "escalate", "open-authorized-encounter"],
    zumi: {
      readScope: ["role-permitted-patient-context", "assigned-tasks", "handoff-state"],
      inferScope: ["missing-preparation", "handoff-blocker", "escalation-need"],
      recommend: ["next-role-permitted-action", "handoff-recipient", "missing-item"],
      prepareDraft: ["handoff-summary", "task-note", "patient-message-draft-within-role-scope"],
      executeViaAuthorizedTools: ["save-draft", "create-task", "route-handoff", "escalate"],
      forbidden: [...COMMON_ZUMI_FORBIDDEN, "expand-staff-scope-of-practice", "invent-clinical-finding", "attribute-one-role-work-to-another"],
    },
    aiProcessing: {
      allowedDataClasses: ["minimum-necessary-phi-for-assigned-handoff", "task-state", "intake-evidence"],
      prohibitedDataClasses: ["unrelated-patient-data", "out-of-scope-clinical-data", "authentication-secrets"],
      purpose: ["clinical-handoff-assistance", "task-completion", "care-coordination"],
      processingBasis: ["organization-service-agreement", "baa-when-required", "approved-hipaa-ai-rail", "authorized-role-purpose"],
      agreementKey: "global_terms_ai_service_processing",
      phiGate: "minimum-necessary",
      modelTraining: "not-permitted-by-default",
    },
    audit: [...COMMON_AUDIT, "role-attribution", "handoff-source-and-destination"],
    provenance: [...COMMON_PROVENANCE],
    promotionPolicy: ["promote-only-work-required-for-current-handoff", "no-cross-role-feature-upsell-during-patient-care"],
    commercialTargetingBoundary: ["no-clinical-or-phi-context-for-commercial-targeting", "staff-workflow-analytics-may-support-contracted-operational-improvement-only-through-governed-path"],
    states: { ...COMMON_STATES },
    mobile: COMMON_MOBILE,
    accessibility: COMMON_ACCESSIBILITY,
  }),

  contract({
    id: "biller-money-readiness",
    screenFamily: "billing readiness, claims, financial exceptions and revenue work",
    routePatterns: ["/money*", "/billing*", "/claims*", "/readiness*", "/revenue*"],
    audiences: ["biller", "authorized-revenue-user", "clinic-owner-with-financial-authority"],
    contextRequirements: ["organization", "financial-role", "entitlement", "claim-or-work-item", "purpose"],
    visibleByDefault: ["ready-vs-needs-attention", "documentation-blocker", "claim-state", "payer-or-patient-obligation-state", "next-financial-action"],
    intentionallyHidden: ["full-clinical-chart-unless-required", "unrelated-clinical-narrative", "other-organization-finances", "provider-authoring-controls"],
    discoverable: ["documentation-evidence-needed-for-readiness", "claim-history", "payment-evidence", "authorized-payer-or-patient-financial-context"],
    promotable: ["resolve-documentation-gap", "submit-when-ready", "reconcile-payment", "revenue-workflow-automation-when-pattern-is-established"],
    eligibility: ["financial-work-assignment", "organization-scope", "payer-or-transaction-policy"],
    entitlement: ["organization-money-or-billing-entitlement"],
    authority: ["financial-actions-by-role", "clinical-authorship-and-signature-remain-with-qualified-clinical-authority"],
    dataProjection: ["claim-and-financial-state", "minimum-clinical-evidence-for-billing-readiness", "payment-evidence", "exceptions"],
    minimumNecessary: ["clinical-data-limited-to-what-is-needed-for-billing-purpose", "no-unnecessary-sensitive-clinical-narrative"],
    actions: ["review-readiness", "request-missing-documentation", "prepare-claim", "submit-when-authorized", "post-or-reconcile-evidence", "work-exception"],
    zumi: {
      readScope: ["authorized-financial-state", "minimum-documentation-evidence", "claim-history", "payment-evidence"],
      inferScope: ["readiness-gap", "exception-category", "likely-next-financial-work-step"],
      recommend: ["missing-evidence-resolution", "claim-work-priority", "reconciliation-next-step"],
      prepareDraft: ["documentation-request", "appeal-or-follow-up-draft", "financial-work-summary"],
      executeViaAuthorizedTools: ["create-task", "stage-claim-action", "record-confirmed-reconciliation-work"],
      forbidden: [...COMMON_ZUMI_FORBIDDEN, "manufacture-documentation-for-higher-code", "finalize-provider-clinical-authorship", "mark-unverified-payment-as-paid"],
    },
    aiProcessing: {
      allowedDataClasses: ["minimum-necessary-phi-for-billing", "claim-data", "financial-obligation-and-payment-evidence", "documentation-readiness"],
      prohibitedDataClasses: ["unrelated-clinical-data", "other-tenant-financial-data", "payment-secrets"],
      purpose: ["billing-readiness", "financial-exception-assistance", "revenue-workflow-support"],
      processingBasis: ["organization-service-agreement", "baa-when-required", "approved-hipaa-ai-rail", "payment-or-healthcare-operations-purpose-as-applicable"],
      agreementKey: "global_terms_ai_service_processing",
      phiGate: "minimum-necessary",
      modelTraining: "not-permitted-by-default",
    },
    audit: [...COMMON_AUDIT, "claim-state", "payment-evidence", "financial-obligation-vs-settlement"],
    provenance: [...COMMON_PROVENANCE],
    promotionPolicy: ["promote-revenue-capability-from-financial-workflow-friction-not-patient-condition", "keep-clinical-and-commercial-context-separated"],
    commercialTargetingBoundary: ["no-clinical-or-phi-context-for-commercial-targeting", "organization-level-deidentified-operational-friction-may-support-contextual-product-education-under-contract", "patient-debt-not-an-ad-target"],
    states: { ...COMMON_STATES },
    mobile: COMMON_MOBILE,
    accessibility: COMMON_ACCESSIBILITY,
  }),

  contract({
    id: "clinic-owner-operations",
    screenFamily: "owner operating picture across work, team, money, capacity and selected care operations",
    routePatterns: ["/clinic*", "/operations*", "/owner*", "/dashboard*"],
    audiences: ["clinic-owner", "authorized-practice-admin", "executive-operator"],
    contextRequirements: ["verified-organization", "owner-or-admin-authority", "active-location-or-enterprise-scope", "entitlements"],
    visibleByDefault: ["one-operating-picture", "highest-priority-operational-work", "money-and-capacity-attention", "team-exceptions", "ask-klinikos"],
    intentionallyHidden: ["unnecessary-patient-clinical-detail", "raw-security-internals", "systems-not-relevant-to-current-business-state", "other-organizations"],
    discoverable: ["team", "money", "grid", "care-operations", "integrations", "analytics", "workflow-opportunities"],
    promotable: ["solve-observed-workflow-friction", "connect-grid", "activate-revenue-workflow", "add-location-or-team-capability-when-relevant"],
    eligibility: ["organization-authority", "location-or-enterprise-scope", "capability-specific-policy"],
    entitlement: ["organization-plan", "implementation-or-enterprise-contract", "free-grid-organization-capabilities-where-applicable"],
    authority: ["owner-or-delegated-admin-authority", "clinical-content-access-remains-separately-governed", "financial-contract-actions-may-require-specific-authority"],
    dataProjection: ["organization-level-operational-state", "aggregated-care-operations", "financial-state", "capacity", "team-work"],
    minimumNecessary: ["prefer-aggregated-operational-signals-over-patient-detail", "drill-into-clinical-data-only-with-separate-authority-and-purpose"],
    actions: ["review-priority", "assign-or-resolve-operational-work", "manage-team-within-authority", "enter-grid", "open-money", "configure-entitled-workflow"],
    zumi: {
      readScope: ["authorized-organization-operational-data", "aggregated-care-state", "money", "team", "grid", "workflow-events"],
      inferScope: ["operational-friction", "capacity-opportunity", "unfinished-work", "revenue-opportunity-with-evidence"],
      recommend: ["next-owner-action", "workflow-improvement", "capacity-or-grid-action", "product-capability-only-when-relevant"],
      prepareDraft: ["operating-summary", "team-message", "implementation-plan-draft", "customer-or-patient-communication-draft-with-appropriate-data-scope"],
      executeViaAuthorizedTools: ["create-or-assign-task", "stage-authorized-configuration-change", "prepare-grid-demand", "launch-authorized-workflow"],
      forbidden: [...COMMON_ZUMI_FORBIDDEN, "show-patient-detail-merely-because-user-is-owner", "invent-revenue-realization", "change-clinical-authority"],
    },
    aiProcessing: {
      allowedDataClasses: ["organization-operational-data", "aggregated-or-minimum-necessary-healthcare-operations-data", "financial-and-grid-operational-data"],
      prohibitedDataClasses: ["patient-level-phi-without-specific-authorized-purpose", "other-organization-data", "authentication-secrets"],
      purpose: ["clinic-operations", "workflow-orchestration", "business-performance-assistance"],
      processingBasis: ["organization-service-agreement", "ai-service-processing-notice", "baa-when-required-for-phi", "authorized-business-purpose"],
      agreementKey: "global_terms_ai_service_processing",
      phiGate: "minimum-necessary",
      modelTraining: "not-permitted-by-default",
    },
    audit: [...COMMON_AUDIT, "organization-and-location-scope", "configuration-change", "financial-impacting-action"],
    provenance: [...COMMON_PROVENANCE],
    promotionPolicy: ["promotion-by-demonstrated-relevance", "land-without-displacement", "do-not-show-every-capability-as-a-module-catalog"],
    commercialTargetingBoundary: ["organization-level-operational-signals-may-support-contextual-product-education-under-contract", "no-clinical-or-phi-context-for-commercial-targeting", "no-cross-customer-benchmarking-with-identifiable-data"],
    states: { ...COMMON_STATES },
    mobile: COMMON_MOBILE,
    accessibility: COMMON_ACCESSIBILITY,
  }),

  contract({
    id: "enterprise-admin",
    screenFamily: "multi-organization governance, hierarchy, policy, contracts, SSO and enterprise operations",
    routePatterns: ["/enterprise*", "/admin/enterprise*", "/organizations*"],
    audiences: ["enterprise-admin", "authorized-network-operator", "security-or-compliance-admin"],
    contextRequirements: ["enterprise-identity", "organization-hierarchy-authority", "admin-purpose", "policy-scope", "entitlement"],
    visibleByDefault: ["organization-hierarchy", "policy-and-access-exceptions", "contract-and-entitlement-state", "integration-and-reliability-attention", "enterprise-next-action"],
    intentionallyHidden: ["patient-level-clinical-data-by-default", "unrelated-tenant-content", "individual-private-data-beyond-admin-purpose", "secret-values"],
    discoverable: ["organizations", "locations", "memberships", "policy", "SSO", "integrations", "audit", "reliability", "entitlements"],
    promotable: ["enterprise-control-needed-for-observed-governance-problem", "integration-or-reliability-capability", "additional-entitlement-with-business-relevance"],
    eligibility: ["enterprise-contract-and-admin-assignment", "policy-and-jurisdiction"],
    entitlement: ["enterprise-agreement-and-feature-entitlements"],
    authority: ["hierarchy-scoped-admin-authority", "security-and-financial-authority-separated", "clinical-access-not-implied-by-enterprise-admin"],
    dataProjection: ["organization-metadata", "access-policy", "entitlement", "audit-summary", "reliability-and-integration-state"],
    minimumNecessary: ["aggregate-and-metadata-first", "patient-level-data-excluded-unless-separate-authorized-investigation-or-purpose"],
    actions: ["manage-authorized-hierarchy", "configure-policy", "review-audit", "manage-entitlement", "configure-SSO-or-integration", "open-incident-work"],
    zumi: {
      readScope: ["authorized-enterprise-metadata", "policy", "audit-summary", "reliability", "entitlements", "integration-state"],
      inferScope: ["governance-gap", "configuration-risk", "reliability-priority", "entitlement-opportunity"],
      recommend: ["policy-or-configuration-review", "incident-or-integration-next-step", "enterprise-capability-when-relevant"],
      prepareDraft: ["policy-change-summary", "incident-summary", "enterprise-report", "implementation-plan"],
      executeViaAuthorizedTools: ["stage-configuration", "create-change-request", "create-incident-task", "prepare-entitlement-change-for-authorized-confirmation"],
      forbidden: [...COMMON_ZUMI_FORBIDDEN, "grant-itself-admin-rights", "expose-secret-values", "use-enterprise-admin-role-as-clinical-access"],
    },
    aiProcessing: {
      allowedDataClasses: ["enterprise-metadata", "policy", "audit-summary", "reliability", "integration-and-entitlement-metadata"],
      prohibitedDataClasses: ["patient-level-phi-by-default", "secret-values", "other-tenant-private-data"],
      purpose: ["enterprise-governance", "operations", "reliability-and-integration-assistance"],
      processingBasis: ["enterprise-service-agreement", "ai-service-processing-notice", "authorized-admin-purpose"],
      agreementKey: "global_terms_ai_service_processing",
      phiGate: "forbidden",
      modelTraining: "not-permitted-by-default",
    },
    audit: [...COMMON_AUDIT, "admin-change-request", "policy-and-entitlement-change", "security-sensitive-access"],
    provenance: [...COMMON_PROVENANCE],
    promotionPolicy: ["promote-only-enterprise-capability-tied-to-governance-or-operational-need", "never-use-clinical-content-as-upsell-context"],
    commercialTargetingBoundary: ["enterprise-usage-metadata-may-support-contractual-account-management", "no-clinical-or-phi-context-for-commercial-targeting", "no-identifiable-cross-customer-benchmark-sale"],
    states: { ...COMMON_STATES },
    mobile: COMMON_MOBILE,
    accessibility: COMMON_ACCESSIBILITY,
  }),

  contract({
    id: "organization-claim-verification",
    screenFamily: "organization representation claim, evidence, verification and authority establishment",
    routePatterns: ["/claim/organization*", "/verify/organization*", "/organization/claim*"],
    audiences: ["prospective-owner", "organization-representative", "admin-invitee"],
    contextRequirements: ["authenticated-identity", "organization-claim", "claimed-capacity", "verification-policy"],
    visibleByDefault: ["claim-state", "required-evidence", "why-evidence-is-needed", "verification-progress", "next-action"],
    intentionallyHidden: ["organization-private-workspaces-before-authority", "other-claimants-private-evidence", "clinical-data", "financial-admin-until-authorized"],
    discoverable: ["supported-evidence-types", "verification-help", "authorized-delegation-path"],
    promotable: ["submit-required-proof", "accept-invitation", "request-authorized-review", "continue-to-organization-experience-after-verification"],
    eligibility: ["claimable-organization", "identity-assurance", "verification-method-policy"],
    entitlement: ["claim-process-access-does-not-equal-product-entitlement", "post-verification-entitlements-resolved-separately"],
    authority: ["self-claim-is-not-authority", "verification-evidence-and-policy-establish-specific-representation-state", "binding-authority-may-require-separate-proof"],
    dataProjection: ["claim", "evidence-status", "verification-decision", "organization-public-or-claim-relevant-metadata"],
    minimumNecessary: ["request-only-evidence-needed-for-specific-authority", "protect-identity-and-business-documents"],
    actions: ["submit-evidence", "review-status", "respond-to-verification-request", "withdraw-claim", "continue-after-authorized-decision"],
    zumi: {
      readScope: ["claim-metadata", "verification-requirements", "non-secret-evidence-status"],
      inferScope: ["which-approved-evidence-path-may-apply", "missing-step"],
      recommend: ["next-verification-step", "plain-language-evidence-guidance"],
      prepareDraft: ["explanation-of-claim-status", "support-request"],
      executeViaAuthorizedTools: ["route-evidence-to-deterministic-or-human-verification", "create-review-request"],
      forbidden: [...COMMON_ZUMI_FORBIDDEN, "approve-organization-authority-from-language-model-judgment-alone", "expose-private-evidence", "bind-organization"],
    },
    aiProcessing: {
      allowedDataClasses: ["claim-metadata", "verification-status", "redacted-or-approved-evidence-metadata"],
      prohibitedDataClasses: ["raw-high-risk-identity-document-unless-approved-tool-path", "authentication-secrets", "phi"],
      purpose: ["verification-navigation", "evidence-requirement-explanation"],
      processingBasis: ["global-or-organization-claim-terms", "ai-service-processing-notice", "user-requested-verification-assistance"],
      agreementKey: "global_terms_ai_service_processing",
      phiGate: "forbidden",
      modelTraining: "not-permitted-by-default",
    },
    audit: [...COMMON_AUDIT, "claim-submission", "evidence-receipt", "verification-decision-and-authority-scope"],
    provenance: [...COMMON_PROVENANCE],
    promotionPolicy: ["promotion-to-organization-products-only-after-or-alongside-truthful-claim-state", "never-represent-pending-claim-as-owned"],
    commercialTargetingBoundary: ["organization-claim-intent-may-support-contextual-setup-guidance", "no-clinical-or-phi-context-for-commercial-targeting", "verification-documents-not-commercial-targeting-data"],
    states: { ...COMMON_STATES },
    mobile: COMMON_MOBILE,
    accessibility: COMMON_ACCESSIBILITY,
  }),

  contract({
    id: "telemedicine-encounter",
    screenFamily: "telemedicine inside the same governed clinical encounter",
    routePatterns: ["/encounters/*/telemedicine*", "/care/telemedicine*", "/telemedicine/visit*"],
    audiences: ["provider", "patient", "authorized-clinical-support"],
    contextRequirements: ["appointment-or-encounter", "patient-identity", "provider-authority", "consent-and-readiness", "organization", "jurisdiction"],
    visibleByDefault: ["visit-readiness", "consent-state", "join-or-start-action", "current-encounter-context", "connection-status", "post-visit-next-action"],
    intentionallyHidden: ["separate-duplicate-chart", "unrelated-patient-records", "organization-admin", "commercial-promotions-during-visit"],
    discoverable: ["authorized-current-visit", "device-readiness", "consent", "visit-instructions"],
    promotable: ["complete-readiness", "join-visit", "return-to-current-visit", "complete-follow-up-after-visit"],
    eligibility: ["scheduled-or-authorized-visit", "provider-jurisdiction-and-privilege", "patient-consent", "telemedicine-policy"],
    entitlement: ["organization-care-or-telemedicine-entitlement"],
    authority: ["provider-clinical-authority", "patient-or-proxy-participation", "support-role-limited-to-assigned-assistance"],
    dataProjection: ["current-encounter-minimum-necessary-data", "readiness", "consent", "connection-state"],
    minimumNecessary: ["same-encounter-context-only", "video-or-audio-processing-limited-to-disclosed-approved-purpose", "no-background-cross-patient-context"],
    actions: ["complete-readiness", "join-or-start", "document-in-same-encounter", "end-session", "continue-orders-documentation-and-follow-up"],
    zumi: {
      readScope: ["authorized-current-encounter-context", "readiness", "consent", "approved-transcript-or-scribe-stream-when-enabled"],
      inferScope: ["visit-readiness-blocker", "documented-conversation-structure-when-scribe-is-enabled", "missing-follow-up-work"],
      recommend: ["readiness-resolution", "documentation-review", "post-visit-next-action"],
      prepareDraft: ["transcript-derived-note-draft", "patient-instruction-draft", "follow-up-draft"],
      executeViaAuthorizedTools: ["join-routing", "save-draft", "create-follow-up-task", "return-to-current-visit"],
      forbidden: [...COMMON_ZUMI_FORBIDDEN, "record-or-transcribe-without-required-notice-or-consent", "invent-clinical-finding", "sign-note-or-autonomously-order-diagnose-or-prescribe"],
    },
    aiProcessing: {
      allowedDataClasses: ["minimum-necessary-phi-in-approved-telemedicine-ai-rail", "consented-transcript-or-scribe-stream", "encounter-evidence"],
      prohibitedDataClasses: ["unconsented-audio-or-video-for-ai-processing", "unrelated-patient-data", "authentication-secrets"],
      purpose: ["telemedicine-delivery", "consented-documentation-assistance", "encounter-continuity"],
      processingBasis: ["organization-service-agreement", "baa-when-required", "telemedicine-consent-or-notice-as-required", "ai-service-processing-notice", "approved-hipaa-ai-rail"],
      agreementKey: "global_terms_ai_service_processing",
      phiGate: "hipaa-gated",
      modelTraining: "not-permitted-by-default",
    },
    audit: [...COMMON_AUDIT, "telemedicine-consent", "session-start-end", "scribe-or-transcription-enablement", "clinical-review"],
    provenance: [...COMMON_PROVENANCE],
    promotionPolicy: ["no-unrelated-commercial-promotion-during-live-care", "post-visit-capability-promotion-limited-to-current-care-workflow"],
    commercialTargetingBoundary: ["no-clinical-or-phi-context-for-commercial-targeting", "audio-video-transcript-never-commercial-targeting-data", "care-context-remains-care-context"],
    states: { ...COMMON_STATES },
    mobile: "mobile-telemedicine-prioritizes-readiness-join-media-controls-and-return-to-current-visit-without-duplicate-charting",
    accessibility: COMMON_ACCESSIBILITY,
  }),
] as const satisfies readonly ScreenExperienceContract[];

export type KlinikosScreenExperienceContract = (typeof KLINIKOS_SCREEN_EXPERIENCE_CONTRACTS)[number];

export const KLINIKOS_SCREEN_CONTRACT_RELEASE_GATE = {
  policy: "every-active-user-facing-route-must-resolve-to-an-approved-screen-experience-contract-before-production-release",
  requiredDeclarations: [
    "visible-by-default",
    "intentionally-hidden",
    "discoverable",
    "promotable",
    "eligibility",
    "entitlement",
    "authority",
    "minimum-necessary-data-projection",
    "zumi-read-infer-recommend-draft-execute-forbidden",
    "ai-data-classes-and-processing-basis",
    "phi-gate",
    "agreement-key",
    "audit-and-provenance",
    "commercial-targeting-boundary",
    "denied-blocked-loading-empty-error-states",
    "mobile-and-accessibility-contract",
  ],
  unclassifiedRoutePolicy: "block-production-release-until-classified",
  exceptionPolicy: "documented-security-privacy-product-and-legal-review-required",
} as const;
