project_id = "klinikos"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://klinikos.io", "https://www.klinikos.io"]

[studio]
enabled = true

[inbucket]
enabled = true
