import {
  Archive, ArrowRight, Check, ClipboardCheck, CloudUpload, Download, Eye,
  FileClock, FilePlus2, Files, Image as ImageIcon, LockKeyhole, Plus, ScanLine,
  Send, Signature, SlidersHorizontal,
} from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { imagingQueue } from "@/lib/clinic-data";
import { PageIntro, Person, Progress, SectionCard, StatCard, StatusBadge } from "@/components/clinic/workspace-kit";

export function ImagingWorkspace() {
  return <div className="space-y-6"><PageIntro title="Imaging, from order to approved release." description="Track studies, facilities, incoming reports, provider review, patient visibility, and the follow-up created from each result." action={<Button variant="primary"><Plus className="size-4" /> New imaging order</Button>} aside={<Button variant="secondary"><CloudUpload className="size-4" /> Upload report</Button>} />
    <div className="grid gap-4 sm:grid-cols-3"><StatCard accent="amber" detail="Provider action required" icon={<ScanLine className="size-4" />} label="Reports to review" value="2" /><StatCard accent="sky" detail="Across 4 facilities" icon={<ImageIcon className="size-4" />} label="Studies pending" value="6" /><StatCard accent="teal" detail="This week" icon={<Check className="size-4" />} label="Released" value="9" /></div>
    <SectionCard title="Imaging worklist" description="Facility names below are demo roadmap references, not live interfaces."><div className="overflow-x-auto"><table className="w-full min-w-[820px] text-left"><thead><tr className="border-b border-slate-100 text-[9px] font-extrabold uppercase tracking-[.14em] text-slate-400"><th className="px-5 py-3">Patient</th><th className="px-3 py-3">Study</th><th className="px-3 py-3">Facility</th><th className="px-3 py-3">Ordered</th><th className="px-3 py-3">Report</th><th className="px-5 py-3">Review</th></tr></thead><tbody>{imagingQueue.map((item) => <tr className="border-b border-slate-100 text-xs last:border-0" key={item.id}><td className="px-5 py-5"><Person initials={item.patient.split(" ").map((part) => part[0]).join("")} name={item.patient} /></td><td className="px-3 py-5 font-bold text-slate-800">{item.study}</td><td className="px-3 py-5 text-slate-500">{item.facility}</td><td className="px-3 py-5 text-slate-500">{item.ordered}</td><td className="px-3 py-5"><StatusBadge status={item.status} /></td><td className="px-5 py-5"><div className="flex items-center gap-2"><StatusBadge status={item.review} /><Button size="icon" variant="ghost" aria-label="Open imaging report"><ArrowRight className="size-4" /></Button></div></td></tr>)}</tbody></table></div></SectionCard>
    <div className="grid gap-6 lg:grid-cols-2"><SectionCard title="Facility connectivity roadmap"><div className="space-y-4 p-5">{[["Lenox Hill Radiology", 25, "Discovery"], ["RadNet", 18, "Future"], ["Hospital imaging", 10, "Future"]].map(([label, value, status]) => <div key={String(label)}><div className="mb-2 flex items-center justify-between"><p className="text-xs font-bold text-slate-800">{label}</p><Badge tone="slate">{status}</Badge></div><Progress value={Number(value)} tone="sky" /></div>)}</div></SectionCard><SectionCard title="Release checklist"><div className="grid gap-3 p-5 sm:grid-cols-2">{["Report attached", "Ordering provider matched", "Provider reviewed", "Patient release approved"].map((label, index) => <div className="flex items-center gap-3 rounded-xl bg-slate-50 p-3" key={label}><span className={`grid size-7 place-items-center rounded-lg ${index < 2 ? "bg-teal-100 text-teal-700" : "bg-white text-slate-400"}`}>{index < 2 ? <Check className="size-3.5" /> : <LockKeyhole className="size-3.5" />}</span><p className="text-[10px] font-bold text-slate-700">{label}</p></div>)}</div></SectionCard></div>
  </div>;
}

export function DocumentsWorkspace() {
  const docs = [
    { name: "Insurance card - front and back", patient: "Maya Thompson", category: "Insurance card", date: "Jul 13, 2026", visibility: "Internal", review: "Verified" },
    { name: "Telemedicine consent", patient: "Darius Coleman", category: "Consent", date: "Jul 13, 2026", visibility: "Patient visible", review: "Signed" },
    { name: "MRI lumbar spine report", patient: "Anthony Nguyen", category: "Imaging report", date: "Jul 12, 2026", visibility: "Held", review: "Needs review" },
    { name: "No-fault assignment of benefits", patient: "Jordan Kim", category: "No-fault", date: "Jul 10, 2026", visibility: "Internal", review: "Complete" },
  ];
  return <div className="space-y-6"><PageIntro title="The right document, with the right visibility." description="Upload, categorize, review, lock, release, and export records with patient visibility and audit state visible before every action." action={<Button variant="primary"><CloudUpload className="size-4" /> Upload document</Button>} />
    <div className="grid gap-4 sm:grid-cols-4"><StatCard accent="sky" detail="Across all categories" icon={<Files className="size-4" />} label="Documents" value="1,284" /><StatCard accent="amber" detail="Provider or staff action" icon={<FileClock className="size-4" />} label="Needs review" value="6" /><StatCard accent="teal" detail="Approved for portal" icon={<Eye className="size-4" />} label="Patient visible" value="418" /><StatCard accent="slate" detail="Retention policy applied" icon={<Archive className="size-4" />} label="Locked records" value="796" /></div>
    <SectionCard title="Document library" action={<Button size="sm" variant="secondary"><SlidersHorizontal className="size-3.5" /> Filter</Button>}><div className="divide-y divide-slate-100">{docs.map((doc) => <div className="grid gap-4 p-5 md:grid-cols-[1.2fr_.7fr_.55fr_.45fr_auto] md:items-center" key={doc.name}><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-sky-50 text-sky-700"><FileTextIcon /></span><div><p className="text-xs font-extrabold text-slate-900">{doc.name}</p><p className="mt-1 text-[10px] text-slate-400">{doc.patient} · {doc.date}</p></div></div><div><p className="text-[9px] font-bold text-slate-400">CATEGORY</p><p className="mt-1 text-xs font-bold text-slate-700">{doc.category}</p></div><StatusBadge status={doc.visibility} /><StatusBadge status={doc.review} /><div className="flex gap-1"><Button size="icon" variant="ghost" aria-label="Preview"><Eye className="size-4" /></Button><Button size="icon" variant="ghost" aria-label="Download"><Download className="size-4" /></Button></div></div>)}</div></SectionCard>
  </div>;
}

function FileTextIcon() { return <Files className="size-4" />; }

export function FormsWorkspace() {
  const forms = [
    { title: "New patient intake", use: "Primary care", fields: 32, status: "Active", completion: 88 },
    { title: "Telemedicine consent", use: "All virtual visits", fields: 9, status: "Active", completion: 96 },
    { title: "Chronic care follow-up", use: "Primary care", fields: 18, status: "Active", completion: 91 },
    { title: "No-fault intake", use: "Case management", fields: 41, status: "Draft", completion: 64 },
  ];
  return <div className="space-y-6"><PageIntro title="Intake that arrives chart-ready." description="Build conditional forms, collect signatures, route reviews, lock submissions, and attach the approved record directly to the patient chart." action={<Button variant="primary"><FilePlus2 className="size-4" /> New template</Button>} aside={<Button variant="secondary"><Send className="size-4" /> Send forms</Button>} />
    <section className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><SectionCard title="Form templates" description="Templates are scoped by organization, location, and appointment type."><div className="grid gap-3 p-4 sm:grid-cols-2">{forms.map((form) => <div className="rounded-2xl border border-slate-200 p-4" key={form.title}><div className="flex items-start gap-3"><span className="grid size-9 place-items-center rounded-xl bg-teal-50 text-teal-700"><ClipboardCheck className="size-4" /></span><div className="min-w-0 flex-1"><p className="text-xs font-extrabold text-slate-900">{form.title}</p><p className="mt-1 text-[10px] text-slate-400">{form.use} · {form.fields} fields</p></div><StatusBadge status={form.status} /></div><div className="mt-5 flex items-center justify-between text-[9px] font-bold text-slate-400"><span>COMPLETION RATE</span><span>{form.completion}%</span></div><div className="mt-2"><Progress value={form.completion} /></div></div>)}</div></SectionCard><div className="space-y-6"><Card className="bg-[#dff7f1] p-6"><Signature className="size-6 text-teal-700" /><p className="mt-5 text-xl font-extrabold tracking-[-.035em] text-slate-950">Signed and traceable.</p><p className="mt-3 text-xs leading-6 text-slate-600">Every submission keeps template version, timestamp, signer context, review state, lock state, and patient-chart attachment history.</p></Card><SectionCard title="Incomplete today"><div className="space-y-2 p-3">{[["Elena Rivera", "New patient intake", "72%"], ["Lena Morris", "Telemedicine consent", "Not started"], ["Jordan Kim", "No-fault intake", "44%"]].map(([patient, form, progress]) => <div className="rounded-xl border border-slate-100 p-3" key={patient}><div className="flex items-center justify-between"><div><p className="text-xs font-bold text-slate-900">{patient}</p><p className="mt-1 text-[10px] text-slate-400">{form}</p></div><Badge tone="amber">{progress}</Badge></div><Button className="mt-3 w-full" size="sm" variant="secondary"><Send className="size-3.5" /> Send reminder</Button></div>)}</div></SectionCard></div></section>
  </div>;
}
