import {
  ArrowRight, BadgeCheck, Banknote, Calculator,
  ChartNoAxesCombined, CheckCircle2, ClipboardList,
  FileWarning, HeartHandshake, Megaphone, Plus, ReceiptText,
  RefreshCw, SearchCheck, ShieldCheck, TrendingUp, TriangleAlert,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { PaymentConsole } from "@/components/clinic/payment-actions";
import { claims } from "@/lib/clinic-data";
import type { PaymentWorkspace } from "@/lib/repositories/payment-repository";
import { formatCurrency } from "@/lib/utils";
import { PageIntro, Person, Progress, SectionCard, StatCard, StatusBadge } from "@/components/clinic/workspace-kit";

export function BillingWorkspace({ paymentWorkspace }: { paymentWorkspace: PaymentWorkspace }) {
  return <div className="space-y-6"><PageIntro title="Revenue cycle with every handoff visible." description="Superbills, claim drafts, payer status, denials, remittance, patient balances, and owner-level cash insight share one work queue." action={<Button variant="primary"><Plus className="size-4" /> New claim draft</Button>} aside={<Button variant="secondary"><ReceiptText className="size-4" /> Create invoice</Button>} />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard accent="sky" detail="12 claims in motion" icon={<Banknote className="size-4" />} label="Submitted this week" value="$14,860" /><StatCard accent="amber" detail="5 claims need review" icon={<FileWarning className="size-4" />} label="At risk" value="$2,180" /><StatCard accent="rose" detail="3 active denials" icon={<TriangleAlert className="size-4" />} label="Denied" value="$1,044" /><StatCard accent="teal" detail="11.2 days average" icon={<TrendingUp className="size-4" />} label="Collected MTD" value="$38,420" /></div>
    <PaymentConsole workspace={paymentWorkspace} />
    <div className="grid gap-6 xl:grid-cols-[1.25fr_.75fr]">
      <SectionCard title="Claim worklist" description="Claims remain drafts until authorized billing review is complete.">
        <div className="overflow-x-auto"><table className="w-full min-w-[770px] text-left"><thead><tr className="border-b border-slate-100 text-[11px] font-extrabold uppercase tracking-[.14em] text-slate-400"><th className="px-5 py-3">Claim / patient</th><th className="px-3 py-3">Payer</th><th className="px-3 py-3">Service date</th><th className="px-3 py-3">Amount</th><th className="px-3 py-3">Issue</th><th className="px-5 py-3">Status</th></tr></thead><tbody>{claims.map((claim) => <tr className="border-b border-slate-100 text-xs last:border-0" key={claim.id}><td className="px-5 py-5"><p className="font-extrabold text-slate-900">{claim.id}</p><p className="mt-1 text-[12px] text-slate-400">{claim.patient}</p></td><td className="px-3 py-5 font-bold text-slate-700">{claim.payer}</td><td className="px-3 py-5 text-slate-500">{claim.serviceDate}</td><td className="px-3 py-5 font-extrabold text-slate-900">{formatCurrency(claim.amount)}</td><td className="px-3 py-5 text-[12px] text-rose-600">{claim.issue ?? "-"}</td><td className="px-5 py-5"><div className="flex items-center gap-2"><StatusBadge status={claim.status} /><Button size="icon" variant="ghost" aria-label="Open claim"><ArrowRight className="size-4" /></Button></div></td></tr>)}</tbody></table></div>
      </SectionCard>
      <div className="space-y-6"><Card className="bg-slate-950 p-6 text-white"><div className="flex items-center justify-between"><p className="text-[12px] font-extrabold uppercase tracking-[.18em] text-lime-300">Collections forecast</p><Calculator className="size-5 text-teal-300" /></div><p className="mt-6 text-4xl font-extrabold tracking-[-.06em]">$51.2k</p><p className="mt-2 text-xs text-slate-400">Expected in the next 30 days from current demo claims and patient balances.</p><div className="mt-6"><Progress tone="teal" value={74} /></div><div className="mt-3 flex justify-between text-[11px] font-bold text-slate-400"><span>74% clean-claim confidence</span><span>Demo estimate</span></div></Card><SectionCard title="Denial reasons"><div className="space-y-4 p-5">{[["Missing modifier", 42], ["Eligibility mismatch", 26], ["Timely filing", 18], ["Other", 14]].map(([label, value]) => <div key={String(label)}><div className="mb-2 flex justify-between text-[12px] font-bold"><span className="text-slate-600">{label}</span><span className="text-slate-400">{value}%</span></div><Progress tone={Number(value) > 30 ? "rose" : "amber"} value={Number(value)} /></div>)}</div></SectionCard></div>
    </div>
  </div>;
}

export function InsuranceWorkspace() {
  const verifications = [
    { patient: "Maya Thompson", payer: "Healthfirst", member: "HF-TEST-40218", copay: "$25", deductible: "$380 remaining", verified: "Today, 8:42 AM", status: "Verified" },
    { patient: "Elena Rivera", payer: "MetroPlus", member: "MP-TEST-33981", copay: "$15", deductible: "Unknown", verified: "Not verified", status: "Needs review" },
    { patient: "Darius Coleman", payer: "EmblemHealth", member: "EMB-TEST-90116", copay: "$30", deductible: "$0 remaining", verified: "Jul 12, 3:18 PM", status: "Verified" },
    { patient: "Anthony Nguyen", payer: "Aetna", member: "AET-TEST-77241", copay: "$35", deductible: "$910 remaining", verified: "Jun 28, 10:06 AM", status: "Reverify" },
  ];
  return <div className="space-y-6"><PageIntro title="Coverage facts, never coverage promises." description="Eligibility, benefits, copay, deductible, coinsurance, prior authorization, source, and staff verification history stay explicit." action={<Button variant="primary"><SearchCheck className="size-4" /> Verify eligibility</Button>} />
    <div className="grid gap-4 sm:grid-cols-4"><StatCard accent="teal" detail="For today's schedule" icon={<BadgeCheck className="size-4" />} label="Verified" value="15" /><StatCard accent="amber" detail="Before arrival" icon={<RefreshCw className="size-4" />} label="Needs reverification" value="3" /><StatCard accent="sky" detail="Tracking documents" icon={<ClipboardList className="size-4" />} label="Prior authorizations" value="6" /><StatCard accent="rose" detail="Staff follow-up required" icon={<FileWarning className="size-4" />} label="Coverage issues" value="2" /></div>
    <SectionCard title="Eligibility and benefits" description="Demo responses are manually entered. 270/271 connectivity is a future clearinghouse integration."><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left"><thead><tr className="border-b border-slate-100 text-[11px] font-extrabold uppercase tracking-[.14em] text-slate-400"><th className="px-5 py-3">Patient</th><th className="px-3 py-3">Payer / member</th><th className="px-3 py-3">Copay</th><th className="px-3 py-3">Deductible</th><th className="px-3 py-3">Last checked</th><th className="px-5 py-3">Status</th></tr></thead><tbody>{verifications.map((item) => <tr className="border-b border-slate-100 text-xs last:border-0" key={item.patient}><td className="px-5 py-5"><Person initials={item.patient.split(" ").map((part) => part[0]).join("")} name={item.patient} /></td><td className="px-3 py-5"><p className="font-bold text-slate-800">{item.payer}</p><p className="mt-1 text-[12px] text-slate-400">{item.member}</p></td><td className="px-3 py-5 font-extrabold text-slate-900">{item.copay}</td><td className="px-3 py-5 text-slate-600">{item.deductible}</td><td className="px-3 py-5 text-slate-500">{item.verified}</td><td className="px-5 py-5"><StatusBadge status={item.status} /></td></tr>)}</tbody></table></div></SectionCard>
    <Card className="border-sky-200 bg-sky-50 p-5"><div className="flex items-start gap-4"><span className="grid size-10 place-items-center rounded-xl bg-white text-sky-700 shadow-sm"><ShieldCheck className="size-5" /></span><div><p className="text-xs font-extrabold text-slate-900">Verification is not a guarantee of payment.</p><p className="mt-2 text-[11px] leading-5 text-slate-600">ClinicOS records source, date, response, and staff notes. Final payment depends on payer adjudication and benefit rules at the time of service.</p></div></div></Card>
  </div>;
}
