import Link from "next/link";
import {
  Activity, AlertOctagon, ArrowRight, BadgeCheck, Blocks, Bot, CalendarDays, Check, ChevronRight,
  CircleDollarSign, ClipboardCheck, Clock3, Cloud, FileCheck2, FileText, Fingerprint,
  FlaskConical, HeartPulse, LockKeyhole, MessageCircle, MessagesSquare,
  MonitorSmartphone, PhoneCall, Plus, Send, Settings2, ShieldAlert, ShieldCheck,
  Network, Sparkles, Stethoscope, UserRoundCheck, Webhook, Workflow,
} from "lucide-react";
import { AiWorkflowDemo } from "@/components/clinic/ai-workflow-demo";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { auditEvents } from "@/lib/clinic-data";
import { EscalationActions, TaskActions } from "@/components/clinic/care-coordination-actions";
import { NavigationDraftActions, NavigationReviewActions } from "@/components/clinic/patient-navigation-actions";
import { ProviderConsultationCreateAction, ProviderConsultationTransitionActions } from "@/components/clinic/provider-consultation-actions";
import { CredentialingWorkspace } from "@/components/clinic/credentialing-workspace";
import type { CareCoordinationWorkspace } from "@/lib/repositories/care-coordination-repository";
import type { PatientNavigationWorkspace } from "@/lib/repositories/patient-navigation-repository";
import type { ProviderConsultationWorkspace } from "@/lib/repositories/provider-consultation-repository";
import type { CredentialingWorkspace as CredentialingWorkspaceData } from "@/lib/repositories/credentialing-repository";
import { PageIntro, Person, SectionCard, StatCard, StatusBadge } from "@/components/clinic/workspace-kit";

export function MessagesWorkspace() {
  const threads = [
    { initials: "MT", name: "Maya Thompson", preview: "Does this lab result change my visit?", time: "9:38 AM", unread: 2, type: "Lab question", risk: "Needs Provider" },
    { initials: "DC", name: "Darius Coleman", preview: "Can I refill my atorvastatin?", time: "9:12 AM", unread: 1, type: "Refill", risk: "Needs Provider" },
    { initials: "ER", name: "Elena Rivera", preview: "I completed the forms in Spanish.", time: "8:48 AM", unread: 0, type: "Office", risk: "Needs Staff" },
    { initials: "DC", name: "Darius Coleman", preview: "Is my appointment still at 10:45?", time: "Yesterday", unread: 0, type: "Scheduling", risk: "Normal" },
  ];
  return <div className="space-y-6"><PageIntro title="One inbox, routed by responsibility." description="Patient, staff, provider, billing, lab, appointment, payment, and form messages remain threaded and attached to the patient record." action={<Button variant="primary"><Plus className="size-4" /> New message</Button>} />
    <Card className="min-h-[680px] overflow-hidden"><div className="grid min-h-[680px] lg:grid-cols-[300px_1fr_290px]">
      <aside className="border-b border-slate-200 bg-slate-50/60 lg:border-b-0 lg:border-r"><div className="border-b border-slate-200 p-4"><p className="text-xs font-extrabold text-slate-950">Conversations</p><div className="mt-3 rounded-xl border border-slate-200 bg-white px-3 py-2 text-[10px] text-slate-400">Search messages...</div></div><div className="p-2">{threads.map((thread, index) => <button className={`w-full rounded-xl p-3 text-left transition ${index === 0 ? "bg-white shadow-sm ring-1 ring-slate-200" : "hover:bg-white"}`} key={thread.name}><div className="flex items-start gap-3"><span className={`grid size-9 shrink-0 place-items-center rounded-xl text-[10px] font-extrabold ${index === 0 ? "bg-teal-100 text-teal-800" : "bg-slate-100 text-slate-600"}`}>{thread.initials}</span><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><p className="truncate text-xs font-extrabold text-slate-900">{thread.name}</p><span className="ml-auto text-[8px] text-slate-400">{thread.time}</span></div><p className="mt-1 truncate text-[10px] text-slate-500">{thread.preview}</p><div className="mt-2 flex items-center gap-1.5"><StatusBadge status={thread.risk} />{thread.unread > 0 && <span className="grid size-4 place-items-center rounded-full bg-sky-600 text-[8px] font-extrabold text-white">{thread.unread}</span>}</div></div></div></button>)}</div></aside>
      <section className="flex min-w-0 flex-col bg-white"><div className="flex items-center gap-3 border-b border-slate-200 p-4"><Person color="teal" detail="Patient portal · Active now" initials="MT" name="Maya Thompson" /><Badge className="ml-auto" tone="amber">Provider review</Badge></div><div className="flex-1 space-y-5 overflow-y-auto bg-[#f7faf9] p-5"><div className="max-w-[78%] rounded-[18px_18px_18px_5px] bg-white p-4 shadow-sm ring-1 ring-slate-100"><p className="text-xs leading-6 text-slate-700">Hi, I saw that my A1C result was marked high. Does this change what I should do before my visit today?</p><p className="mt-2 text-right text-[8px] text-slate-400">9:38 AM</p></div><div className="rounded-2xl border border-amber-200 bg-amber-50 p-4"><div className="flex items-start gap-3"><ShieldAlert className="mt-0.5 size-5 shrink-0 text-amber-700" /><div><p className="text-xs font-extrabold text-amber-950">Automated clinical reply blocked</p><p className="mt-2 text-[10px] leading-5 text-amber-800">This message asks about a lab result. It was routed to the provider queue, and the draft below cannot be sent without human review.</p></div></div></div><div className="ml-auto max-w-[78%] rounded-[18px_18px_5px_18px] bg-slate-950 p-4 text-white"><p className="text-xs leading-6">Thanks for reaching out. Your result has been sent to your provider for review. Please keep your scheduled visit, and the clinical team will discuss next steps with you.</p><div className="mt-3 flex items-center justify-between"><Badge className="bg-white/10 text-white ring-white/15">Staff approved</Badge><p className="text-[8px] text-slate-400">Draft only</p></div></div></div><div className="border-t border-slate-200 p-4"><div className="rounded-2xl border border-slate-200 bg-white p-3"><textarea className="min-h-16 w-full resize-none text-xs leading-5 outline-none" placeholder="Write a reply..." /><div className="mt-2 flex items-center gap-2"><Button size="sm" variant="secondary"><Sparkles className="size-3.5" /> Suggest office-safe reply</Button><Button className="ml-auto" disabled size="sm" variant="primary">Send after approval <Send className="size-3.5" /></Button></div></div></div></section>
      <aside className="border-t border-slate-200 bg-white p-5 lg:border-l lg:border-t-0"><p className="text-xs font-extrabold text-slate-950">Patient context</p><div className="mt-5 space-y-4">{[["MRN", "BFM-28419"], ["Provider", "Nadja R., NP"], ["Next visit", "Today, 10:30 AM"], ["Insurance", "Healthfirst"], ["Portal", "Active"]].map(([label, value]) => <div key={label}><p className="text-[8px] font-extrabold uppercase tracking-[.14em] text-slate-400">{label}</p><p className="mt-1 text-[11px] font-bold text-slate-700">{value}</p></div>)}</div><div className="mt-6 rounded-xl bg-rose-50 p-4"><p className="text-[9px] font-extrabold text-rose-700">CHART FLAGS</p><p className="mt-2 text-[10px] font-bold text-rose-900">Abnormal A1C · Penicillin allergy</p></div><Button className="mt-4 w-full" variant="secondary">Open full chart <ArrowRight className="size-4" /></Button></aside>
    </div></Card>
  </div>;
}

export function TasksWorkspace({ workspace }: { workspace: CareCoordinationWorkspace }) {
  const open = workspace.tasks.filter((task) => task.status !== "completed");
  const urgent = open.filter((task) => task.priority === "urgent" || task.riskLevel === "URGENT").length;
  const dueToday = open.filter((task) => task.dueAt && new Date(task.dueAt).toDateString() === new Date().toDateString()).length;
  return <div className="space-y-6"><PageIntro title="Every task has an owner and a reason." description="Clinical, front desk, billing, quality, and case work can be filtered without losing patient or audit context." action={<Button variant="primary"><Plus className="size-4" /> New task</Button>} />
    <div className="grid gap-4 sm:grid-cols-4"><StatCard accent="rose" detail="Needs action now" icon={<AlertOctagon className="size-4" />} label="Urgent" value={String(urgent)} /><StatCard accent="amber" detail="Based on the current date" icon={<Clock3 className="size-4" />} label="Due today" value={String(dueToday)} /><StatCard accent="sky" detail="Tenant-filtered work queue" icon={<Workflow className="size-4" />} label="Open" value={String(open.length)} /><StatCard accent="teal" detail="Completed in this workspace" icon={<Check className="size-4" />} label="Completed" value={String(workspace.tasks.length - open.length)} /></div>
    <SectionCard title="Team work queue" description="Every transition requires a human note and produces an audit receipt."><div className="divide-y divide-slate-100">{workspace.tasks.map((task) => <div className="p-5" key={task.id}><div className="grid gap-4 md:grid-cols-[1.4fr_.6fr_.5fr_auto] md:items-start"><div><div className="flex items-center gap-2"><StatusBadge status={task.priority} /><Badge tone="slate">{task.category}</Badge></div><p className="mt-3 text-xs font-extrabold text-slate-900">{task.title}</p><p className="mt-1 text-[10px] text-slate-400">{task.patientName}</p><p className="mt-2 text-[10px] leading-5 text-slate-500">{task.details}</p></div><div><p className="text-[8px] font-bold text-slate-400">OWNER</p><p className="mt-1 text-xs font-bold text-slate-700">{task.ownerId ?? "Unassigned"}</p></div><div><p className="text-[8px] font-bold text-slate-400">DUE</p><p className="mt-1 text-xs font-bold text-slate-700">{task.dueAt ? new Date(task.dueAt).toLocaleString() : "No due time"}</p></div><StatusBadge status={task.status} /></div><TaskActions taskId={task.id} status={task.status} /></div>)}{!workspace.tasks.length && <p className="p-6 text-xs text-slate-500">No tenant tasks are recorded.</p>}</div></SectionCard>
  </div>;
}

export function EscalationsWorkspace({ workspace }: { workspace: CareCoordinationWorkspace }) {
  const open = workspace.escalations.filter((escalation) => escalation.status !== "resolved");
  return <div className="space-y-6"><div className="rounded-[26px] bg-rose-950 p-7 text-white"><div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><p className="text-[10px] font-extrabold uppercase tracking-[.2em] text-rose-300">Human review queue</p><h2 className="mt-3 text-3xl font-extrabold tracking-[-.05em]">{open.length} items are safely held.</h2><p className="mt-3 max-w-2xl text-xs leading-6 text-rose-100/70">Urgent or clinically sensitive content cannot complete automatically. The responsible licensed or authorized team must review and act.</p></div><Button className="bg-white text-rose-950 hover:bg-rose-50" variant="secondary"><PhoneCall className="size-4" /> Open callback console</Button></div></div>
    <div className="grid gap-4 sm:grid-cols-3"><StatCard accent="rose" detail="Require human action" icon={<AlertOctagon className="size-4" />} label="Open" value={String(open.length)} /><StatCard accent="amber" detail="Tenant-visible alerts" icon={<ShieldAlert className="size-4" />} label="Total" value={String(workspace.escalations.length)} /><StatCard accent="teal" detail="Resolved with a note" icon={<Check className="size-4" />} label="Resolved" value={String(workspace.escalations.length - open.length)} /></div>
    <div className="space-y-4">{workspace.escalations.map((item, index) => <Card className={`p-5 ${index === 0 ? "border-rose-300 shadow-[0_18px_45px_rgba(190,24,93,.12)]" : ""}`} key={item.id}><div className="grid gap-5 lg:grid-cols-[1.2fr_.7fr_.8fr] lg:items-start"><div className="flex items-start gap-4"><span className={`grid size-11 shrink-0 place-items-center rounded-xl ${item.riskLevel === "URGENT" ? "bg-rose-100 text-rose-700" : "bg-amber-50 text-amber-700"}`}><ShieldAlert className="size-5" /></span><div><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-extrabold text-slate-950">{item.category.replaceAll("_", " ")}</p><StatusBadge status={item.riskLevel.replaceAll("_", " ")} /></div><p className="mt-1 text-[10px] text-slate-400">{item.patientName} · {item.sourceType} · {new Date(item.createdAt).toLocaleString()}</p><p className="mt-2 text-[10px] leading-5 text-slate-600">Source: {item.sourceId} · Assigned team: {item.assignedTeam}</p></div></div><div><p className="text-[8px] font-bold text-slate-400">STATUS</p><p className="mt-1 text-xs font-bold text-slate-700">{item.status}</p><p className="mt-2 text-[10px] leading-5 text-slate-500">{item.resolution ?? "No human resolution note yet."}</p></div><EscalationActions escalationId={item.id} status={item.status} /></div></Card>)}{!workspace.escalations.length && <Card className="p-6 text-xs text-slate-500">No escalations are recorded for this organization.</Card>}</div>
  </div>;
}

export function AiAssistantsWorkspace() {
  const assistants = [
    { name: "Front Desk Agent", scope: "Classify requests, draft office-safe replies, create tasks", icon: PhoneCall, status: "Demo-ready", tone: "teal" },
    { name: "Provider Prep Agent", scope: "Summarize chart history and missing visit information", icon: Stethoscope, status: "Human review", tone: "sky" },
    { name: "Billing Prep Agent", scope: "Flag missing claim fields before biller review", icon: CircleDollarSign, status: "Roadmap", tone: "amber" },
    { name: "Quality Gap Agent", scope: "Prepare outreach lists from configured measure rules", icon: HeartPulse, status: "Roadmap", tone: "rose" },
  ];
  return <div className="space-y-6"><PageIntro title="AI for workflow, never for practicing medicine." description="ClinicOS assistants summarize, classify, draft, route, detect missing information, and prepare reports. Diagnosis, prescribing, interpretation, treatment, and final clinical communication stay human." />
    <section className="grid gap-6 xl:grid-cols-[1.1fr_.9fr]"><AiWorkflowDemo /><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-1">{assistants.map((assistant) => <Card className="p-4" key={assistant.name}><div className="flex items-start gap-3"><span className={`grid size-10 place-items-center rounded-xl ${assistant.tone === "teal" ? "bg-teal-50 text-teal-700" : assistant.tone === "sky" ? "bg-sky-50 text-sky-700" : assistant.tone === "amber" ? "bg-amber-50 text-amber-700" : "bg-rose-50 text-rose-700"}`}><assistant.icon className="size-5" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="text-xs font-extrabold text-slate-950">{assistant.name}</p><StatusBadge status={assistant.status} /></div><p className="mt-2 text-[10px] leading-5 text-slate-500">{assistant.scope}</p></div></div></Card>)}</div></section>
    <Card className="border-slate-800 bg-slate-950 p-6 text-white"><div className="grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><div><Bot className="size-7 text-lime-300" /><h3 className="mt-5 text-2xl font-extrabold tracking-[-.04em]">Hard clinical boundaries</h3><p className="mt-3 text-xs leading-6 text-slate-400">These rules are part of the workflow engine, not optional wording in a prompt.</p></div><div className="grid gap-2 sm:grid-cols-2">{["No diagnosis", "No prescribing", "No treatment decisions", "No final lab interpretation", "No insurance guarantees", "No record release without approval"].map((rule) => <div className="flex items-center gap-2 rounded-xl bg-white/6 p-3 ring-1 ring-inset ring-white/10" key={rule}><LockKeyhole className="size-3.5 text-teal-300" /><p className="text-[10px] font-bold text-slate-200">{rule}</p></div>)}</div></div></Card>
  </div>;
}

export function PatientNavigationWorkspace({ workspace, canCreate, canReview }: { workspace: PatientNavigationWorkspace; canCreate: boolean; canReview: boolean }) {
  const openDrafts = workspace.drafts.filter((draft) => draft.status === "draft");
  const urgent = workspace.escalations.filter((escalation) => escalation.status !== "resolved" && escalation.riskLevel === "URGENT").length;
  return <div className="space-y-6"><PageIntro title="Guide the next step without practicing medicine." description="Patient Navigation prepares administrative guidance, checks the safety boundary, and routes anything clinical or urgent to the right human queue. Drafts never send automatically." aside={<Badge tone="sky"><Sparkles className="mr-1.5 size-3" /> Human-reviewed AI</Badge>} />
    <div className="grid gap-4 sm:grid-cols-4"><StatCard accent="amber" detail="Awaiting staff or provider review" icon={<Workflow className="size-4" />} label="Drafts" value={String(openDrafts.length)} /><StatCard accent="rose" detail="Routine processing stopped" icon={<ShieldAlert className="size-4" />} label="Urgent holds" value={String(urgent)} /><StatCard accent="sky" detail="Tenant-filtered schedule context" icon={<CalendarDays className="size-4" />} label="Appointments" value={String(workspace.appointments.length)} /><StatCard accent="teal" detail="Open care-navigation context" icon={<ArrowRight className="size-4" />} label="Referrals" value={String(workspace.referrals.length)} /></div>
    <section className="grid gap-6 xl:grid-cols-[.75fr_1.25fr]"><Card className="overflow-hidden"><div className="border-b border-slate-100 bg-slate-950 p-5 text-white"><p className="text-[10px] font-extrabold uppercase tracking-[.18em] text-teal-300">Create a safe draft</p><h3 className="mt-3 text-xl font-extrabold tracking-[-.04em]">What administrative help is needed?</h3><p className="mt-2 text-xs leading-5 text-slate-400">Use plain language. The engine identifies emergency, medical, insurance, and case-management boundaries before creating work.</p></div>{canCreate ? <NavigationDraftActions patients={workspace.patients} /> : <p className="p-5 text-xs text-slate-500">Your role can view navigation work but cannot create drafts.</p>}<div className="border-t border-slate-100 bg-amber-50 p-5"><p className="text-[9px] font-extrabold uppercase tracking-[.16em] text-amber-800">Safety contract</p><p className="mt-2 text-xs leading-5 text-amber-900">No diagnosis, prescribing, lab interpretation, insurance guarantee, emergency triage, or automatic send. Urgent requests create a visible escalation.</p></div></Card><SectionCard title="Navigation review queue" description="Every draft remains blocked from send until an authorized human reviews it."><div className="divide-y divide-slate-100">{workspace.drafts.map((draft) => <div className="p-5" key={draft.id}><div className="flex flex-wrap items-start gap-2"><div className="min-w-0 flex-1"><p className="text-xs font-extrabold text-slate-900">{draft.patientName}</p><p className="mt-1 text-[10px] text-slate-400">{draft.purpose.replaceAll("_", " ")} · {new Date(draft.createdAt).toLocaleString()}</p></div><StatusBadge status={draft.status} /><StatusBadge status={draft.riskLevel.replaceAll("_", " ")} /></div><p className="mt-4 rounded-xl bg-slate-50 p-4 text-xs leading-5 text-slate-700">{draft.content}</p><div className="mt-3 flex items-center gap-2"><Badge tone="rose">Blocked from send</Badge>{canReview && <NavigationReviewActions disabled={draft.status !== "draft"} draftId={draft.id} />}</div></div>)}{!workspace.drafts.length && <p className="p-5 text-xs text-slate-500">No navigation drafts have been created.</p>}</div></SectionCard></section>
    <section className="grid gap-6 lg:grid-cols-2"><SectionCard title="Appointment context" description="Scheduling guidance can use context without confirming a booking."><div className="divide-y divide-slate-100">{workspace.appointments.slice(0, 6).map((appointment) => <div className="flex items-center justify-between gap-3 p-4" key={appointment.id}><div><p className="text-xs font-extrabold text-slate-900">{appointment.patientName} · {appointment.mrn}</p><p className="mt-1 text-[10px] text-slate-500">{new Date(appointment.startsAt).toLocaleString()} · {appointment.notes ?? "No scheduling note"}</p></div><StatusBadge status={appointment.status} /></div>)}{!workspace.appointments.length && <p className="p-4 text-xs text-slate-500">No appointment context is available.</p>}</div></SectionCard><SectionCard title="Referral context" description="Navigation can point patients to the next referral step while keeping clinical questions with providers."><div className="divide-y divide-slate-100">{workspace.referrals.slice(0, 6).map((referral) => <div className="flex items-center justify-between gap-3 p-4" key={referral.id}><div><p className="text-xs font-extrabold text-slate-900">{referral.patientName} · {referral.specialty}</p><p className="mt-1 text-[10px] text-slate-500">{referral.mrn} · Follow-up {referral.followUpDueAt ? new Date(referral.followUpDueAt).toLocaleDateString() : "not set"}</p></div><StatusBadge status={referral.status} /></div>)}{!workspace.referrals.length && <p className="p-4 text-xs text-slate-500">No open referrals are available.</p>}</div></SectionCard></section>
  </div>;
}

export function ProviderConsultationWorkspace({ workspace, credentialing, canCreate, canReview, canCredentialingCreate, canCredentialingManage }: { workspace: ProviderConsultationWorkspace; credentialing: CredentialingWorkspaceData; canCreate: boolean; canReview: boolean; canCredentialingCreate: boolean; canCredentialingManage: boolean }) {
  const open = workspace.consultations.filter((consultation) => !["closed", "declined"].includes(consultation.status));
  const verified = workspace.providers.filter((provider) => provider.verified).length;
  return <div className="space-y-6"><PageIntro title="A documented consult, not a loose message." description="Find current credential snapshots, request provider-to-provider review, and keep responsibility with the requesting provider until a consultation is explicitly closed." aside={<Badge tone="sky"><Stethoscope className="mr-1.5 size-3" /> Credential-aware network</Badge>} /><CredentialingWorkspace canCreate={canCredentialingCreate} canManage={canCredentialingManage} workspace={credentialing} />
    <div className="grid gap-4 sm:grid-cols-4"><StatCard accent="teal" detail="Current active credential snapshot" icon={<BadgeCheck className="size-4" />} label="Verified providers" value={String(verified)} /><StatCard accent="amber" detail="Human-owned requests" icon={<Workflow className="size-4" />} label="Open consults" value={String(open.length)} /><StatCard accent="sky" detail="Network-visible patient context" icon={<UserRoundCheck className="size-4" />} label="Patients" value={String(workspace.patients.length)} /><StatCard accent="slate" detail="Approved clinic connections" icon={<Network className="size-4" />} label="Connections" value={String(workspace.connections.length)} /></div>
    <section className="grid gap-6 xl:grid-cols-[.7fr_1.3fr]"><Card className="overflow-hidden"><div className="border-b border-slate-100 bg-slate-950 p-5 text-white"><p className="text-[10px] font-extrabold uppercase tracking-[.18em] text-teal-300">Request provider review</p><h3 className="mt-3 text-xl font-extrabold tracking-[-.04em]">Ask a verified colleague.</h3><p className="mt-2 text-xs leading-5 text-slate-400">Clinical responsibility stays with the requesting provider. External requests require an active clinic connection and a current credential.</p></div>{canCreate ? <ProviderConsultationCreateAction patients={workspace.patients} providers={workspace.providers} /> : <p className="p-5 text-xs text-slate-500">Your role can view consultations but cannot create them.</p>}<div className="border-t border-slate-100 bg-amber-50 p-5"><p className="text-[9px] font-extrabold uppercase tracking-[.16em] text-amber-800">Adapter boundary</p><p className="mt-2 text-xs leading-5 text-amber-900">Secure provider room, compensation, and external record transfer remain explicit adapter/manual workflows. This surface never claims vendor connectivity.</p></div></Card><SectionCard title="Consultation queue" description="Requests, acceptance, scheduling, decline, and closure are recorded as human transitions with audit receipts."><div className="divide-y divide-slate-100">{workspace.consultations.map((consultation) => <div className="p-5" key={consultation.id}><div className="flex flex-wrap items-start gap-2"><div className="min-w-0 flex-1"><p className="text-xs font-extrabold text-slate-900">{consultation.patientName}{consultation.mrn ? ` · ${consultation.mrn}` : ""}</p><p className="mt-1 text-[10px] text-slate-400">{consultation.specialty} · Requested by {consultation.requestingProvider} · Consultant {consultation.consultantProvider}</p></div><StatusBadge status={consultation.status} /><StatusBadge status={consultation.priority} /></div><p className="mt-4 rounded-xl bg-slate-50 p-4 text-xs leading-5 text-slate-700">{consultation.clinicalQuestion}</p><p className="mt-3 text-[10px] text-slate-400">{consultation.scheduledAt ? `Scheduled ${new Date(consultation.scheduledAt).toLocaleString()}` : "No consultation time recorded"} · Updated {new Date(consultation.updatedAt).toLocaleString()}</p>{canReview && <ProviderConsultationTransitionActions consultationId={consultation.id} status={consultation.status} />}</div>)}{!workspace.consultations.length && <p className="p-5 text-xs text-slate-500">No consultation requests have been created.</p>}</div></SectionCard></section>
    <SectionCard title="Verified provider directory" description="Only providers in the current clinic or an active connected clinic are shown; credentials are status snapshots, not a legal guarantee."><div className="grid gap-3 p-4 sm:grid-cols-2 lg:grid-cols-3">{workspace.providers.map((provider) => <div className="rounded-2xl border border-slate-200 p-4" key={provider.id}><div className="flex items-start justify-between gap-2"><div><p className="text-xs font-extrabold text-slate-900">{provider.name}, {provider.credential}</p><p className="mt-1 text-[10px] text-slate-500">{provider.specialty ?? "Specialty pending"}</p></div><StatusBadge status={provider.verified ? "Verified" : "Credential review"} /></div><p className="mt-3 text-[10px] text-slate-400">{provider.organizationName} · {provider.credentialType ?? "No credential snapshot"}{provider.credentialState ? ` · ${provider.credentialState}` : ""}</p><p className="mt-1 text-[10px] text-slate-400">{provider.credentialExpiresAt ? `Expires ${new Date(provider.credentialExpiresAt).toLocaleDateString()}` : "Expiration not recorded"}</p></div>)}</div></SectionCard>
  </div>;
}

export function PortalWorkspace() {
  return <div className="space-y-6"><PageIntro title="A patient experience the clinic controls." description="Patients use a separate authenticated identity to see appointments, forms, approved documents and results, visit summaries, balances, messages, and telemedicine links based on explicit release rules." action={<Button asChild variant="primary"><Link href="/portal/login"><MonitorSmartphone className="size-4" /> Open patient sign-in</Link></Button>} />
    <section className="grid gap-8 xl:grid-cols-[.65fr_1.35fr]">
      <div className="mx-auto w-full max-w-[420px] rounded-[38px] bg-slate-950 p-3 shadow-[0_30px_80px_rgba(15,23,42,.25)]"><div className="min-h-[720px] overflow-hidden rounded-[29px] bg-[#f5f8f7]"><div className="bg-[#0e414b] p-6 pb-8 text-white"><div className="flex items-center justify-between"><p className="text-xs font-extrabold">ClinicOS Portal</p><span className="grid size-8 place-items-center rounded-full bg-white/10 text-[9px] font-extrabold">MT</span></div><p className="mt-8 text-[10px] text-teal-200">Good morning, Maya</p><h3 className="mt-2 text-2xl font-extrabold tracking-[-.04em]">Your care, clearly organized.</h3></div><div className="space-y-3 p-4"><div className="rounded-2xl bg-white p-4 shadow-sm"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-teal-50 text-teal-700"><CalendarDays className="size-4" /></span><div><p className="text-[9px] font-bold text-slate-400">NEXT APPOINTMENT</p><p className="mt-1 text-xs font-extrabold text-slate-900">Today · 10:30 AM</p><p className="mt-1 text-[9px] text-slate-500">Diabetes follow-up</p></div></div><Button className="mt-4 w-full" size="sm" variant="secondary">View appointment</Button></div><div className="grid grid-cols-2 gap-3">{[[FileText, "Forms", "All complete"], [FlaskConical, "Results", "1 approved"], [CircleDollarSign, "Balance", "$75 due"], [MessagesSquare, "Messages", "1 new"]].map(([Icon, label, detail]) => { const PortalIcon = Icon as typeof FileText; return <button className="rounded-2xl bg-white p-4 text-left shadow-sm" key={String(label)}><PortalIcon className="size-4 text-teal-700" /><p className="mt-4 text-xs font-extrabold text-slate-900">{String(label)}</p><p className="mt-1 text-[9px] text-slate-400">{String(detail)}</p></button>; })}</div><div className="rounded-2xl bg-amber-50 p-4 ring-1 ring-inset ring-amber-100"><p className="text-[10px] font-extrabold text-amber-900">A result is under review</p><p className="mt-2 text-[9px] leading-5 text-amber-800">Your care team will release it when provider review is complete.</p></div></div></div></div>
      <div className="space-y-6"><SectionCard title="Patient-visible surfaces"><div className="grid gap-3 p-4 sm:grid-cols-2">{[[CalendarDays, "Appointments", "Requests, confirmation, telemedicine"], [ClipboardCheck, "Forms & consents", "Complete, sign, upload"], [FileCheck2, "Approved records", "Results, summaries, documents"], [CircleDollarSign, "Payments", "Balances and payment links"], [MessageCircle, "Secure messages", "Office and reviewed clinical replies"], [UserRoundCheck, "Profile", "Demographics and preferences"]].map(([Icon, title, body]) => { const TileIcon = Icon as typeof CalendarDays; return <div className="rounded-2xl border border-slate-200 p-4" key={String(title)}><TileIcon className="size-5 text-teal-700" /><p className="mt-4 text-xs font-extrabold text-slate-900">{String(title)}</p><p className="mt-2 text-[10px] leading-5 text-slate-500">{String(body)}</p></div>; })}</div></SectionCard><Card className="bg-[#dff7f1] p-6"><ShieldCheck className="size-6 text-teal-700" /><p className="mt-5 text-xl font-extrabold tracking-[-.04em] text-slate-950">Visibility is explicit.</p><p className="mt-3 text-xs leading-6 text-slate-600">Every result and document carries patient-visible, internal-only, review, and release state. The demo does not imply that all clinical records are automatically released.</p></Card></div>
    </section>
  </div>;
}

export function IntegrationsWorkspace() {
  const integrations = [
    ["FHIR / SMART", "Clinical interoperability", "Roadmap", "High", "BAA + authorization", "Phase 4"],
    ["HL7 lab feeds", "Inbound orders and results", "Roadmap", "High", "BAA + interface", "Phase 4"],
    ["Quest Diagnostics", "Lab orders and results", "Manual demo", "High", "Vendor contract", "Phase 4"],
    ["Labcorp", "Lab orders and results", "Manual demo", "High", "Vendor contract", "Phase 4"],
    ["BioReference", "Lab orders and results", "Manual demo", "High", "Vendor contract", "Phase 4"],
    ["Radiology / imaging", "Orders and reports", "Manual demo", "High", "BAA + interface", "Phase 5"],
    ["270 / 271", "Eligibility", "Roadmap", "Medium", "Clearinghouse", "Phase 3"],
    ["837 / 835", "Claims and remittance", "Roadmap", "High", "Clearinghouse", "Phase 3"],
    ["276 / 277 / 278", "Claim status and prior auth", "Roadmap", "High", "Clearinghouse", "Phase 5"],
    ["Stripe", "Patient payments", "Roadmap", "Medium", "BAA scope review", "Phase 2"],
    ["Twilio", "Voice and SMS", "Roadmap", "High", "BAA + consent", "Phase 2"],
    ["Telemedicine vendor", "Secure virtual visits", "Roadmap", "High", "BAA", "Phase 3"],
  ];
  return <div className="space-y-6"><PageIntro title="Standards first. Integrations only when they are real." description="Every future connection lists purpose, current state, risk, contractual need, and implementation phase. None of these tiles claim live connectivity." action={<Button variant="secondary"><Blocks className="size-4" /> Export roadmap</Button>} />
    <div className="grid gap-4 sm:grid-cols-4"><StatCard accent="teal" detail="Internal demo services" icon={<Check className="size-4" />} label="Connected" value="2" /><StatCard accent="sky" detail="Contracts not started" icon={<Webhook className="size-4" />} label="Mapped" value="12" /><StatCard accent="amber" detail="BAA or security review" icon={<ShieldAlert className="size-4" />} label="High-risk" value="9" /><StatCard accent="slate" detail="FHIR and X12 layers" icon={<Cloud className="size-4" />} label="Standards" value="6" /></div>
    <SectionCard title="Integration roadmap" description="Owners and vendor-specific implementation details belong in a governed delivery plan."><div className="overflow-x-auto"><table className="w-full min-w-[940px] text-left"><thead><tr className="border-b border-slate-100 text-[9px] font-extrabold uppercase tracking-[.14em] text-slate-400"><th className="px-5 py-3">Connection</th><th className="px-3 py-3">Purpose</th><th className="px-3 py-3">Current status</th><th className="px-3 py-3">Risk</th><th className="px-3 py-3">Requirement</th><th className="px-5 py-3">Phase</th></tr></thead><tbody>{integrations.map(([name, purpose, status, risk, need, phase]) => <tr className="border-b border-slate-100 text-xs last:border-0" key={name}><td className="px-5 py-4 font-extrabold text-slate-900">{name}</td><td className="px-3 py-4 text-slate-600">{purpose}</td><td className="px-3 py-4"><StatusBadge status={status} /></td><td className="px-3 py-4"><StatusBadge status={risk} /></td><td className="px-3 py-4 text-slate-500">{need}</td><td className="px-5 py-4"><Badge tone="slate">{phase}</Badge></td></tr>)}</tbody></table></div></SectionCard>
  </div>;
}

export function SettingsWorkspace() {
  return <div className="space-y-6"><PageIntro title="Organization controls with an audit trail." description="Clinic identity, locations, roles, permissions, safety policies, retention, sessions, and future integration secrets belong behind controlled administration." action={<Button variant="primary"><Settings2 className="size-4" /> Save settings</Button>} />
    <div className="grid gap-6 xl:grid-cols-[.7fr_1.3fr]"><div className="space-y-4"><SectionCard title="Organization"><div className="space-y-1 p-3">{["Practice profile", "Locations & departments", "Providers & credentials", "Users & roles", "Appointment types", "Form templates", "Billing settings", "Quality measures"].map((item, index) => <button className={`flex w-full items-center gap-3 rounded-xl p-3 text-left text-xs font-bold ${index === 0 ? "bg-slate-950 text-white" : "text-slate-600 hover:bg-slate-50"}`} key={item}>{item}<ChevronRight className="ml-auto size-4 opacity-50" /></button>)}</div></SectionCard><Card className="p-5"><Fingerprint className="size-5 text-teal-700" /><p className="mt-4 text-sm font-extrabold text-slate-950">Security foundation</p><p className="mt-2 text-[10px] leading-5 text-slate-500">Passkeys, MFA, device sessions, suspicious-login alerts, and production identity are designed but not connected in this demo.</p></Card></div>
      <div className="space-y-6"><SectionCard title="Practice profile" description="This organization boundary scopes every connected demo record."><div className="grid gap-4 p-5 sm:grid-cols-2"><SettingField label="Organization name" value="Brooklyn Family Medicine" /><SettingField label="Clinic type" value="Primary Care" /><SettingField label="Primary location" value="Brooklyn Heights" /><SettingField label="Timezone" value="America/New_York" /><SettingField label="Default provider" value="Nadja R., NP" /><SettingField label="Demo mode" value="Enabled - fake records only" /></div></SectionCard><SectionCard title="Recent audit activity" description="A production system requires durable, tamper-resistant access and mutation records."><div className="divide-y divide-slate-100">{auditEvents.map((event) => <div className="grid gap-3 p-4 sm:grid-cols-[1fr_.8fr_.55fr] sm:items-center" key={event.actor + event.time}><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-slate-100 text-slate-600"><Activity className="size-4" /></span><div><p className="text-xs font-extrabold text-slate-900">{event.action}</p><p className="mt-1 text-[9px] text-slate-400">{event.actor}</p></div></div><p className="text-[10px] font-bold text-slate-600">{event.target}</p><div className="text-right"><p className="text-[10px] font-bold text-slate-600">{event.time}</p><p className="mt-1 text-[8px] text-slate-400">{event.source}</p></div></div>)}</div></SectionCard></div></div>
  </div>;
}

function SettingField({ label, value }: { label: string; value: string }) {
  return <label className="block"><span className="text-[9px] font-extrabold uppercase tracking-[.12em] text-slate-400">{label}</span><input className="mt-2 h-10 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 text-xs font-bold text-slate-700 outline-none focus:border-teal-400 focus:bg-white" defaultValue={value} /></label>;
}
