import Link from "next/link";
import {
  ArrowRight, AudioLines, BadgeCheck, Building2,
  FileCheck2, Fingerprint, HeartHandshake, KeyRound, MapPin, Network, Orbit,
  RadioTower, Route, ShieldCheck, Sparkles,
} from "lucide-react";
import { AiWorkflowDemo } from "@/components/clinic/ai-workflow-demo";
import { PageIntro, Progress, SectionCard, StatusBadge } from "@/components/clinic/workspace-kit";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import type { CanonicalRegistrySection } from "@/lib/feature-registry-canon";
import type { ConnectedCareOverview } from "@/lib/repositories/connected-care-repository";

export function NetworkWorkspace({ overview }: { overview: ConnectedCareOverview }) {
  return <div className="space-y-6">
    <div className="network-command relative overflow-hidden rounded-[28px] bg-[#07131f] p-6 text-white shadow-[0_28px_80px_rgba(2,12,23,.22)] sm:p-8">
      <div className="absolute -right-20 -top-24 size-80 rounded-full border border-sky-300/20 bg-sky-400/5" /><div className="absolute -right-4 top-12 size-40 rounded-full border border-teal-300/20" />
      <div className="relative grid gap-8 lg:grid-cols-[1fr_.8fr] lg:items-center"><div><Badge className="bg-white/10 text-sky-200 ring-white/15"><RadioTower className="mr-1.5 size-3" /> Network Mode</Badge><h2 className="mt-5 max-w-2xl text-3xl font-black tracking-[-.055em] sm:text-5xl">Connected care, visible as it moves.</h2><p className="mt-4 max-w-xl text-sm leading-7 text-slate-300">Verified organizations coordinate through purpose-bound access, provenance, consent, delivery status, and human-controlled fallbacks.</p><div className="mt-6 flex flex-wrap gap-2"><Button asChild className="bg-white text-slate-950 hover:bg-sky-50" size="sm"><Link href="/care-teams">Open Care Constellation <ArrowRight className="size-3.5" /></Link></Button><Button asChild className="border-white/20 bg-white/5 text-white hover:bg-white/10" size="sm" variant="secondary"><Link href="/feature-registry">View P0 registry</Link></Button></div></div>
        <div className="grid grid-cols-2 gap-3">{[[String(overview.connections.length), "Trusted links"], [String(overview.careTeams.length), "Care rooms"], [String(overview.capacity.length), "Open capacity"], [String(overview.passports.length), "Passports"]].map(([value, label]) => <div className="rounded-2xl bg-white/[.07] p-4 ring-1 ring-white/10" key={label}><p className="text-3xl font-black tracking-[-.05em]">{value}</p><p className="mt-1 text-[10px] font-bold text-slate-400">{label}</p></div>)}</div></div>
    </div>
    <div className="grid gap-4 lg:grid-cols-2">
      <SectionCard title="Verified clinic graph" description="Synthetic demo connections. Joining the network never grants unlimited chart access.">{overview.connections.length ? <div className="space-y-3 p-4">{overview.connections.map((connection) => <div className="flex items-center gap-3 rounded-2xl border border-slate-200 p-4" key={connection.id}><span className="grid size-10 place-items-center rounded-xl bg-sky-50 text-sky-700"><Building2 className="size-5" /></span><div className="min-w-0 flex-1"><p className="text-xs font-extrabold text-slate-900">{connection.source} <span className="text-slate-300">→</span> {connection.target}</p><p className="mt-1 text-[10px] text-slate-500">{connection.allowedPurposes.join(" · ")} · {connection.trustLevel}</p></div><StatusBadge status={connection.status} /></div>)}</div> : <Empty label="No verified connections yet" />}</SectionCard>
      <SectionCard title="Closed-loop movement" description="Every exchange must show what is happening, who acts next, and what is blocked."><div className="space-y-3 p-4">{[["Referral accepted", "Diagnostic partner", "Schedule the patient", "Complete"], ["Record request", "Privacy reviewer", "Confirm data categories", "Needs review"], ["Consultation note", "Referring provider", "Acknowledge and close loop", "Pending"]].map(([event, owner, action, status]) => <div className="grid gap-3 rounded-2xl bg-slate-50 p-4 sm:grid-cols-[1fr_1fr_auto]" key={event}><div><p className="text-[9px] font-bold text-slate-400">WHAT IS HAPPENING</p><p className="mt-1 text-xs font-extrabold text-slate-900">{event}</p></div><div><p className="text-[9px] font-bold text-slate-400">NEXT OWNER</p><p className="mt-1 text-xs font-bold text-slate-700">{owner}: {action}</p></div><StatusBadge status={status} /></div>)}</div></SectionCard>
    </div>
  </div>;
}

export function CareTeamsWorkspace({ overview }: { overview: ConnectedCareOverview }) {
  const room = overview.careTeams[0];
  const nodes = [
    ["Primary care", "Nadja R., NP", "bg-teal-500", "left-[6%] top-[44%]"],
    ["Imaging", "Diagnostic Exchange", "bg-sky-500", "right-[4%] top-[18%]"],
    ["Consultant", "Samuel Lee, MD", "bg-amber-400", "right-[7%] bottom-[12%]"],
  ];
  return <div className="space-y-6"><PageIntro title="Care Constellation" description="A shared, permissioned care map where responsibility, organization, next action, and activity remain visible." aside={<Badge tone="sky">Network Mode</Badge>} />
    <div className="grid gap-4 xl:grid-cols-[1.25fr_.75fr]"><Card className="relative min-h-[520px] overflow-hidden bg-[#07131f] p-6 text-white"><div className="absolute inset-0 opacity-30 clinical-grid" /><div className="relative"><div className="flex items-center justify-between"><div><p className="text-[9px] font-extrabold uppercase tracking-[.18em] text-sky-300">{room?.mrn ?? "Synthetic demo"}</p><h3 className="mt-1 text-xl font-black">{room?.name ?? "No active Care Team Room"}</h3></div><Badge className="bg-white/10 text-white ring-white/15">{room?.memberCount ?? 0} members</Badge></div>
      <div className="relative mt-8 h-[390px] rounded-[24px] border border-white/10 bg-white/[.035]"><svg className="absolute inset-0 h-full w-full" aria-hidden><line x1="50%" y1="50%" x2="18%" y2="50%" stroke="rgba(45,212,191,.35)" /><line x1="50%" y1="50%" x2="80%" y2="27%" stroke="rgba(56,189,248,.35)" /><line x1="50%" y1="50%" x2="80%" y2="77%" stroke="rgba(251,191,36,.35)" /></svg><div className="absolute left-1/2 top-1/2 grid size-28 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full bg-white text-center text-slate-950 shadow-[0_0_70px_rgba(125,211,252,.25)] ring-8 ring-white/5"><div><Orbit className="mx-auto size-5 text-teal-600" /><p className="mt-1 text-xs font-black">{room?.patientName ?? "Patient"}</p><p className="text-[8px] text-slate-400">Patient center</p></div></div>{nodes.map(([role, name, color, position]) => <div className={`absolute ${position} w-36 rounded-2xl bg-white/10 p-3 ring-1 ring-white/15 backdrop-blur`} key={role}><span className={`block size-2 rounded-full ${color}`} /><p className="mt-2 text-[9px] font-bold text-slate-400">{role}</p><p className="mt-1 text-[10px] font-extrabold text-white">{name}</p></div>)}</div></div></Card>
      <div className="space-y-4"><SectionCard title="Shared plan" description="Clinical content remains subject to licensed review."><div className="space-y-3 p-4">{[["Current status", room?.status ?? "No room"], ["Responsible", "Primary care"], ["Next action", "Provider reviews repeat A1C order"], ["Risk", "Needs provider"]].map(([label, value]) => <div className="rounded-xl bg-slate-50 p-3" key={label}><p className="text-[9px] font-bold text-slate-400">{label.toUpperCase()}</p><p className="mt-1 text-xs font-extrabold text-slate-900">{value}</p></div>)}</div></SectionCard><SectionCard title="Minimum necessary" description="Membership does not equal full-chart access."><div className="p-4 text-xs leading-6 text-slate-600"><ShieldCheck className="mb-3 size-5 text-teal-600" />Team members receive only purpose-bound categories, with consent expiration, revocation, and a patient-visible access history.</div></SectionCard></div></div>
  </div>;
}

export function CapacityExchangeWorkspace({ overview }: { overview: ConnectedCareOverview }) {
  return <div className="space-y-6"><PageIntro title="Capacity Exchange" description="Travel-booking clarity for verified clinical and diagnostic capacity, with authorization and manual confirmation kept visible." action={<Button variant="primary"><Route className="size-4" /> Find capacity</Button>} />
    <Card className="overflow-hidden"><div className="grid gap-3 border-b border-slate-100 bg-slate-50 p-4 md:grid-cols-4">{[["Service", "MRI Lumbar Spine"], ["Payer", "GEICO No-Fault"], ["Urgency", "High"], ["Area", "Brooklyn / Queens"]].map(([label, value]) => <div className="rounded-xl border border-slate-200 bg-white p-3" key={label}><p className="text-[9px] font-bold text-slate-400">{label.toUpperCase()}</p><p className="mt-1 text-xs font-extrabold text-slate-900">{value}</p></div>)}</div><div className="divide-y divide-slate-100">{overview.capacity.map((listing, index) => <div className="grid gap-4 p-5 md:grid-cols-[auto_1fr_auto] md:items-center" key={listing.id}><span className="grid size-12 place-items-center rounded-2xl bg-sky-50 text-sky-700"><MapPin className="size-5" /></span><div><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-extrabold text-slate-950">{listing.facility}</p>{index === 0 && <Badge tone="teal">Earliest verified</Badge>}</div><p className="mt-1 text-xs text-slate-500">{listing.service} · {listing.location} · {new Date(listing.startsAt).toLocaleString("en-US", { weekday: "short", hour: "numeric", minute: "2-digit" })}</p><p className="mt-2 text-[9px] font-bold text-slate-400">{listing.acceptedPayers.join(" · ")} · Manual confirmation required</p></div><Button size="sm" variant="secondary">Request slot <ArrowRight className="size-3.5" /></Button></div>)}{overview.capacity.length === 0 && <Empty label="No published capacity for this organization" />}</div></Card>
  </div>;
}

export function HealthPassportWorkspace({ overview }: { overview: ConnectedCareOverview }) {
  const passport = overview.passports[0];
  return <div className="space-y-6"><PageIntro title="Health Passport + Consent Wallet" description="A portable patient summary paired with category-level, purpose-bound sharing controls and access receipts." aside={<Badge tone="teal">Patient controlled</Badge>} />
    <div className="grid gap-4 xl:grid-cols-[1fr_.9fr]"><Card className="overflow-hidden"><div className="bg-gradient-to-br from-[#07131f] via-[#102e3d] to-[#0d6b68] p-6 text-white"><div className="flex items-start justify-between"><span className="grid size-12 place-items-center rounded-2xl bg-white/10 ring-1 ring-white/15"><Fingerprint className="size-6 text-teal-200" /></span><Badge className="bg-white/10 text-white ring-white/15">{passport?.status ?? "Unavailable"}</Badge></div><p className="mt-8 text-[9px] font-bold uppercase tracking-[.18em] text-teal-200">ClinicOS Health Passport</p><h3 className="mt-2 text-2xl font-black tracking-[-.04em]">{passport?.patientName ?? "No passport found"}</h3><p className="mt-1 text-xs text-slate-300">{passport?.mrn ?? "Synthetic demo data"} · Last confirmed {passport?.lastConfirmedAt ? new Date(passport.lastConfirmedAt).toLocaleDateString() : "not yet"}</p></div><div className="grid gap-3 p-5 sm:grid-cols-2">{[["Allergies", "Penicillin"], ["Medications", "Metformin · Lisinopril"], ["Problems", "Diabetes · Hypertension"], ["Provenance", "Source organization labeled"]].map(([label, value]) => <div className="rounded-xl bg-slate-50 p-3" key={label}><p className="text-[9px] font-bold text-slate-400">{label.toUpperCase()}</p><p className="mt-1 text-xs font-extrabold text-slate-900">{value}</p></div>)}</div></Card>
      <SectionCard title="Consent Wallet" description="The patient controls who receives which category, for what purpose, and for how long."><div className="space-y-3 p-4">{[["Treatment sharing", "Ask each time", "Needs review"], ["Payment", "Organization only", "Active"], ["Sensitive records", "Blocked", "Restricted"], ["Emergency access", "Allow with alert", "Audited"]].map(([label, value, status]) => <div className="flex items-center gap-3 rounded-xl border border-slate-200 p-3" key={label}><KeyRound className="size-4 text-teal-600" /><div className="flex-1"><p className="text-xs font-extrabold text-slate-900">{label}</p><p className="mt-0.5 text-[10px] text-slate-500">{value}</p></div><StatusBadge status={status} /></div>)}</div></SectionCard></div>
  </div>;
}

export function InjuryEpisodesWorkspace({ overview }: { overview: ConnectedCareOverview }) {
  const episode = overview.episodes[0];
  return <div className="space-y-6"><PageIntro title="Injury Episode Room" description="Clinical care, diagnostics, legal participants, deadlines, documents, authorization, billing, and readiness in one command center." aside={<Badge tone="amber">Synthetic case demo</Badge>} />
    <div className="grid gap-4 xl:grid-cols-[.8fr_1.2fr]"><Card className="p-6"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-2xl bg-amber-50 text-amber-700"><HeartHandshake className="size-5" /></span><div><p className="text-sm font-extrabold text-slate-950">{episode?.title ?? "No active episode"}</p><p className="text-[10px] text-slate-500">{episode?.patientName} · {episode?.mrn}</p></div></div><div className="mt-8 flex items-end justify-between"><div><p className="text-[9px] font-bold text-slate-400">CLAIM READY</p><p className="mt-1 text-5xl font-black tracking-[-.07em] text-slate-950">{episode?.readinessScore ?? 0}<span className="text-xl text-slate-300">%</span></p></div><StatusBadge status={episode?.riskLevel.replaceAll("_", " ") ?? "Planned"} /></div><div className="mt-4"><Progress value={episode?.readinessScore ?? 0} tone="amber" /></div><div className="mt-6 rounded-2xl bg-slate-950 p-4 text-white"><p className="text-[9px] font-bold text-slate-400">NEXT ACTION</p><p className="mt-2 text-sm font-extrabold">{episode?.nextAction ?? "Create episode"}</p><p className="mt-1 text-[10px] text-slate-400">Owner: {episode?.responsibleRole?.replaceAll("_", " ") ?? "Unassigned"}</p></div></Card>
      <SectionCard title="Readiness checklist" description="Nothing is hidden behind a score; every missing input is explainable and assigned."><div className="grid gap-3 p-4 sm:grid-cols-2">{[["Provider signature", "Complete", "Provider"], ["Diagnosis support for CPT 99214", "Needs review", "Coding reviewer"], ["Prior authorization document", "Missing", "Front desk"], ["MRI report attached", "Pending", "Case manager"], ["Attorney contact verified", "Complete", "Case manager"], ["Claim packet export", "Blocked", "Biller"]].map(([item, status, owner]) => <div className="rounded-2xl border border-slate-200 p-4" key={item}><div className="flex items-start justify-between gap-2"><FileCheck2 className="size-4 text-slate-400" /><StatusBadge status={status} /></div><p className="mt-4 text-xs font-extrabold text-slate-900">{item}</p><p className="mt-1 text-[9px] font-bold text-slate-400">RESPONSIBLE: {owner.toUpperCase()}</p></div>)}</div></SectionCard></div>
  </div>;
}

export function VoiceAssistantWorkspace() {
  return <div className="space-y-6"><PageIntro title="Talk to ClinicOS" description="Speak or type in the same command surface. The transcript stays editable and nothing is sent until the user confirms the action." aside={<Badge tone="sky"><AudioLines className="mr-1.5 size-3" /> Voice-first demo</Badge>} />
    <div className="grid gap-4 lg:grid-cols-[1.1fr_.9fr]"><AiWorkflowDemo /><div className="space-y-4"><SectionCard title="Voice safety contract" description="Browser speech is a demonstration adapter, not a production PHI transcription claim."><div className="space-y-3 p-4">{[["No ambient recording", "Push-to-talk only"], ["Visible transcript", "Edit before analysis"], ["Clinical questions", "Route to provider"], ["Emergencies", "Stop routine processing"], ["Fallback", "Typing always available"]].map(([label, value]) => <div className="flex items-center gap-3 rounded-xl bg-slate-50 p-3" key={label}><BadgeCheck className="size-4 text-teal-600" /><div><p className="text-xs font-extrabold text-slate-900">{label}</p><p className="text-[10px] text-slate-500">{value}</p></div></div>)}</div></SectionCard><SectionCard title="Approved future adapter" description="A production transcription vendor requires security, retention, consent, BAA, failure recovery, and audit review before PHI use."><div className="p-4"><div className="flex items-center gap-3 rounded-xl border border-amber-200 bg-amber-50 p-3"><AudioLines className="size-5 text-amber-700" /><p className="text-[10px] leading-5 text-amber-900">Current mode: browser voice with synthetic demo data only. No audio is stored by ClinicOS.</p></div></div></SectionCard></div></div>
  </div>;
}

export function RegistryDomainWorkspace({ section }: { section: CanonicalRegistrySection }) {
  return <div className="space-y-6"><PageIntro title={section.title} description={section.mandate} aside={<><Badge tone="rose">P0</Badge><StatusBadge status={section.deliveryStatus.replace("_", " ")} /></>} />
    <div className="grid gap-4 lg:grid-cols-[.75fr_1.25fr]"><Card className="p-5"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-slate-950 text-white"><Sparkles className="size-4" /></span><div><p className="text-[9px] font-bold text-slate-400">DELIVERY MODE</p><p className="text-xs font-extrabold text-slate-900">{section.deliveryMode}</p></div></div><div className="mt-5 space-y-3">{[["Status", section.deliveryStatus], ["Primary route", section.interfaceRoute], ["Owners", section.ownerRoles.join(", ")], ["Data", section.databaseObjects.join(", ")]].map(([label, value]) => <div className="rounded-xl bg-slate-50 p-3" key={label}><p className="text-[9px] font-bold text-slate-400">{label.toUpperCase()}</p><p className="mt-1 text-[10px] font-semibold leading-5 text-slate-700">{value}</p></div>)}</div></Card><SectionCard title={`${section.features.length} permanent capabilities`} description="This surface is the visible architecture and acceptance map. Planned status does not imply live vendor connectivity."><div className="grid gap-2 p-4 sm:grid-cols-2">{section.features.map((feature) => <div className="flex items-start gap-2 rounded-xl border border-slate-200 p-3" key={feature}><BadgeCheck className="mt-0.5 size-3.5 shrink-0 text-teal-600" /><p className="text-[10px] font-semibold leading-5 text-slate-700">{feature}</p></div>)}</div></SectionCard></div>
  </div>;
}

function Empty({ label }: { label: string }) {
  return <div className="grid min-h-40 place-items-center p-6 text-center"><div><Network className="mx-auto size-6 text-slate-300" /><p className="mt-3 text-xs font-extrabold text-slate-700">{label}</p></div></div>;
}
