import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { BrandMark } from "@/components/clinic/brand-mark";
import { getLegalDocument } from "@/lib/legal/document-registry";

export default function PrivacyPage() {
  const definition = getLegalDocument("privacy_policy");
  if (!definition) throw new Error("Canonical Privacy Policy metadata is unavailable.");

  return <main className="min-h-screen bg-[#f7f8fa] text-slate-950"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex h-20 max-w-5xl items-center px-5 sm:px-8"><Link className="flex items-center gap-3" href="/"><BrandMark /><div><p className="text-sm font-extrabold">Klinikos</p><p className="text-[11px] font-bold uppercase tracking-[.18em] text-[#9a7a1f]">Privacy</p></div></Link><Link className="ml-auto flex items-center gap-2 text-xs font-bold text-slate-600" href="/access"><ArrowLeft className="size-4" /> Access gate</Link></div></header><article className="mx-auto max-w-4xl px-5 py-14 sm:px-8"><p className="text-[11px] font-extrabold uppercase tracking-[.2em] text-[#9a7a1f]">Version {definition.version} · Draft effective date <time dateTime={definition.effectiveDate}>{definition.effectiveDate}</time></p><h1 className="mt-3 text-4xl font-extrabold tracking-[-.05em] sm:text-5xl">{definition.title}</h1><p className="mt-6 text-sm leading-7 text-slate-600">This notice explains the product-facing privacy expectations for Klinikos evaluation access. It is not a substitute for a final jurisdiction-specific privacy policy or production HIPAA privacy documentation.</p><div className="mt-10 divide-y divide-slate-200 border-y border-slate-200">{[
["Information we collect", "Evaluation and qualification flows may collect contact information such as name, work email, organization details, submitted business-system information, and technical request metadata used for security, abuse prevention, auditability and service operation."],
["How we use it", "Klinikos may use submitted information to provide requested access, qualify clinics or providers, operate and secure the service, improve product workflows, communicate about requested services, maintain acceptance records, and meet legal or operational obligations."],
["Healthcare information", "Do not enter real patient information or protected health information into demo or evaluation environments unless Klinikos has expressly confirmed an approved production environment and the required agreements and controls are in place."],
["Sharing", "Klinikos should limit sharing to service providers and professional partners necessary to operate, secure, support or provide the service, subject to applicable contractual and legal requirements. Production healthcare vendors require separate review where PHI may be involved."],
["Retention and security", "Information should be retained only as needed for legitimate product, security, contractual and legal purposes and protected using appropriate technical and organizational controls. Production retention and deletion rules may differ by customer and regulatory context."],
["Choices", "You may choose not to submit optional information. Certain access, qualification, security or contractual information may be required to use protected product surfaces or production services."],
].map(([title, body]) => <section className="py-7" key={title}><h2 className="text-lg font-extrabold tracking-[-.025em]">{title}</h2><p className="mt-3 text-sm leading-7 text-slate-600">{body}</p></section>)}</div><p className="mt-8 text-xs leading-6 text-slate-500">Before public commercial launch, this notice should be reviewed and expanded by counsel for applicable state, federal and international privacy requirements.</p></article></main>;
}
