import Link from "next/link";
import { ArrowRight, BriefcaseMedical, ClipboardCheck, FileWarning, ListChecks, PlugZap } from "lucide-react";
import { CaseCreateAction } from "@/components/clinic/case-actions";
import { PageIntro, Progress, SectionCard, StatCard, StatusBadge } from "@/components/clinic/workspace-kit";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import type { CaseWorkspace as CaseWorkspaceData } from "@/lib/repositories/case-repository";

function formatDate(value: string | null) {
  return value ? new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric", timeZone: "UTC" }).format(new Date(value)) : "Not set";
}

export function CasesWorkspace({ workspace, canCreate }: { workspace: CaseWorkspaceData; canCreate: boolean }) {
  return <div className="space-y-6">
    <PageIntro title="Case rooms for every injury claim." description="Coordinate no-fault and workers compensation facts, tasks, documents, forms, packet readiness, and audited manual delivery without pretending an external carrier connection exists." action={<CaseCreateAction enabled={canCreate} patients={workspace.patients} />} />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard accent="sky" detail="Tenant-scoped rooms" icon={<BriefcaseMedical className="size-4" />} label="Active cases" value={String(workspace.metrics.activeCases)} /><StatCard accent="amber" detail="Due within seven days" icon={<FileWarning className="size-4" />} label="Narratives due" value={String(workspace.metrics.narrativesDue)} /><StatCard accent="rose" detail="Human resolution required" icon={<ClipboardCheck className="size-4" />} label="Disputed / denied" value={String(workspace.metrics.disputedCases)} /><StatCard accent="teal" detail="Across every case room" icon={<ListChecks className="size-4" />} label="Open case tasks" value={String(workspace.metrics.openTasks)} /></div>
    <div className="grid gap-6 xl:grid-cols-[1fr_300px]">
      <SectionCard title="Case portfolio" description="Every number below comes from the current organization’s PostgreSQL records."><div className="divide-y divide-slate-100">{workspace.cases.map((item) => <article className="p-5" key={`${item.caseType}:${item.id}`}><div className="flex flex-wrap items-start gap-4"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-black text-slate-950">{item.patientName}</p><Badge tone={item.caseType === "nofault" ? "sky" : "violet"}>{item.caseLabel}</Badge><StatusBadge status={item.status} /></div><p className="mt-1 text-[12px] text-slate-400">{item.patientMrn} · Claim {item.claimNumber} · Accident {formatDate(item.accidentDate)}</p></div><Button asChild size="sm" variant="secondary"><Link href={`/cases/${item.caseType}/${item.id}`}>Open room <ArrowRight className="size-3.5" /></Link></Button></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-slate-50 p-3"><p className="text-[11px] font-black uppercase tracking-[.12em] text-slate-400">Carrier</p><p className="mt-2 text-xs font-bold text-slate-800">{item.carrier}</p><p className="mt-1 text-[11px] text-slate-500">{item.authorizationStatus ?? "Authorization not recorded"}</p></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-[11px] font-black uppercase tracking-[.12em] text-slate-400">Follow-through</p><p className="mt-2 text-xs font-bold text-slate-800">{item.openTaskCount} open tasks</p><p className="mt-1 text-[11px] text-slate-500">{item.documentCount} linked documents · {item.packetCount} packets</p></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-[11px] font-black uppercase tracking-[.12em] text-slate-400">Narrative due</p><p className="mt-2 text-xs font-bold text-slate-800">{formatDate(item.narrativeDueAt)}</p><p className="mt-1 text-[11px] text-slate-500">{item.denialStatus ?? "No denial recorded"}</p></div></div><div className="mt-4 flex items-center gap-3"><p className="text-[11px] font-black uppercase tracking-[.12em] text-slate-400">Best packet readiness</p><div className="flex-1"><Progress tone={item.packetReadiness === 100 ? "teal" : item.packetReadiness >= 60 ? "amber" : "rose"} value={item.packetReadiness} /></div><p className="text-[12px] font-black text-slate-700">{item.packetReadiness}%</p></div></article>)}{!workspace.cases.length && <div className="p-10 text-center"><BriefcaseMedical className="mx-auto size-8 text-slate-300" /><p className="mt-3 text-xs font-bold text-slate-700">No case rooms exist in this organization yet.</p><p className="mt-1 text-[12px] text-slate-400">Create one to start a governed manual workflow.</p></div>}</div></SectionCard>
      <div className="space-y-5"><Card className="border-amber-200 bg-amber-50 p-5"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-white text-amber-700"><PlugZap className="size-5" /></span><div><p className="text-xs font-black text-slate-950">{workspace.connection.status}</p><p className="mt-1 text-[12px] text-slate-500">Carrier, attorney, government-form, and clearinghouse adapters</p></div></div><p className="mt-4 text-[12px] leading-5 text-slate-600">ClinicOS provides a complete manual checklist and audited PDF fallback now. Electronic transmission stays disabled until credentials, contracts, BAAs where applicable, and interface testing are complete.</p></Card><Card className="bg-slate-950 p-5 text-white"><p className="text-[11px] font-black uppercase tracking-[.16em] text-teal-300">Case safety</p><p className="mt-3 text-lg font-black tracking-[-.03em]">No legal outcome prediction.</p><p className="mt-2 text-[12px] leading-5 text-slate-300">Readiness means required evidence was checked by staff. It never guarantees carrier acceptance, payment, eligibility, or legal recovery.</p></Card></div>
    </div>
  </div>;
}
