import Link from "next/link";
import { ArrowLeft, BriefcaseMedical, CalendarClock, CircleDollarSign, FileCheck2, Files, History, Landmark, ListChecks, Mail, MapPin, Phone, PlugZap, ShieldAlert, UserRound, WalletCards } from "lucide-react";
import { CasePacketActions, CasePacketCreateAction, CaseTaskCreateAction, CaseTaskTransitionAction, CaseUpdateAction } from "@/components/clinic/case-actions";
import { PageIntro, Progress, SectionCard, StatCard, StatusBadge } from "@/components/clinic/workspace-kit";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import type { CaseRoom as CaseRoomData } from "@/lib/repositories/case-repository";
import { formatCurrency } from "@/lib/utils";

function formatDate(value: string | null, withTime = false) {
  if (!value) return "Not recorded";
  return new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric", ...(withTime ? { hour: "numeric", minute: "2-digit" } : {}), timeZone: "UTC" }).format(new Date(value));
}

function titleCase(value: string) {
  return value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
}

function ContactCard({ title, contact }: { title: string; contact: CaseRoomData["case"]["adjuster"] }) {
  return <div className="rounded-2xl border border-slate-100 bg-slate-50 p-4"><p className="text-[9px] font-black uppercase tracking-[.14em] text-slate-400">{title}</p>{contact ? <div className="mt-3 space-y-2"><p className="text-xs font-black text-slate-900">{contact.name}</p>{contact.organization && <p className="flex items-center gap-2 text-[10px] text-slate-500"><MapPin className="size-3" /> {contact.organization}</p>}{contact.phone && <p className="flex items-center gap-2 text-[10px] text-slate-500"><Phone className="size-3" /> {contact.phone}</p>}{contact.email && <p className="flex items-center gap-2 text-[10px] text-slate-500"><Mail className="size-3" /> {contact.email}</p>}</div> : <p className="mt-3 text-[10px] text-slate-400">Not recorded</p>}</div>;
}

export function CaseRoom({ room, canUpdate, canManage }: { room: CaseRoomData; canUpdate: boolean; canManage: boolean }) {
  const item = room.case;
  const openTasks = room.tasks.filter((task) => task.status === "open").length;
  const generatedPackets = room.packets.filter((packet) => ["generated_manual", "approved"].includes(packet.status)).length;
  const paidCents = room.financial.payments.filter((payment) => payment.status === "posted" || payment.status === "paid").reduce((sum, payment) => sum + payment.amountCents, 0);
  return <div className="space-y-6">
    <Button asChild size="sm" variant="ghost"><Link href="/cases"><ArrowLeft className="size-4" /> Back to case portfolio</Link></Button>
    <PageIntro title={`${item.patientName} · ${item.caseLabel}`} description={`Claim ${item.claimNumber} with ${item.carrier}. This room is isolated to ${item.patientMrn} and the authenticated organization.`} aside={<><Badge tone={item.caseType === "nofault" ? "sky" : "violet"}>{item.caseLabel}</Badge><StatusBadge status={item.status} /></>} />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard accent="sky" detail={`Accident ${formatDate(item.accidentDate)}`} icon={<BriefcaseMedical className="size-4" />} label="Claim" value={item.claimNumber} /><StatCard accent={openTasks ? "amber" : "teal"} detail="Human-owned follow-through" icon={<ListChecks className="size-4" />} label="Open tasks" value={String(openTasks)} /><StatCard accent={item.packetReadiness === 100 ? "teal" : "rose"} detail={`${generatedPackets} generated or approved`} icon={<FileCheck2 className="size-4" />} label="Best packet readiness" value={`${item.packetReadiness}%`} /><StatCard accent="violet" detail="Case-linked evidence only" icon={<Files className="size-4" />} label="Documents" value={String(room.documents.length)} /></div>

    <div className="grid gap-6 xl:grid-cols-[1fr_340px]">
      <div className="space-y-6">
        <SectionCard title="Case facts" description="Structured facts persist in PostgreSQL; corrections create audit history."><div className="grid gap-4 p-5 sm:grid-cols-2 xl:grid-cols-3">{[
          ["Accident date", formatDate(item.accidentDate)], ["Carrier", item.carrier], ["Policy", item.policyNumber ?? "Not recorded"], ["Body parts", item.injuredBodyParts.join(", ")], ["Diagnosis codes", item.diagnosisCodes.join(", ") || "Not recorded"], ["Authorization", item.authorizationStatus ?? "Not recorded"], ["IME", item.imeStatus ?? "Not recorded"], [item.caseType === "nofault" ? "NF-2 / NF-3" : "C-4 status", item.caseType === "nofault" ? `${item.formStatus.nf2 ?? "Not recorded"} / ${item.formStatus.nf3 ?? "Not recorded"}` : item.formStatus.c4 ?? "Not recorded"], ["Narrative due", formatDate(item.narrativeDueAt)], ["Denial", item.denialStatus ?? "None recorded"], ["Appeal", item.appealStatus ?? "None recorded"], ["Packet state", titleCase(item.packetStatus)],
        ].map(([label, value]) => <div className="rounded-2xl bg-slate-50 p-4" key={label}><p className="text-[9px] font-black uppercase tracking-[.12em] text-slate-400">{label}</p><p className="mt-2 text-xs font-bold leading-5 text-slate-800">{value}</p></div>)}</div>{item.treatmentPlan && <div className="border-t border-slate-100 p-5"><p className="text-[9px] font-black uppercase tracking-[.12em] text-slate-400">Treatment plan summary</p><p className="mt-2 text-xs leading-6 text-slate-600">{item.treatmentPlan}</p></div>}{item.caseType === "workers_comp" && <div className="grid gap-3 border-t border-slate-100 p-5 sm:grid-cols-2"><div><p className="text-[9px] font-black text-slate-400">WORK STATUS</p><p className="mt-2 text-xs font-bold text-slate-800">{item.workStatus ?? "Not recorded"}</p></div><div><p className="text-[9px] font-black text-slate-400">RETURN TO WORK</p><p className="mt-2 text-xs font-bold text-slate-800">{item.returnToWorkStatus ?? "Not recorded"}</p></div></div>}</SectionCard>

        <SectionCard title="Case contacts" description="Contact details are case-specific and never shared across tenants."><div className="grid gap-4 p-5 sm:grid-cols-3"><ContactCard contact={item.adjuster} title="Adjuster" /><ContactCard contact={item.attorney} title="Attorney" /><ContactCard contact={item.employer} title="Employer" /></div></SectionCard>

        <SectionCard title="Case task room" description="Completion, cancellation, and reopening are human actions with audit evidence."><div className="divide-y divide-slate-100">{room.tasks.map((task) => <article className="p-5" key={task.id}><div className="flex flex-wrap items-start gap-3"><span className={`grid size-10 place-items-center rounded-xl ${task.priority === "urgent" ? "bg-rose-50 text-rose-700" : task.priority === "high" ? "bg-amber-50 text-amber-700" : "bg-slate-100 text-slate-600"}`}><ListChecks className="size-4" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="text-xs font-black text-slate-900">{task.title}</p><StatusBadge status={task.status} /><Badge tone={task.priority === "urgent" ? "rose" : task.priority === "high" ? "amber" : "slate"}>{task.priority}</Badge></div><p className="mt-1 text-[10px] text-slate-400">{task.ownerName} · due {formatDate(task.dueAt)}</p>{task.details && <p className="mt-3 whitespace-pre-line text-[10px] leading-5 text-slate-600">{task.details}</p>}<CaseTaskTransitionAction enabled={canUpdate} room={room} task={task} /></div></div></article>)}{!room.tasks.length && <p className="p-6 text-xs text-slate-500">No case tasks are recorded.</p>}</div><CaseTaskCreateAction enabled={canUpdate} room={room} /></SectionCard>

        <SectionCard action={<CasePacketCreateAction enabled={canUpdate} room={room} />} title="Packet builder" description="Required-item readiness, human approval, and a manual PDF fallback. No electronic submission occurs."><div className="divide-y divide-slate-100">{room.packets.map((packet) => <article className="p-5" key={packet.id}><div className="flex flex-wrap items-start gap-3"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="text-xs font-black text-slate-900">{titleCase(packet.type)}</p><StatusBadge status={titleCase(packet.status)} /></div><p className="mt-1 text-[9px] text-slate-400">{packet.id} · created {formatDate(packet.createdAt)}</p></div><p className="text-lg font-black text-slate-950">{packet.readiness}%</p></div><div className="mt-3"><Progress tone={packet.readiness === 100 ? "teal" : packet.readiness >= 60 ? "amber" : "rose"} value={packet.readiness} /></div><p className="mt-2 text-[9px] text-slate-400">{packet.checklist.filter((entry) => entry.complete).length} of {packet.checklist.length} checklist items reviewed · required readiness only</p><CasePacketActions enabled={canUpdate} packet={packet} room={room} /></article>)}{!room.packets.length && <p className="p-6 text-xs text-slate-500">No packets have been created.</p>}</div></SectionCard>

        <SectionCard action={<Button asChild size="sm" variant="secondary"><Link href="/documents"><Files className="size-3.5" /> Open documents</Link></Button>} title="Case document ledger" description="Upload through the governed Documents workspace and select this case; the link is persisted automatically."><div className="divide-y divide-slate-100">{room.documents.map((document) => <div className="grid gap-3 p-5 sm:grid-cols-[1fr_auto] sm:items-center" key={document.id}><div><div className="flex flex-wrap items-center gap-2"><p className="text-xs font-black text-slate-900">{document.name}</p><StatusBadge status={document.status} /><StatusBadge status={document.reviewStatus} /></div><p className="mt-1 text-[9px] text-slate-400">{document.originalFileName} · {document.requirementKey ?? "Unassigned requirement"} · {formatDate(document.createdAt)}</p></div><Badge tone={document.linkStatus === "attached" ? "teal" : "slate"}>{document.linkStatus}</Badge></div>)}{!room.documents.length && <div className="p-8 text-center"><ShieldAlert className="mx-auto size-7 text-amber-500" /><p className="mt-3 text-xs font-bold text-slate-800">No case evidence is attached.</p><p className="mt-1 text-[10px] text-slate-400">Packet readiness should remain incomplete until staff reviews the required evidence.</p></div>}</div></SectionCard>

        <SectionCard title="Patient-level revenue context" description={room.financial.notice}><div className="grid gap-4 p-5 sm:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-4"><CircleDollarSign className="size-4 text-teal-700" /><p className="mt-3 text-xl font-black text-slate-950">{formatCurrency(paidCents / 100)}</p><p className="mt-1 text-[9px] text-slate-400">Posted patient payments</p></div><div className="rounded-2xl bg-slate-50 p-4"><WalletCards className="size-4 text-violet-700" /><p className="mt-3 text-xl font-black text-slate-950">{formatCurrency(room.financial.balanceCents / 100)}</p><p className="mt-1 text-[9px] text-slate-400">Latest patient balance</p></div><div className="rounded-2xl bg-slate-50 p-4"><Landmark className="size-4 text-sky-700" /><p className="mt-3 text-xl font-black text-slate-950">{room.financial.claims.length}</p><p className="mt-1 text-[9px] text-slate-400">Patient claims in this tenant</p></div></div><div className="border-t border-amber-200 bg-amber-50 p-4 text-[10px] leading-5 text-amber-900">These values are deliberately not called case revenue or case profitability. The current billing schema has not attributed them to this case; that allocation belongs to the claim-readiness slice and requires human review.</div></SectionCard>

        <SectionCard title="Case audit timeline" description="Access, updates, task actions, checklist decisions, packet generation, approval, and export are recorded here."><div className="space-y-2 p-4">{room.timeline.map((event) => <div className="flex gap-3 rounded-2xl bg-slate-50 p-4" key={event.id}><span className="grid size-8 shrink-0 place-items-center rounded-xl bg-white text-slate-600"><History className="size-3.5" /></span><div><p className="text-[10px] font-black text-slate-900">{titleCase(event.action.replace("case.", ""))}</p><p className="mt-1 text-[9px] text-slate-400">{formatDate(event.createdAt, true)} · {event.actorId ?? "system"}</p></div></div>)}{!room.timeline.length && <p className="p-4 text-xs text-slate-500">No case events are recorded.</p>}</div></SectionCard>
      </div>

      <aside className="space-y-5">
        <SectionCard title="Patient identity"><div className="p-5"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-2xl bg-sky-50 text-sky-700"><UserRound className="size-5" /></span><div><p className="text-sm font-black text-slate-950">{room.patient.preferredName ?? item.patientName}</p><p className="mt-1 text-[9px] text-slate-400">{room.patient.mrn} · DOB {formatDate(room.patient.dateOfBirth)}</p></div></div><div className="mt-4 space-y-2 text-[10px] text-slate-500">{room.patient.phone && <p className="flex items-center gap-2"><Phone className="size-3" /> {room.patient.phone}</p>}{room.patient.email && <p className="flex items-center gap-2"><Mail className="size-3" /> {room.patient.email}</p>}</div><Button asChild className="mt-4 w-full" size="sm" variant="secondary"><Link href={`/patients/${room.patient.id}`}>Open patient chart</Link></Button></div></SectionCard>
        <SectionCard title="Reviewed status update" description="A note is required for every change."><div className="p-4"><CaseUpdateAction enabled={canUpdate} room={room} /></div></SectionCard>
        <Card className="border-amber-200 bg-amber-50 p-5"><div className="flex items-center gap-3"><PlugZap className="size-5 text-amber-700" /><div><p className="text-xs font-black text-slate-950">{room.connection.status}</p><p className="mt-1 text-[9px] text-slate-500">Manual fallback active</p></div></div><p className="mt-4 text-[10px] leading-5 text-slate-600">Carrier, attorney, payer, NF form, C-4, and clearinghouse delivery require configured adapters and completed contractual/compliance review.</p></Card>
        <Card className="bg-slate-950 p-5 text-white"><CalendarClock className="size-5 text-teal-300" /><p className="mt-4 text-lg font-black">Human checkpoints stay mandatory.</p><p className="mt-2 text-[10px] leading-5 text-slate-300">ClinicOS can organize, calculate readiness, and prepare a manual artifact. It does not make legal, clinical, eligibility, coverage, or final billing decisions.</p>{canManage && <Badge className="mt-4" tone="teal">Case manager controls enabled</Badge>}</Card>
      </aside>
    </div>
  </div>;
}
