import { CalendarDays, CheckCircle2, ChevronRight, ClipboardCheck, FileCheck2, FileText, HeartPulse, History, LockKeyhole, MessageCircle, ReceiptText, ShieldCheck, Video } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import type { PortalDashboard as PortalDashboardData } from "@/lib/repositories/portal-repository";

function formatMoney(cents: number) { return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(cents / 100); }
function formatDate(value: string | null) { return value ? new Date(value).toLocaleString([], { month: "short", day: "numeric", year: "numeric", hour: "numeric", minute: "2-digit" }) : "Date pending"; }
function statusLabel(value: string) { return value.toLowerCase().replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }

export function PortalDashboard({ data, organizationName }: { data: PortalDashboardData; organizationName: string }) {
  const pendingForms = data.forms.filter((form) => !["completed", "cancelled"].includes(form.status));
  const nextAppointment = [...data.appointments].filter((appointment) => new Date(appointment.startsAt) >= new Date() && !["CANCELLED", "NO_SHOW"].includes(appointment.status)).sort((left, right) => left.startsAt.localeCompare(right.startsAt))[0];
  return <main className="min-h-screen bg-[#f3f0e8] text-[#173c34]">
    <header className="border-b border-[#d8ddd4] bg-[#f8f6f0]/90 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center gap-4 px-5 py-4 sm:px-8"><span className="grid size-11 place-items-center rounded-2xl bg-[#153f37] text-[#e7d182]"><HeartPulse className="size-5" /></span><div><p className="text-xs font-extrabold">{organizationName}</p><p className="text-[11px] font-bold uppercase tracking-[.16em] text-[#748b83]">Private patient portal</p></div><div className="ml-auto flex items-center gap-3"><Badge tone="teal"><LockKeyhole className="mr-1 size-3" /> Patient-only session</Badge><form action="/api/portal/auth/logout" method="post"><Button size="sm" type="submit" variant="secondary">Sign out</Button></form></div></div></header>
    <div className="mx-auto max-w-7xl px-5 py-8 sm:px-8 sm:py-12">
      <section className="relative overflow-hidden rounded-[36px] bg-[#153f37] p-7 text-white shadow-[0_24px_70px_rgba(21,63,55,.18)] sm:p-10"><div className="absolute -right-16 -top-20 size-72 rounded-full border border-[#e7d182]/30" /><div className="absolute -right-4 -top-4 size-44 rounded-full border border-[#a8d8c6]/30" /><p className="text-[12px] font-extrabold uppercase tracking-[.2em] text-[#a8d8c6]">Welcome back</p><h1 className="mt-4 max-w-2xl font-serif text-4xl font-semibold leading-none tracking-[-.045em] sm:text-6xl">{data.patient.displayName}, your next step is clear.</h1><p className="mt-5 max-w-2xl text-sm leading-7 text-[#c7dbd4]">Only records explicitly released by your care team appear here. Clinical drafts and internal files stay inside the clinic workspace.</p><div className="mt-7 flex flex-wrap gap-2"><Badge tone="amber">MRN {data.patient.mrn}</Badge><Badge tone="teal">Preferred language: {data.patient.preferredLanguage}</Badge></div></section>
      <section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <PortalStat icon={<CalendarDays className="size-5" />} label="Next appointment" value={nextAppointment ? formatDate(nextAppointment.startsAt) : "No visit scheduled"} />
        <PortalStat icon={<ClipboardCheck className="size-5" />} label="Forms to finish" value={String(pendingForms.length)} />
        <PortalStat icon={<FileCheck2 className="size-5" />} label="Released records" value={String(data.records.length)} />
        <PortalStat icon={<ReceiptText className="size-5" />} label="Current balance" value={formatMoney(data.financial.balanceCents)} />
      </section>
      <section className="mt-8 grid gap-6 xl:grid-cols-[1.05fr_.95fr]">
        <div className="space-y-6">
          <PortalPanel icon={<CalendarDays className="size-4" />} title="Appointments" subtitle="Your clinic schedule, not a generic calendar.">{data.appointments.length ? data.appointments.map((appointment) => <div className="flex flex-wrap items-center gap-4 border-t border-[#e7e7df] px-5 py-4 first:border-0" key={appointment.id}><span className="grid size-10 place-items-center rounded-2xl bg-[#dceee7] text-[#276c5e]">{appointment.telemedicine ? <Video className="size-4" /> : <CalendarDays className="size-4" />}</span><div className="min-w-0 flex-1"><p className="text-xs font-extrabold text-[#173c34]">{appointment.type}</p><p className="mt-1 text-[12px] text-[#72867f]">{formatDate(appointment.startsAt)} · {appointment.provider}</p></div><Badge tone={appointment.status === "COMPLETED" ? "teal" : "sky"}>{statusLabel(appointment.status)}</Badge></div>) : <PortalEmpty text="No appointments are available." />}</PortalPanel>
          <PortalPanel icon={<FileText className="size-4" />} title="Released records" subtitle="Every item below has an explicit clinic release decision.">{data.records.length ? data.records.map((record) => <article className="border-t border-[#e7e7df] px-5 py-4 first:border-0" key={`${record.kind}-${record.id}`}><div className="flex items-start gap-4"><span className="grid size-10 shrink-0 place-items-center rounded-2xl bg-[#f1e7c6] text-[#7a6320]"><FileCheck2 className="size-4" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="text-xs font-extrabold text-[#173c34]">{record.title}</p><Badge tone="slate">{record.kind}</Badge></div><p className="mt-2 line-clamp-3 text-[12px] leading-5 text-[#657b73]">{record.detail}</p><p className="mt-2 text-[11px] font-bold text-[#8a9a94]">Released {formatDate(record.releasedAt)}</p></div></div></article>) : <PortalEmpty text="Your clinic has not released any records yet." />}</PortalPanel>
        </div>
        <div className="space-y-6">
          <PortalPanel icon={<ClipboardCheck className="size-4" />} title="Forms" subtitle="Assignments stay bound to your patient identity.">{data.forms.length ? data.forms.map((form) => <div className="flex items-center gap-3 border-t border-[#e7e7df] px-5 py-4 first:border-0" key={form.id}><span className="grid size-9 place-items-center rounded-xl bg-[#dceee7] text-[#276c5e]">{form.status === "completed" ? <CheckCircle2 className="size-4" /> : <ClipboardCheck className="size-4" />}</span><div className="flex-1"><p className="text-xs font-extrabold">Patient form</p><p className="mt-1 text-[11px] text-[#748b83]">{form.dueAt ? `Due ${formatDate(form.dueAt)}` : "No due date"}</p></div><Badge tone={form.status === "completed" ? "teal" : "amber"}>{statusLabel(form.status)}</Badge></div>) : <PortalEmpty text="No forms are assigned." />}</PortalPanel>
          <PortalPanel icon={<ReceiptText className="size-4" />} title="Billing" subtitle="Amounts are shown without placing health details in payment descriptions."><div className="p-5"><p className="text-[12px] font-bold uppercase tracking-[.14em] text-[#7b8e87]">Balance due</p><p className="mt-2 font-serif text-4xl font-semibold text-[#173c34]">{formatMoney(data.financial.balanceCents)}</p><p className="mt-2 text-[11px] text-[#879791]">As of {formatDate(data.financial.asOf)}</p></div>{data.financial.invoices.map((invoice) => <div className="flex items-center gap-3 border-t border-[#e7e7df] px-5 py-4" key={invoice.id}><div className="flex-1"><p className="text-xs font-extrabold">Statement {invoice.number}</p><p className="mt-1 text-[11px] text-[#748b83]">{formatMoney(invoice.balanceCents)} remaining · due {formatDate(invoice.dueAt)}</p></div><Badge tone="sky">{statusLabel(invoice.status)}</Badge></div>)}</PortalPanel>
          <PortalPanel icon={<History className="size-4" />} title="Access history" subtitle="You can see when your portal identity accessed this record.">{data.accessHistory.slice(0, 8).map((event) => <div className="flex items-center gap-3 border-t border-[#e7e7df] px-5 py-3 first:border-0" key={event.id}><ShieldCheck className="size-4 text-[#3b7c6e]" /><div className="flex-1"><p className="text-[12px] font-extrabold">{statusLabel(event.action.replace("portal.", ""))}</p><p className="mt-1 text-[11px] text-[#81928c]">{formatDate(event.createdAt)}</p></div></div>)}</PortalPanel>
          <div className="rounded-[28px] bg-[#ede3bf] p-6"><div className="flex items-start gap-4"><MessageCircle className="mt-1 size-5 text-[#715c1c]" /><div><p className="text-sm font-extrabold text-[#493f20]">Need help from the office?</p><p className="mt-2 text-[12px] leading-5 text-[#74642c]">Secure messaging and refill/referral requests are the next portal workflow slice. For urgent symptoms, call 911 or go to the nearest emergency room.</p></div><ChevronRight className="ml-auto size-4 text-[#8d7a38]" /></div></div>
        </div>
      </section>
    </div>
  </main>;
}

function PortalStat({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="rounded-[24px] border border-[#dce1d8] bg-[#faf9f5] p-5"><span className="grid size-10 place-items-center rounded-2xl bg-[#dceee7] text-[#276c5e]">{icon}</span><p className="mt-5 text-[11px] font-extrabold uppercase tracking-[.14em] text-[#748b83]">{label}</p><p className="mt-2 text-sm font-extrabold text-[#173c34]">{value}</p></div>; }
function PortalPanel({ children, icon, subtitle, title }: { children: React.ReactNode; icon: React.ReactNode; subtitle: string; title: string }) { return <section className="overflow-hidden rounded-[28px] border border-[#dce1d8] bg-[#faf9f5]"><div className="flex items-start gap-3 border-b border-[#e7e7df] p-5"><span className="grid size-9 place-items-center rounded-xl bg-[#153f37] text-[#e7d182]">{icon}</span><div><h2 className="text-sm font-extrabold text-[#173c34]">{title}</h2><p className="mt-1 text-[12px] leading-5 text-[#748b83]">{subtitle}</p></div></div>{children}</section>; }
function PortalEmpty({ text }: { text: string }) { return <p className="p-5 text-xs text-[#748b83]">{text}</p>; }
