import Link from "next/link";
import { ArrowRight, Check, ShieldCheck } from "lucide-react";
import { BrandMark } from "@/components/clinic/brand-mark";
import { clinicCommercialOffers, clinicPlans, commercialAddOns, KLINIKOS_GODADDY_PAYLINK } from "@/lib/commercial/klinikos-commercial";

export const metadata = { title: "Pricing — Klinikos", description: "Klinikos clinic operating system pricing, implementation, and expansion options." };

const plans = Object.values(clinicPlans);
const addOns = Object.values(commercialAddOns);

export default function PricingPage() {
  return <main className="min-h-screen bg-[#f7f8fa] text-[#0b1220]">
    <header className="border-b border-[#e2e6ea] bg-white"><div className="mx-auto flex h-20 max-w-[1400px] items-center px-5 sm:px-8"><Link href="/" className="flex items-center gap-3"><BrandMark/><span className="text-sm font-black">Klinikos</span></Link><Link href="/founding-clinic" className="ml-auto text-xs font-extrabold text-[#174ea6]">See if your clinic qualifies <ArrowRight className="ml-1 inline size-3.5"/></Link></div></header>

    <section className="border-b border-[#dfe3e8] bg-white"><div className="mx-auto max-w-[1400px] px-5 py-16 sm:px-8 lg:py-20"><p className="text-[10px] font-extrabold uppercase tracking-[.2em] text-[#174ea6]">Commercial model</p><h1 className="mt-4 max-w-5xl text-5xl font-black leading-[.95] tracking-[-.06em] sm:text-6xl">Start with the operation. Expand with the value.</h1><p className="mt-6 max-w-3xl text-sm leading-7 text-[#5b6675]">Klinikos combines implementation with recurring operating software. Variable external usage is customer-funded rather than hidden inside an unlimited promise. Final scope can vary by locations, providers, migration, integrations, volume, and governed workflows.</p></div></section>

    <section className="mx-auto max-w-[1400px] px-5 py-12 sm:px-8"><div className="grid gap-4 xl:grid-cols-4">{plans.map(plan => <article key={plan.key} className="flex flex-col border border-[#dfe3e8] bg-white p-6"><p className="text-[10px] font-extrabold uppercase tracking-[.16em] text-[#174ea6]">{plan.name}</p><p className="mt-4 text-3xl font-black tracking-[-.04em]">{plan.monthlyPriceLabel}</p><p className="mt-1 text-[11px] text-[#6c7684]">{plan.annualPriceLabel} · {plan.annualSavingsLabel}</p><p className="mt-4 text-[12px] leading-6 text-[#5b6675]">{plan.idealFor}</p><p className="mt-5 border-y border-[#edf0f2] py-3 text-xs font-extrabold">Implementation {plan.implementationPriceLabel}</p><ul className="mt-5 space-y-3">{plan.includes.map(item => <li key={item} className="flex gap-2 text-[12px] leading-5 text-[#45505f]"><Check className="mt-0.5 size-3.5 shrink-0 text-[#174ea6]"/>{item}</li>)}</ul><Link href="/founding-clinic" className="mt-auto pt-7 text-xs font-extrabold text-[#174ea6]">Qualify this plan <ArrowRight className="ml-1 inline size-3.5"/></Link></article>)}</div></section>

    <section className="border-y border-[#dfe3e8] bg-white"><div className="mx-auto grid max-w-[1400px] gap-6 px-5 py-12 sm:px-8 lg:grid-cols-3"><div><p className="text-[10px] font-extrabold uppercase tracking-[.16em] text-[#174ea6]">Step 1</p><h2 className="mt-2 text-xl font-black">{clinicCommercialOffers.privateWorkflowReview.name}</h2><p className="mt-2 text-3xl font-black">{clinicCommercialOffers.privateWorkflowReview.priceLabel}</p><p className="mt-3 text-[12px] leading-6 text-[#5b6675]">Map the current operation, fragmentation, spend, leakage, and best Klinikos configuration. {clinicCommercialOffers.privateWorkflowReview.creditForward}</p><a href={KLINIKOS_GODADDY_PAYLINK} target="_blank" rel="noreferrer" className="mt-5 inline-flex min-h-11 items-center bg-[#174ea6] px-5 text-xs font-extrabold text-white">Start analysis <ArrowRight className="ml-2 size-4"/></a></div><div><p className="text-[10px] font-extrabold uppercase tracking-[.16em] text-[#174ea6]">Step 2</p><h2 className="mt-2 text-xl font-black">{clinicCommercialOffers.foundingEvaluation.name}</h2><p className="mt-2 text-3xl font-black">{clinicCommercialOffers.foundingEvaluation.priceLabel}</p><p className="mt-3 text-[12px] leading-6 text-[#5b6675]">Migration, integration, role, workflow, automation, and deployment blueprint. {clinicCommercialOffers.foundingEvaluation.creditForward}</p></div><div><p className="text-[10px] font-extrabold uppercase tracking-[.16em] text-[#174ea6]">Step 3</p><h2 className="mt-2 text-xl font-black">{clinicCommercialOffers.foundingImplementation.name}</h2><p className="mt-2 text-3xl font-black">{clinicCommercialOffers.foundingImplementation.priceLabel}</p><p className="mt-3 text-[12px] leading-6 text-[#5b6675]">Configuration, implementation planning, migration/integration work, operating setup, training, and launch according to approved scope.</p></div></div></section>

    <section className="mx-auto max-w-[1400px] px-5 py-12 sm:px-8"><h2 className="text-2xl font-black tracking-[-.04em]">Expand only where it creates value.</h2><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-5">{addOns.map(addOn => <article key={addOn.name} className="border border-[#dfe3e8] bg-white p-5"><h3 className="text-sm font-black">{addOn.name}</h3><p className="mt-2 text-lg font-black text-[#174ea6]">{addOn.priceLabel}</p>{"setupLabel" in addOn && <p className="mt-1 text-[11px] text-[#6c7684]">{addOn.setupLabel}</p>}{"rule" in addOn && <p className="mt-3 text-[11px] leading-5 text-[#5b6675]">{addOn.rule}</p>}</article>)}</div><div className="mt-8 flex gap-3 border border-[#dfe3e8] bg-white p-5"><ShieldCheck className="size-5 shrink-0 text-[#9a7a1f]"/><p className="text-[12px] leading-6 text-[#5b6675]">Payment activates commercial access only. It never bypasses authentication, tenant boundaries, RBAC, credentialing, privacy, consent, clinical governance, or required human review. Paid integrations remain pending until their external connection is actually ready.</p></div></section>
  </main>;
}
