export type KlinikosCanonLayer = {
  id: string;
  name: string;
  canonAnchors: readonly string[];
  blueprintAnchors: readonly string[];
  owners: readonly string[];
  implementationConsequences: readonly string[];
  evidence: readonly string[];
  moneyPath: readonly string[];
  riskControls: readonly string[];
  kpis: readonly string[];
};

/**
 * Subordinate implementation registry generated from the Master Canon.
 * It is intentionally broad: a missing layer is a governance regression even when
 * that layer is strategically deferred or not yet implemented.
 */
export const klinikosCanonLayers: readonly KlinikosCanonLayer[] = [
  {
    id: "governance-authority",
    name: "Authority, anti-compression, truth and merge-forward",
    canonAnchors: ["ONE KLINIKOS. ONE MASTER CANON. ONE GOVERNING COMPANY + PRODUCT TRUTH.", "ANTI-COMPRESSION AND LIFECYCLE-PRESERVATION LAW"],
    blueprintAnchors: ["AUTHORITY AND ANTI-COMPRESSION CONTRACT", "Canon compression must never erase accepted architecture"],
    owners: ["executive-council", "architecture"],
    implementationConsequences: ["authority-map", "sync-gates", "document-retirement"],
    evidence: ["git-history", "canon-diff", "verification-report"],
    moneyPath: ["reduces-rework", "protects-speed"],
    riskControls: ["no-parallel-authority", "no-silent-deletion"],
    kpis: ["authority-conflicts", "canon-drift-failures"],
  },
  {
    id: "five-planes",
    name: "Five-plane ecosystem architecture",
    canonAnchors: ["PLANE A — HEALTHCARE UNIVERSE", "PLANE B — ECONOMIC & RESOURCE UNIVERSE", "PLANE C — LIFECYCLE / JOURNEY UNIVERSE", "PLANE D — KLINIKOS OPERATING INFRASTRUCTURE", "PLANE E — COMPANY COMPOUNDING SYSTEM"],
    blueprintAnchors: ["PLANE A — HEALTHCARE UNIVERSE", "PLANE B — ECONOMIC & RESOURCE UNIVERSE", "PLANE C — LIFECYCLE / JOURNEY UNIVERSE", "PLANE D — KLINIKOS OPERATING INFRASTRUCTURE", "PLANE E — COMPANY COMPOUNDING SYSTEM"],
    owners: ["architecture", "product"],
    implementationConsequences: ["ecosystem-graph", "generated-views", "domain-contracts"],
    evidence: ["graph-tests", "route-tests"],
    moneyPath: ["cross-sell", "network-effects"],
    riskControls: ["no-module-silos"],
    kpis: ["cross-engine-journeys", "connected-node-coverage"],
  },
  {
    id: "healthcare-universe",
    name: "Actors, organizations, rails, assets and sectors",
    canonAnchors: ["HEALTHCARE UNIVERSE TAXONOMY", "NOW / NEXT / LATER / PARTNER / CONNECT / INTERNALIZE / NEVER_BUILD"],
    blueprintAnchors: ["HEALTHCARE UNIVERSE TAXONOMY", "sector strategy state"],
    owners: ["product", "partnerships"],
    implementationConsequences: ["actor-registry", "organization-types", "sector-policy"],
    evidence: ["schema-coverage", "integration-register"],
    moneyPath: ["market-expansion", "enterprise-contracts"],
    riskControls: ["scope-classification", "regulated-boundaries"],
    kpis: ["sector-coverage", "activated-sectors"],
  },
  {
    id: "resource-universe-grid",
    name: "Universal economic/resource universe and Grid",
    canonAnchors: ["ECONOMIC & RESOURCE UNIVERSE", "I NEED / I HAVE", "UNIVERSAL GRID TRANSACTION LIFECYCLE"],
    blueprintAnchors: ["ECONOMIC & RESOURCE UNIVERSE", "I NEED / I HAVE", "UNIVERSAL GRID TRANSACTION LIFECYCLE"],
    owners: ["grid", "financial-os"],
    implementationConsequences: ["resource-kernel", "demand-kernel", "eligibility-engine", "transaction-state-machine"],
    evidence: ["grid-tests", "transaction-evidence"],
    moneyPath: ["subscriptions", "lawful-transaction-economics", "organization-tools"],
    riskControls: ["eligibility-before-ranking", "marketplace-safety", "regulated-fee-gates"],
    kpis: ["liquidity", "match-rate", "time-to-fill", "fulfillment-rate"],
  },
  {
    id: "lifecycle-grammar",
    name: "Universal composable lifecycle grammar",
    canonAnchors: ["CANONICAL LIFECYCLE GRAMMAR", "DISCOVER → IDENTIFY → EXPRESS INTENT"],
    blueprintAnchors: ["CANONICAL LIFECYCLE GRAMMAR", "DISCOVER → IDENTIFY → EXPRESS INTENT"],
    owners: ["product", "architecture"],
    implementationConsequences: ["route-registry", "state-machines", "unfinished-work"],
    evidence: ["end-to-end-tests", "route-coverage"],
    moneyPath: ["conversion", "retention"],
    riskControls: ["no-happy-path-only-design"],
    kpis: ["journey-completion", "dropoff-by-state"],
  },
  {
    id: "identity-trust-authority",
    name: "Identity, claims, verification, relationships and authority",
    canonAnchors: ["IDENTITY → CLAIM → EVIDENCE → VERIFICATION → RELATIONSHIP → ELIGIBILITY → ENTITLEMENT → AUTHORITY", "Payment does not create authority"],
    blueprintAnchors: ["IDENTITY → CLAIM → EVIDENCE → VERIFICATION → RELATIONSHIP → ELIGIBILITY → ENTITLEMENT → AUTHORITY", "context switch is a security event"],
    owners: ["identity-trust", "security"],
    implementationConsequences: ["person-graph", "claim-model", "verification-model", "authority-engine"],
    evidence: ["negative-authorization-tests", "audit-events"],
    moneyPath: ["trusted-marketplace", "enterprise-readiness"],
    riskControls: ["least-privilege", "purpose-of-use", "progressive-verification"],
    kpis: ["verification-conversion", "authorization-denials", "fraud-rate"],
  },
  {
    id: "experience-living-home",
    name: "Living Home, Experience Engine and Screen Contracts",
    canonAnchors: ["LIVING HOME + EXPERIENCE ENGINE", "SCREEN CONTRACT", "The complexity belongs to Klinikos"],
    blueprintAnchors: ["LIVING HOME + EXPERIENCE ENGINE", "SCREEN CONTRACT"],
    owners: ["experience", "frontend"],
    implementationConsequences: ["active-experience-envelope", "screen-contracts", "context-switch"],
    evidence: ["accessibility-tests", "responsive-tests", "route-tests"],
    moneyPath: ["activation", "retention", "upgrade-conversion"],
    riskControls: ["minimum-necessary-projection", "no-brochure-first"],
    kpis: ["time-to-first-value", "task-completion", "return-rate"],
  },
  {
    id: "profile-resume-recruiting",
    name: "Professional profile, resume evidence and recruiting",
    canonAnchors: ["Resume evidence is a claim, not professional authority", "RECRUITER / RESUME EVIDENCE PATH", "Tiffany provenance use case"],
    blueprintAnchors: ["RECRUITER / RESUME EVIDENCE PATH", "resume → structured career profile"],
    owners: ["identity-trust", "grid", "edu"],
    implementationConsequences: ["resume-parser", "career-profile", "claim-provenance", "matching-inputs"],
    evidence: ["resume-source", "human-confirmation", "verification-records"],
    moneyPath: ["recruiting", "grid-pro", "employer-tools"],
    riskControls: ["no-fabricated-credentials", "claim-vs-verified-separation"],
    kpis: ["profile-completion", "qualified-match-rate"],
  },
  {
    id: "edu-student-placement",
    name: "EDU, student, competency, placement and workforce transition",
    canonAnchors: ["STUDENT → TRAINING → COMPETENCY", "PLACEMENT RELATIONSHIP OBJECT", "EDU completion does not create licensure"],
    blueprintAnchors: ["STUDENT → TRAINING → COMPETENCY", "PLACEMENT RELATIONSHIP OBJECT"],
    owners: ["edu", "grid", "identity-trust"],
    implementationConsequences: ["programs", "cohorts", "simulation", "competency-evidence", "placement-object"],
    evidence: ["rubrics", "human-review", "hours-evidence"],
    moneyPath: ["edu-plus", "courses", "institution-contracts", "workforce-contracts"],
    riskControls: ["synthetic-data-first", "external-credential-separation"],
    kpis: ["completion", "placement-rate", "time-to-work"],
  },
  {
    id: "professional-injector",
    name: "Professional progression and injector/aesthetics path",
    canonAnchors: ["RN → INJECTOR / AESTHETICS GOVERNED PATH", "An unverified professional cannot publicly offer governed clinical services"],
    blueprintAnchors: ["RN → INJECTOR / AESTHETICS GOVERNED PATH", "jurisdiction / scope / supervision / facility / malpractice gates"],
    owners: ["grid", "identity-trust", "clinical-safety"],
    implementationConsequences: ["credential-gates", "service-eligibility", "availability", "contractor-relationships"],
    evidence: ["license-source", "malpractice-evidence", "supervision-evidence"],
    moneyPath: ["professional-tools", "lawful-booking-economics"],
    riskControls: ["scope-of-practice", "jurisdiction", "facility-policy"],
    kpis: ["verified-professionals", "eligible-services", "safe-fulfillment"],
  },
  {
    id: "clinic-os",
    name: "Clinic OS and operating overlay",
    canonAnchors: ["CLINIC OS — OPERATING LAYER", "Clinic OS is both operating product and ecosystem sensor"],
    blueprintAnchors: ["CLINIC OS — OPERATING LAYER", "ecosystem sensor"],
    owners: ["clinic-os", "operations"],
    implementationConsequences: ["organization", "locations", "staff", "work-queues", "capacity", "bridges"],
    evidence: ["workflow-evidence", "owner-outcomes"],
    moneyPath: ["clinic-saas", "implementation", "expansion"],
    riskControls: ["progressive-migration", "tenant-separation"],
    kpis: ["activation", "workflow-cycle-time", "revenue-recovery"],
  },
  {
    id: "current-visit",
    name: "Current Visit clinical convergence",
    canonAnchors: ["CURRENT VISIT — CLINICAL CONVERGENCE", "INITIAL → PREVIOUS → TODAY", "Nadja first-clinic provenance"],
    blueprintAnchors: ["CURRENT VISIT — CLINICAL CONVERGENCE", "INITIAL → PREVIOUS → TODAY"],
    owners: ["care", "clinical"],
    implementationConsequences: ["current-visit", "staff-handoff", "clinical-change", "body-map", "scribe-review"],
    evidence: ["signed-records", "clinical-provenance", "audit"],
    moneyPath: ["clinic-retention", "billing-readiness", "software-consolidation"],
    riskControls: ["human-signature", "no-invented-clinical-truth", "versioning"],
    kpis: ["documentation-time", "visit-close-rate", "billing-ready-rate"],
  },
  {
    id: "patient-caregiver",
    name: "Patient, caregiver and longitudinal care",
    canonAnchors: ["PATIENT / CAREGIVER JOURNEY", "Patients are never public Grid supply"],
    blueprintAnchors: ["PATIENT / CAREGIVER JOURNEY", "patient identity remains private"],
    owners: ["care", "patient-experience"],
    implementationConsequences: ["patient-portal", "proxy-access", "intake", "follow-up"],
    evidence: ["consent", "relationship-evidence", "release-audit"],
    moneyPath: ["clinic-value", "patient-payments", "retention"],
    riskControls: ["privacy", "proxy-scope", "minimum-necessary"],
    kpis: ["intake-completion", "follow-up-completion", "no-show-rate"],
  },
  {
    id: "cross-org",
    name: "Cross-organizational healthcare workflows",
    canonAnchors: ["CROSS-ORGANIZATIONAL HEALTHCARE LIFECYCLES", "relationship + purpose + minimum necessary"],
    blueprintAnchors: ["CROSS-ORGANIZATIONAL HEALTHCARE LIFECYCLES", "closed-loop referral"],
    owners: ["network", "integration-hub", "security"],
    implementationConsequences: ["referrals", "consults", "orders-results", "cross-org-relationship"],
    evidence: ["transmission-evidence", "acceptance", "review", "closure"],
    moneyPath: ["network-tools", "enterprise", "reduced-leakage"],
    riskControls: ["purpose-of-use", "consent", "data-minimization"],
    kpis: ["closed-loop-rate", "referral-completion", "result-review-time"],
  },
  {
    id: "medspa-commerce",
    name: "Med Spa clinic + provider network + commerce/resource proof case",
    canonAnchors: ["MED SPA = CLINIC + PROVIDER NETWORK + COMMERCE / RESOURCE NODE", "Regulated clinical inventory is not ordinary public commerce"],
    blueprintAnchors: ["MED SPA = CLINIC + PROVIDER NETWORK + COMMERCE / RESOURCE NODE", "regulated inventory boundary"],
    owners: ["clinic-os", "grid", "commerce"],
    implementationConsequences: ["lead-crm", "services", "rooms-chairs", "inventory", "bookings", "payouts"],
    evidence: ["consent", "lot-expiration", "fulfillment-evidence"],
    moneyPath: ["cash-pay", "memberships", "lawful-commerce", "space-capacity"],
    riskControls: ["scope-of-practice", "regulated-inventory", "adverse-event-workflow"],
    kpis: ["lead-to-booking", "rebooking", "chair-utilization", "inventory-waste"],
  },
  {
    id: "quality-expert-grid",
    name: "Quality Guardian, Rules & Evidence and Expert Grid",
    canonAnchors: ["QUALITY GUARDIAN → EXPERT GRID", "Melissa provenance use case"],
    blueprintAnchors: ["QUALITY GUARDIAN → EXPERT GRID", "minimum-necessary / time-limited expert access"],
    owners: ["quality", "grid", "zumi"],
    implementationConsequences: ["rules-engine", "quality-signals", "expert-engagement", "evidence-packet"],
    evidence: ["rule-provenance", "human-review", "remediation-evidence"],
    moneyPath: ["expert-services", "quality-subscription", "revenue-protection"],
    riskControls: ["human-judgment", "minimum-necessary", "no-automatic-compliance-claims"],
    kpis: ["issues-detected", "time-to-remediate", "repeat-issue-rate"],
  },
  {
    id: "rcm-financial",
    name: "Financial OS, billing, claims and revenue integrity",
    canonAnchors: ["REVENUE INTEGRITY STATE MACHINE", "PERFORMED → CHARGE EXPECTED → CHARGE PRESENT → CLAIM READY"],
    blueprintAnchors: ["REVENUE INTEGRITY STATE MACHINE", "PERFORMED → CHARGE EXPECTED → CHARGE PRESENT → CLAIM READY"],
    owners: ["financial-os", "rcm"],
    implementationConsequences: ["billing-readiness", "claims", "denials", "remittance", "reconciliation"],
    evidence: ["claim-events", "payment-evidence", "reconciliation"],
    moneyPath: ["revenue-os", "recovered-revenue", "implementation"],
    riskControls: ["financial-state-separation", "no-fake-claim-status"],
    kpis: ["clean-claim-rate", "days-to-payment", "reconciliation-rate", "leakage"],
  },
  {
    id: "payments-settlement",
    name: "Payments, obligations, payout, settlement and entitlements",
    canonAnchors: ["PRICE ≠ QUOTE ≠ CHARGE ≠ INVOICE ≠ PAYMENT", "checkout ≠ payment evidence ≠ entitlement ≠ provisioning ≠ operational external connection"],
    blueprintAnchors: ["PRICE ≠ QUOTE ≠ CHARGE ≠ INVOICE ≠ PAYMENT", "payment-driven provisioning"],
    owners: ["financial-os", "commerce"],
    implementationConsequences: ["offer-registry", "payment-evidence", "entitlements", "payout-settlement"],
    evidence: ["webhook-evidence", "ledger", "reconciliation"],
    moneyPath: ["subscriptions", "implementation", "usage", "lawful-fees"],
    riskControls: ["server-owned-price", "idempotency", "regulated-payments"],
    kpis: ["paid-conversion", "failed-payment", "settlement-lag", "gross-margin"],
  },
  {
    id: "zumi-openai",
    name: "Zumi and OpenAI governed intelligence",
    canonAnchors: ["OPENAI / ZUMI GOVERNED INTELLIGENCE", "OpenAI intelligence, Klinikos authority"],
    blueprintAnchors: ["OPENAI / ZUMI GOVERNED INTELLIGENCE", "OpenAI intelligence, Klinikos authority"],
    owners: ["zumi", "ai-platform"],
    implementationConsequences: ["provider-adapter", "policy-gate", "tool-authority", "provenance"],
    evidence: ["model-telemetry", "tool-audit", "partner-evidence-register"],
    moneyPath: ["zumi-plus", "automation", "usage-margin"],
    riskControls: ["human-approval", "phi-eligibility", "provider-abstraction"],
    kpis: ["task-success", "cost-per-task", "human-override", "latency"],
  },
  {
    id: "memory-data-evidence",
    name: "Data, evidence, memory, knowledge and analytics",
    canonAnchors: ["DATA / EVIDENCE / MEMORY / ANALYTICS PLANE", "AI memory never overrides authoritative domain state"],
    blueprintAnchors: ["DATA / EVIDENCE / MEMORY / ANALYTICS", "provenance"],
    owners: ["data", "analytics", "zumi"],
    implementationConsequences: ["evidence-model", "memory-store", "analytics-events", "knowledge-provenance"],
    evidence: ["source", "effective-date", "version", "authority-class"],
    moneyPath: ["insights", "retention", "enterprise-analytics"],
    riskControls: ["data-classification", "retention", "supersession"],
    kpis: ["evidence-completeness", "analytics-coverage", "stale-memory-rate"],
  },
  {
    id: "integrations-partners",
    name: "Integration Hub, partners and external rails",
    canonAnchors: ["CONNECT → ABSTRACT → CONTROL → INTERNALIZE → REPLACE", "PARTNER / EXTERNAL RAILS"],
    blueprintAnchors: ["CONNECT → ABSTRACT → CONTROL → INTERNALIZE → REPLACE", "PARTNER / EXTERNAL RAILS"],
    owners: ["integration-hub", "partnerships"],
    implementationConsequences: ["adapters", "webhooks", "reconciliation-work", "connection-state"],
    evidence: ["sandbox", "uat", "production-verification", "vendor-contract"],
    moneyPath: ["premium-connections", "enterprise", "software-consolidation"],
    riskControls: ["truthful-integration-status", "vendor-risk", "failure-reconciliation"],
    kpis: ["connection-success", "sync-latency", "error-backlog"],
  },
  {
    id: "security-privacy-legal",
    name: "Security, privacy, legal, confidentiality and trust",
    canonAnchors: ["SECURITY / PRIVACY / LEGAL / TRUST DEFENSE STACK", "Cross-context and cross-tenant data must not leak"],
    blueprintAnchors: ["SECURITY / PRIVACY / LEGAL / TRUST DEFENSE STACK", "browser = experience; server = authority"],
    owners: ["security", "privacy", "legal"],
    implementationConsequences: ["authn", "authz", "audit", "encryption", "secrets", "incident-response", "agreements"],
    evidence: ["security-tests", "audit-log", "vendor-evidence", "counsel-review"],
    moneyPath: ["enterprise-trust", "risk-reduction"],
    riskControls: ["least-privilege", "minimum-necessary", "no-unsupported-compliance-claim"],
    kpis: ["security-findings", "time-to-remediate", "audit-coverage"],
  },
  {
    id: "enterprise-network",
    name: "Enterprise, multi-location, payer/employer/network operations",
    canonAnchors: ["ENTERPRISE / MULTI-LOCATION / NETWORK", "cross-organization governance"],
    blueprintAnchors: ["ENTERPRISE / MULTI-LOCATION / NETWORK", "delegated administration"],
    owners: ["enterprise", "network"],
    implementationConsequences: ["org-hierarchy", "sso", "delegated-admin", "policy", "reporting"],
    evidence: ["tenant-boundary-tests", "contract-evidence", "procurement-evidence"],
    moneyPath: ["enterprise-acv", "network-expansion"],
    riskControls: ["tenant-isolation", "policy-inheritance", "procurement-gates"],
    kpis: ["locations-per-org", "enterprise-acv", "net-revenue-retention"],
  },
  {
    id: "research-public-health",
    name: "Research, public health and government",
    canonAnchors: ["RESEARCH / PUBLIC HEALTH / GOVERNMENT", "separately governed research purpose"],
    blueprintAnchors: ["RESEARCH / PUBLIC HEALTH / GOVERNMENT", "government procurement"],
    owners: ["enterprise", "government", "data-governance"],
    implementationConsequences: ["purpose-separation", "institutional-reporting", "procurement"],
    evidence: ["contract", "approval", "data-use-evidence"],
    moneyPath: ["government-contracts", "institutional-contracts"],
    riskControls: ["research-purpose", "data-governance", "legal-review"],
    kpis: ["contracts-won", "reporting-compliance", "program-outcomes"],
  },
  {
    id: "pharmacy-device-remote",
    name: "Pharmacy, devices, DME and remote care",
    canonAnchors: ["PHARMACY / DEVICES / REMOTE CARE", "eRx / pharmacy / device rails remain separately governed"],
    blueprintAnchors: ["PHARMACY / DEVICES / REMOTE CARE", "CONNECT external authoritative rails"],
    owners: ["care", "integration-hub"],
    implementationConsequences: ["orders", "device-observations", "remote-care", "external-adapters"],
    evidence: ["order-evidence", "device-source", "external-acknowledgement"],
    moneyPath: ["clinic-value", "premium-integrations"],
    riskControls: ["clinical-authority", "external-truth", "device-security"],
    kpis: ["order-completion", "remote-monitoring-adherence"],
  },
  {
    id: "brand-market-positioning",
    name: "Brand, market thesis and positioning",
    canonAnchors: ["THE OPERATING NETWORK FOR HEALTHCARE", "MARKET / BRAND / CATEGORY POSITIONING"],
    blueprintAnchors: ["MARKET / BRAND / CATEGORY POSITIONING", "unfinished work falls between systems"],
    owners: ["ceo", "marketing", "product"],
    implementationConsequences: ["website", "messaging", "demo", "proof"],
    evidence: ["customer-research", "conversion-data"],
    moneyPath: ["demand-generation", "sales"],
    riskControls: ["no-fake-claims", "protect-crown-jewels"],
    kpis: ["qualified-traffic", "demo-rate", "message-comprehension"],
  },
  {
    id: "market-competition-icp",
    name: "Market intelligence, competition and ICP",
    canonAnchors: ["MARKET INTELLIGENCE / COMPETITION / ICP", "economic buyer / decision-maker / champion / end user / blocker"],
    blueprintAnchors: ["MARKET INTELLIGENCE / COMPETITION / ICP", "initiative gate"],
    owners: ["strategy", "sales", "marketing"],
    implementationConsequences: ["research-register", "segment-priority", "buyer-map"],
    evidence: ["dated-research", "interviews", "pipeline-data"],
    moneyPath: ["higher-win-rate", "lower-cac"],
    riskControls: ["dated-evidence", "scenario-labeling"],
    kpis: ["win-rate", "sales-cycle", "cac"],
  },
  {
    id: "pricing-monetization",
    name: "Pricing, offers, monetization and unit economics",
    canonAnchors: ["PRICING / MONETIZATION / UNIT ECONOMICS", "$500", "$1,500", "$995/month"],
    blueprintAnchors: ["PRICING / MONETIZATION / UNIT ECONOMICS", "Offer Registry"],
    owners: ["cfo", "revenue", "product"],
    implementationConsequences: ["offer-registry", "entitlements", "usage-ledger", "margin-reporting"],
    evidence: ["code-owned-prices", "payment-evidence", "cohort-margin"],
    moneyPath: ["subscription", "implementation", "usage", "services", "enterprise"],
    riskControls: ["no-universal-clinical-fee", "legal-review", "server-owned-price"],
    kpis: ["gross-margin", "arpu", "attach-rate", "payback"],
  },
  {
    id: "sales-revenue",
    name: "Sales, pipeline and revenue conversion",
    canonAnchors: ["SALES / PIPELINE / REVENUE SYSTEM", "VISITOR → LEAD → QUALIFIED → DISCOVERY → DEMO"],
    blueprintAnchors: ["SALES / PIPELINE / REVENUE SYSTEM", "OUTREACH ≠ PIPELINE ≠ CONTRACT ≠ CASH"],
    owners: ["cro", "sales"],
    implementationConsequences: ["crm", "stages", "follow-up", "proposal", "payment"],
    evidence: ["crm-stage", "signed-agreement", "payment"],
    moneyPath: ["new-arr", "implementation-revenue"],
    riskControls: ["truthful-stage", "no-fake-traction"],
    kpis: ["pipeline", "win-rate", "sales-cycle", "cash-collected"],
  },
  {
    id: "acquisition-distribution",
    name: "Acquisition, distribution, attribution and content",
    canonAnchors: ["ACQUISITION / DISTRIBUTION / ATTRIBUTION", "SOURCE → CAMPAIGN → CONTENT → VISIT → LEAD"],
    blueprintAnchors: ["ACQUISITION / DISTRIBUTION / ATTRIBUTION", "Grid is Klinikos’s primary network-acquisition wedge"],
    owners: ["growth", "marketing", "grid"],
    implementationConsequences: ["utm-attribution", "public-grid", "seo", "partnership-distribution"],
    evidence: ["analytics", "lead-source", "campaign-cost"],
    moneyPath: ["lower-cac", "network-growth"],
    riskControls: ["truthful-content", "privacy-safe-public-discovery"],
    kpis: ["cac", "qualified-leads", "organic-share", "referral-rate"],
  },
  {
    id: "onboarding-retention-cs",
    name: "Onboarding, activation, customer success, retention and expansion",
    canonAnchors: ["ONBOARDING / ACTIVATION / RETENTION / CUSTOMER SUCCESS", "HEALTHY / WATCH / AT-RISK / CRITICAL / EXPANSION"],
    blueprintAnchors: ["ONBOARDING / ACTIVATION / RETENTION / CUSTOMER SUCCESS", "Day 0 / Day 1 / Day 3 / Day 7 / Day 14"],
    owners: ["customer-success", "product-growth"],
    implementationConsequences: ["activation-events", "health-score", "success-plan", "expansion-triggers"],
    evidence: ["usage", "outcomes", "support-history"],
    moneyPath: ["retention", "nrr", "expansion"],
    riskControls: ["no-dark-patterns", "outcome-truth"],
    kpis: ["ttfv", "activation", "logo-retention", "nrr"],
  },
  {
    id: "automation-ops",
    name: "Automation, operations and human approval",
    canonAnchors: ["ELIMINATE → SIMPLIFY → STANDARDIZE → AUTOMATE → DELEGATE → MEASURE", "AUTOMATION / OPERATIONS SYSTEM"],
    blueprintAnchors: ["ELIMINATE → SIMPLIFY → STANDARDIZE → AUTOMATE → DELEGATE → MEASURE", "human approval"],
    owners: ["coo", "zumi", "engineering"],
    implementationConsequences: ["workflows", "agents", "approval-gates", "runbooks"],
    evidence: ["automation-audit", "human-approval", "outcome"],
    moneyPath: ["lower-cogs", "higher-capacity"],
    riskControls: ["consequential-action-gates", "rollback"],
    kpis: ["hours-saved", "automation-success", "exception-rate"],
  },
  {
    id: "capital-credit-investor",
    name: "Capital, funding, business credit and investor readiness",
    canonAnchors: ["CAPITAL / FUNDING / BUSINESS CREDIT / INVESTOR READINESS", "probability × speed × amount × dilution × repayment burden × strategic value"],
    blueprintAnchors: ["CAPITAL / FUNDING / BUSINESS CREDIT / INVESTOR READINESS", "customer-funded implementation"],
    owners: ["cfo", "ceo", "capital"],
    implementationConsequences: ["capital-register", "data-room", "bankability", "application-evidence"],
    evidence: ["actual-applications", "bank-records", "signed-terms"],
    moneyPath: ["customer-capital", "non-dilutive", "debt", "equity"],
    riskControls: ["no-fake-application-facts", "cheapest-capital-first"],
    kpis: ["runway", "capital-cost", "funding-probability"],
  },
  {
    id: "financial-model-cfo",
    name: "Financial model, cash control and company economics",
    canonAnchors: ["CFO / FINANCIAL MODEL / CASH CONTROL", "MRR / ARR / ACV / CAC / LTV / gross margin / payback / churn / NRR"],
    blueprintAnchors: ["CFO / FINANCIAL MODEL / CASH CONTROL", "base / upside / downside"],
    owners: ["cfo", "finance"],
    implementationConsequences: ["13-week-cash", "pnl", "unit-economics", "scenario-model"],
    evidence: ["bank", "payments", "ledger", "contracts"],
    moneyPath: ["cash-discipline", "margin", "runway"],
    riskControls: ["actual-vs-scenario", "cash-reconciliation"],
    kpis: ["runway", "burn", "gross-margin", "cash-collected"],
  },
  {
    id: "defensibility-network-effects",
    name: "Defensibility, network effects and switching value",
    canonAnchors: ["DEFENSIBILITY / NETWORK EFFECTS", "Value Graph"],
    blueprintAnchors: ["DEFENSIBILITY / NETWORK EFFECTS", "USER VALUE → BEHAVIOR CHANGE → EVIDENCE → ECONOMIC VALUE"],
    owners: ["strategy", "product", "network"],
    implementationConsequences: ["reputation", "evidence-history", "relationships", "workflow-depth", "distribution"],
    evidence: ["cohort-retention", "network-density", "workflow-outcomes"],
    moneyPath: ["retention", "pricing-power", "enterprise-value"],
    riskControls: ["no-fake-moat", "data-rights"],
    kpis: ["nrr", "multi-product-attach", "network-density", "switching-intent"],
  },
  {
    id: "scale-unicorn",
    name: "Scale and unicorn-value tests",
    canonAnchors: ["SCALE / UNICORN TEST", "$1M / $10M / $100M / $1B / $10B"],
    blueprintAnchors: ["SCALE / UNICORN TEST", "10 / 100 / 1,000 / 10,000 customers/users / 1M users"],
    owners: ["executive-council", "architecture"],
    implementationConsequences: ["capacity-model", "org-design", "platform-reliability", "market-expansion"],
    evidence: ["load-tests", "financial-model", "retention", "market-data"],
    moneyPath: ["enterprise-value", "scale-economics"],
    riskControls: ["premature-scale", "capital-efficiency"],
    kpis: ["arr", "gross-margin", "nrr", "uptime", "market-penetration"],
  },
  {
    id: "company-dashboard-cadence",
    name: "Executive dashboard, priorities and operating cadence",
    canonAnchors: ["EXECUTIVE DASHBOARD / OPERATING CADENCE", "TODAY / THIS WEEK / THIS MONTH / THIS QUARTER"],
    blueprintAnchors: ["EXECUTIVE DASHBOARD / OPERATING CADENCE", "OBSERVE → RESEARCH → VALIDATE → PRIORITIZE"],
    owners: ["executive-council", "coo"],
    implementationConsequences: ["dashboard", "registers", "owners", "cadence"],
    evidence: ["source-linked-kpis", "decision-log"],
    moneyPath: ["focus", "execution-speed"],
    riskControls: ["no-100-equal-priorities", "owner-accountability"],
    kpis: ["priority-throughput", "blocked-work-age", "cash-impact"],
  },
  {
    id: "production-release-devsecops",
    name: "Production, release, SRE, DevSecOps and resilience",
    canonAnchors: ["PRODUCTION / RELEASE / DEVSECOPS / RESILIENCE", "build ≠ deployed ≠ production verified"],
    blueprintAnchors: ["PRODUCTION / RELEASE / DEVSECOPS / RESILIENCE", "backup / restore / disaster recovery"],
    owners: ["engineering", "security", "sre"],
    implementationConsequences: ["ci", "release-gates", "observability", "backup-restore", "incident-response"],
    evidence: ["exact-head-ci", "deployment", "runtime", "restore-test"],
    moneyPath: ["reliability", "enterprise-readiness"],
    riskControls: ["rollback", "feature-flags", "dependency-security"],
    kpis: ["deployment-frequency", "change-failure-rate", "mttr", "uptime"],
  },
  {
    id: "external-service-economics",
    name: "External service economics and capital-efficient provisioning",
    canonAnchors: ["EXTERNAL-SERVICE ECONOMICS / COST-TO-SERVE", "Revenue should precede avoidable variable cost"],
    blueprintAnchors: ["EXTERNAL-SERVICE ECONOMICS / COST-TO-SERVE", "platform infrastructure / customer-owned connections / activate-after-sale"],
    owners: ["cfo", "integration-hub", "product"],
    implementationConsequences: ["vendor-classification", "usage-metering", "provisioning-state"],
    evidence: ["vendor-cost", "usage-ledger", "customer-demand"],
    moneyPath: ["margin", "customer-funded-usage", "reduced-burn"],
    riskControls: ["no-premature-provisioning", "vendor-lock-in-review"],
    kpis: ["cost-to-serve", "gross-margin", "unused-vendor-spend"],
  },
  {
    id: "support-service-operations",
    name: "Support, implementation and service operations",
    canonAnchors: ["SUPPORT / IMPLEMENTATION / SERVICE OPERATIONS", "implementation engagement"],
    blueprintAnchors: ["SUPPORT / IMPLEMENTATION / SERVICE OPERATIONS", "support escalation"],
    owners: ["customer-success", "implementation", "operations"],
    implementationConsequences: ["onboarding-project", "support-case", "sla", "knowledge"],
    evidence: ["case-history", "resolution", "customer-outcome"],
    moneyPath: ["implementation-revenue", "retention", "services"],
    riskControls: ["scope-control", "minimum-necessary-access"],
    kpis: ["time-to-resolution", "implementation-cycle", "csat"],
  },
  {
    id: "enterprise-procurement-trust",
    name: "Enterprise procurement, trust and assurance",
    canonAnchors: ["ENTERPRISE PROCUREMENT / TRUST / ASSURANCE", "evidence before claim"],
    blueprintAnchors: ["ENTERPRISE PROCUREMENT / TRUST / ASSURANCE", "security questionnaire / BAA / DPA / vendor review"],
    owners: ["security", "enterprise-sales", "legal"],
    implementationConsequences: ["trust-center", "evidence-room", "questionnaires", "contracting"],
    evidence: ["control-evidence", "vendor-evidence", "runtime-evidence"],
    moneyPath: ["enterprise-sales", "larger-acv"],
    riskControls: ["no-unsupported-certification", "contract-scope"],
    kpis: ["procurement-cycle", "security-review-pass-rate", "enterprise-win-rate"],
  },
  {
    id: "marketplace-safety-disputes",
    name: "Marketplace safety, fraud, incidents and disputes",
    canonAnchors: ["MARKETPLACE SAFETY / FRAUD / DISPUTES", "incident / dispute / reputation evidence"],
    blueprintAnchors: ["MARKETPLACE SAFETY / FRAUD / DISPUTES", "trust and anti-gaming"],
    owners: ["grid", "trust-safety", "legal"],
    implementationConsequences: ["reporting", "disputes", "suspension", "risk-scoring", "appeals"],
    evidence: ["incident-evidence", "decision-provenance"],
    moneyPath: ["loss-prevention", "marketplace-trust"],
    riskControls: ["anti-fraud", "appeal-path", "no-pay-to-eligibility"],
    kpis: ["incident-rate", "fraud-loss", "resolution-time"],
  },
  {
    id: "api-developer-ecosystem",
    name: "API, developer and partner ecosystem",
    canonAnchors: ["API / DEVELOPER / PARTNER ECOSYSTEM", "APIs / webhooks / FHIR / HL7 / DICOM / X12 where applicable"],
    blueprintAnchors: ["API / DEVELOPER / PARTNER ECOSYSTEM", "versioned contracts"],
    owners: ["platform", "integration-hub"],
    implementationConsequences: ["api-contracts", "webhooks", "partner-auth", "developer-docs"],
    evidence: ["contract-tests", "integration-tests", "version-history"],
    moneyPath: ["premium-integrations", "ecosystem-distribution"],
    riskControls: ["scoped-auth", "rate-limits", "data-minimization"],
    kpis: ["api-adoption", "integration-time", "error-rate"],
  },
] as const;
