export type KlinikosCanonLayer = {
  id: string;
  name: string;
  canonAnchors: readonly string[];
  blueprintAnchors: readonly string[];
  owners: readonly string[];
  implementationConsequences: readonly string[];
  evidence: readonly string[];
  moneyPath: readonly string[];
  riskControls: readonly string[];
  kpis: readonly string[];
};

/**
 * Subordinate implementation registry generated from the Master Canon.
 * It is intentionally broad: a missing layer is a governance regression even when
 * that layer is strategically deferred or not yet implemented.
 */
export const klinikosCanonLayers: readonly KlinikosCanonLayer[] = [
  {
    id: "governance-authority",
    name: "Authority, anti-compression, truth and merge-forward",
    canonAnchors: ["ONE KLINIKOS. ONE MASTER CANON. ONE GOVERNING COMPANY + PRODUCT TRUTH.", "ANTI-COMPRESSION AND LIFECYCLE-PRESERVATION LAW", "SOURCE-TO-CANON / BLUEPRINT COMPLETENESS GATE", "REUSE → EXTEND → GENERALIZE → CONNECT → PARTNER → BUILD NEW"],
    blueprintAnchors: ["AUTHORITY AND ANTI-COMPRESSION CONTRACT", "Canon compression must never erase accepted architecture", "SOURCE-TO-CANON / BLUEPRINT COMPLETENESS GATE", "REUSE → EXTEND → GENERALIZE → CONNECT → PARTNER → BUILD NEW"],
    owners: ["executive-council", "architecture"],
    implementationConsequences: ["authority-map", "sync-gates", "document-retirement"],
    evidence: ["git-history", "canon-diff", "verification-report"],
    moneyPath: ["reduces-rework", "protects-speed"],
    riskControls: ["no-parallel-authority", "no-silent-deletion"],
    kpis: ["authority-conflicts", "canon-drift-failures"],
  },
  {
    id: "five-planes",
    name: "Five-plane ecosystem architecture",
    canonAnchors: ["PLANE A — HEALTHCARE UNIVERSE", "PLANE B — ECONOMIC & RESOURCE UNIVERSE", "PLANE C — LIFECYCLE / JOURNEY UNIVERSE", "PLANE D — KLINIKOS OPERATING INFRASTRUCTURE", "PLANE E — COMPANY COMPOUNDING SYSTEM"],
    blueprintAnchors: ["PLANE A — HEALTHCARE UNIVERSE", "PLANE B — ECONOMIC & RESOURCE UNIVERSE", "PLANE C — LIFECYCLE / JOURNEY UNIVERSE", "PLANE D — KLINIKOS OPERATING INFRASTRUCTURE", "PLANE E — COMPANY COMPOUNDING SYSTEM"],
    owners: ["architecture", "product"],
    implementationConsequences: ["ecosystem-graph", "generated-views", "domain-contracts"],
    evidence: ["graph-tests", "route-tests"],
    moneyPath: ["cross-sell", "network-effects"],
    riskControls: ["no-module-silos"],
    kpis: ["cross-engine-journeys", "connected-node-coverage"],
  },
  {
    id: "healthcare-universe",
    name: "Actors, organizations, rails, assets and sectors",
    canonAnchors: ["HEALTHCARE UNIVERSE TAXONOMY", "NOW / NEXT / LATER / PARTNER / CONNECT / INTERNALIZE / NEVER_BUILD"],
    blueprintAnchors: ["HEALTHCARE UNIVERSE TAXONOMY", "sector strategy state"],
    owners: ["product", "partnerships"],
    implementationConsequences: ["actor-registry", "organization-types", "sector-policy"],
    evidence: ["schema-coverage", "integration-register"],
    moneyPath: ["market-expansion", "enterprise-contracts"],
    riskControls: ["scope-classification", "regulated-boundaries"],
    kpis: ["sector-coverage", "activated-sectors"],
  },
  {
    id: "resource-universe-grid",
    name: "Universal economic/resource universe and Grid",
    canonAnchors: ["ECONOMIC & RESOURCE UNIVERSE", "I NEED / I HAVE", "UNIVERSAL GRID TRANSACTION LIFECYCLE"],
    blueprintAnchors: ["ECONOMIC & RESOURCE UNIVERSE", "I NEED / I HAVE", "UNIVERSAL GRID TRANSACTION LIFECYCLE"],
    owners: ["grid", "financial-os"],
    implementationConsequences: ["resource-kernel", "demand-kernel", "eligibility-engine", "transaction-state-machine"],
    evidence: ["grid-tests", "transaction-evidence"],
    moneyPath: ["subscriptions", "lawful-transaction-economics", "organization-tools"],
    riskControls: ["eligibility-before-ranking", "marketplace-safety", "regulated-fee-gates"],
    kpis: ["liquidity", "match-rate", "time-to-fill", "fulfillment-rate"],
  },
  {
    id: "lifecycle-grammar",
    name: "Universal composable lifecycle grammar",
    canonAnchors: ["CANONICAL LIFECYCLE GRAMMAR", "DISCOVER → IDENTIFY → EXPRESS INTENT", "PATIENT / PROVIDER / GRID / EDU / ENTERPRISE PROPAGATION", "MF-008", "REPRESENTATIVE HUMAN JOURNEYS"],
    blueprintAnchors: ["CANONICAL LIFECYCLE GRAMMAR", "DISCOVER → IDENTIFY → EXPRESS INTENT", "PATIENT / PROVIDER / GRID / EDU / ENTERPRISE PROPAGATION", "MF-008", "REPRESENTATIVE HUMAN JOURNEY IMPLEMENTATION CONTRACT"],
    owners: ["product", "architecture"],
    implementationConsequences: ["route-registry", "state-machines", "unfinished-work", "cross-surface-propagation"],
    evidence: ["end-to-end-tests", "route-coverage"],
    moneyPath: ["conversion", "retention"],
    riskControls: ["no-happy-path-only-design"],
    kpis: ["journey-completion", "dropoff-by-state"],
  },
  {
    id: "identity-trust-authority",
    name: "Identity, claims, verification, relationships and authority",
    canonAnchors: ["IDENTITY → CLAIM → EVIDENCE → VERIFICATION → RELATIONSHIP → ELIGIBILITY → ENTITLEMENT → AUTHORITY", "Payment does not create authority"],
    blueprintAnchors: ["IDENTITY → CLAIM → EVIDENCE → VERIFICATION → RELATIONSHIP → ELIGIBILITY → ENTITLEMENT → AUTHORITY", "context switch is a security event"],
    owners: ["identity-trust", "security"],
    implementationConsequences: ["person-graph", "claim-model", "verification-model", "authority-engine"],
    evidence: ["negative-authorization-tests", "audit-events"],
    moneyPath: ["trusted-marketplace", "enterprise-readiness"],
    riskControls: ["least-privilege", "purpose-of-use", "progressive-verification"],
    kpis: ["verification-conversion", "authorization-denials", "fraud-rate"],
  },
  {
    id: "patient-identity-relationships-consent",
    name: "Patient identity, documents, relationships, consent and duplicate reconciliation",
    canonAnchors: ["CURRENT RECOGNITION PHOTO ≠ GOVERNMENT PHOTO IDENTIFICATION", "QUICK REGISTRATION ≠ COMPLETE REGISTRATION", "NEXT OF KIN / SPOUSE / PARENT OR GUARDIAN / CAREGIVER / EMERGENCY CONTACT / HEALTHCARE PROXY / AUTHORIZED REPRESENTATIVE", "RELATIONSHIP EXISTS ≠ CONTACT PERSON ≠ EMERGENCY CONTACT ≠ AUTHORIZED DISCLOSURE RECIPIENT ≠ HEALTHCARE PROXY ≠ GUARDIAN ≠ CHART ACCESS AUTHORITY", "PATIENT DUPLICATE MATCH / RECONCILIATION"],
    blueprintAnchors: ["CURRENT RECOGNITION PHOTO ≠ GOVERNMENT PHOTO IDENTIFICATION", "QUICK REGISTRATION ≠ COMPLETE REGISTRATION", "NEXT OF KIN / SPOUSE / PARENT OR GUARDIAN / CAREGIVER / EMERGENCY CONTACT / HEALTHCARE PROXY / AUTHORIZED REPRESENTATIVE", "RELATIONSHIP EXISTS ≠ CONTACT PERSON ≠ EMERGENCY CONTACT ≠ AUTHORIZED DISCLOSURE RECIPIENT ≠ HEALTHCARE PROXY ≠ GUARDIAN ≠ CHART ACCESS AUTHORITY", "PATIENT DUPLICATE MATCH / RECONCILIATION"],
    owners: ["identity-trust", "patient-experience", "health-information-management"],
    implementationConsequences: ["recognition-photo", "identity-document", "quick-and-complete-registration", "patient-relationship", "consent-directive-immunization-state", "duplicate-review-queue"],
    evidence: ["identity-evidence", "relationship-evidence", "consent-version", "merge-audit"],
    moneyPath: ["safer-intake", "lower-duplicate-cost", "clinic-retention"],
    riskControls: ["document-vs-projection", "relationship-vs-authority", "human-reviewed-merge", "minimum-necessary"],
    kpis: ["duplicate-rate", "merge-resolution-time", "consent-currency", "identity-exception-rate"],
  },
  {
    id: "provider-context-readiness",
    name: "Provider, location, service, payer/case and chart-authority readiness",
    canonAnchors: ["PROVIDER × ORGANIZATION × LOCATION × SPECIALTY / PROFESSION × SERVICE / APPOINTMENT TYPE × PAYER / FINANCIAL CASE × CREDENTIAL / PRIVILEGE / SUPERVISION × SCHEDULE POLICY × JURISDICTION × TIME", "ADMIN AUTHORITY ≠ CHART AUTHORITY"],
    blueprintAnchors: ["PROVIDER × ORGANIZATION × LOCATION × SPECIALTY / PROFESSION × SERVICE / APPOINTMENT TYPE × PAYER / FINANCIAL CASE × CREDENTIAL / PRIVILEGE / SUPERVISION × SCHEDULE POLICY × JURISDICTION × TIME", "ADMIN AUTHORITY ≠ CHART AUTHORITY"],
    owners: ["identity-trust", "clinic-os", "scheduling", "revenue-cycle"],
    implementationConsequences: ["contextual-authority", "location-privilege", "service-scope", "payer-enrollment", "break-glass"],
    evidence: ["license", "malpractice", "privilege", "payer-enrollment", "access-audit"],
    moneyPath: ["eligible-scheduling", "cleaner-claims", "enterprise-trust"],
    riskControls: ["activity-specific-eligibility", "no-admin-chart-inheritance", "effective-dating"],
    kpis: ["ready-provider-contexts", "schedule-denials", "authority-exceptions"],
  },
  {
    id: "experience-living-home",
    name: "Living Home, Experience Engine and Screen Contracts",
    canonAnchors: ["LIVING HOME + EXPERIENCE ENGINE", "SCREEN CONTRACT", "The complexity belongs to Klinikos"],
    blueprintAnchors: ["LIVING HOME + EXPERIENCE ENGINE", "SCREEN CONTRACT"],
    owners: ["experience", "frontend"],
    implementationConsequences: ["active-experience-envelope", "screen-contracts", "context-switch"],
    evidence: ["accessibility-tests", "responsive-tests", "route-tests"],
    moneyPath: ["activation", "retention", "upgrade-conversion"],
    riskControls: ["minimum-necessary-projection", "no-brochure-first"],
    kpis: ["time-to-first-value", "task-completion", "return-rate"],
  },
  {
    id: "universal-free-entry-passport",
    name: "Universal free ecosystem entry, first value and ecosystem passport",
    canonAnchors: ["MF-001", "UNIVERSAL FREE ECOSYSTEM ENTRY", "MF-002", "NO CREDIT CARD IS REQUIRED MERELY TO EXIST IN THE KLINIKOS ECOSYSTEM", "ECOSYSTEM PASSPORT", "FIRST USEFUL RESULT", "FREE PARTICIPATION AND FIRST VALUE", "PAID CAPABILITY FOLLOWS ADDITIONAL ECONOMIC VALUE"],
    blueprintAnchors: ["MF-001", "UNIVERSAL FREE ECOSYSTEM ENTRY", "MF-002", "NO CREDIT CARD IS REQUIRED MERELY TO EXIST IN THE KLINIKOS ECOSYSTEM", "ECOSYSTEM PASSPORT", "FIRST USEFUL RESULT", "FREE PARTICIPATION AND FIRST VALUE", "PAID CAPABILITY FOLLOWS ADDITIONAL ECONOMIC VALUE"],
    owners: ["experience", "identity-trust", "growth", "product"],
    implementationConsequences: ["public-intent-entry", "join-free", "basic-profile", "ecosystem-passport", "progressive-verification", "first-value-routing", "free-paid-entitlement-boundary"],
    evidence: ["entry-source", "identity-state", "first-value-event", "entitlement-decision", "upgrade-event"],
    moneyPath: ["network-liquidity", "activation", "qualified-upgrade", "retention"],
    riskControls: ["no-payment-to-exist", "no-payment-to-authority", "minimum-necessary-profile", "truthful-free-capability"],
    kpis: ["join-conversion", "time-to-first-value", "free-participation", "verified-progression", "paid-conversion"],
  },
  {
    id: "living-universe-route-path",
    name: "Living Universe projection, route law and governed Paths",
    canonAnchors: ["MF-003", "LIVING UNIVERSE", "UniverseShell / LivingHome / ObjectStage / PlaneLens / PathConstellation / NarrativeTimeline / Inspector / RelationshipGraph / SpatialView / ActionDock / ZumiCommandSurface / EcosystemPassport / LivingEdge / ExceptionQueue", "MF-004", "BEFORE / NOW / NEXT UNIVERSAL GRAMMAR", "ROUTES ARE IMPLEMENTATION PROJECTIONS", "PATHS ARE GOVERNED OBJECTIVE / LIFECYCLE PROJECTIONS"],
    blueprintAnchors: ["MF-003", "LIVING UNIVERSE", "UniverseShell / LivingHome / ObjectStage / PlaneLens / PathConstellation / NarrativeTimeline / Inspector / RelationshipGraph / SpatialView / ActionDock / ZumiCommandSurface / EcosystemPassport / LivingEdge / ExceptionQueue", "MF-004", "BEFORE / NOW / NEXT UNIVERSAL GRAMMAR", "ROUTES ARE IMPLEMENTATION PROJECTIONS", "PATHS ARE GOVERNED OBJECTIVE / LIFECYCLE PROJECTIONS"],
    owners: ["experience", "frontend", "architecture"],
    implementationConsequences: ["universe-shell", "active-object-stage", "plane-lens", "path-projection", "route-registry", "before-now-next", "responsive-accessibility"],
    evidence: ["screen-contract", "route-binding", "browser-journey", "accessibility-audit"],
    moneyPath: ["activation", "product-comprehension", "retention", "cross-engine-adoption"],
    riskControls: ["no-sixth-plane", "no-second-runtime", "no-route-from-prose-alone", "minimum-necessary-projection"],
    kpis: ["route-contract-coverage", "task-completion", "context-switch-safety", "accessibility-defects"],
  },
  {
    id: "profile-resume-recruiting",
    name: "Professional profile, resume evidence and recruiting",
    canonAnchors: ["Resume evidence is a claim, not professional authority", "RECRUITER / RESUME EVIDENCE PATH", "recruiter-facing résumé provenance use case"],
    blueprintAnchors: ["RECRUITER / RESUME EVIDENCE PATH", "resume → structured career profile"],
    owners: ["identity-trust", "grid", "edu"],
    implementationConsequences: ["resume-parser", "career-profile", "claim-provenance", "matching-inputs"],
    evidence: ["resume-source", "human-confirmation", "verification-records"],
    moneyPath: ["recruiting", "grid-pro", "employer-tools"],
    riskControls: ["no-fabricated-credentials", "claim-vs-verified-separation"],
    kpis: ["profile-completion", "qualified-match-rate"],
  },
  {
    id: "edu-student-placement",
    name: "EDU, student, competency, placement and workforce transition",
    canonAnchors: ["STUDENT → TRAINING → COMPETENCY", "PLACEMENT RELATIONSHIP OBJECT", "EDU completion does not create licensure"],
    blueprintAnchors: ["STUDENT → TRAINING → COMPETENCY", "PLACEMENT RELATIONSHIP OBJECT"],
    owners: ["edu", "grid", "identity-trust"],
    implementationConsequences: ["programs", "cohorts", "simulation", "competency-evidence", "placement-object"],
    evidence: ["rubrics", "human-review", "hours-evidence"],
    moneyPath: ["edu-plus", "courses", "institution-contracts", "workforce-contracts"],
    riskControls: ["synthetic-data-first", "external-credential-separation"],
    kpis: ["completion", "placement-rate", "time-to-work"],
  },
  {
    id: "institutional-edu-workforce",
    name: "Colleges, schools, workforce institutions and reusable program delivery",
    canonAnchors: ["MF-005", "INSTITUTIONAL EDU / WORKFORCE BOARD / GOVERNMENT TRAINING DELIVERY", "SCHOOLS, COLLEGES, UNIVERSITIES, AND WORKFORCE INSTITUTIONS ARE FIRST-CLASS ORGANIZATIONS", "INSTITUTION → PROGRAM → PATHWAY → COHORT → SESSION → LEARNER", "PORTABLE ACHIEVEMENT EVIDENCE", "WORKFORCE PROGRAM CONFIGURATION, NOT A PRODUCT FORK", "AI INDUSTRY ACCELERATOR", "AI-POWERED CAREER READINESS", "SYNTHETIC-DATA-FIRST PRACTICE"],
    blueprintAnchors: ["MF-005", "INSTITUTIONAL EDU / WORKFORCE BOARD / GOVERNMENT TRAINING DELIVERY", "SCHOOLS, COLLEGES, UNIVERSITIES, AND WORKFORCE INSTITUTIONS ARE FIRST-CLASS ORGANIZATIONS", "INSTITUTION → PROGRAM → PATHWAY → COHORT → SESSION → LEARNER", "PORTABLE ACHIEVEMENT EVIDENCE", "WORKFORCE PROGRAM CONFIGURATION, NOT A PRODUCT FORK", "AI INDUSTRY ACCELERATOR", "AI-POWERED CAREER READINESS", "SYNTHETIC-DATA-FIRST PRACTICE"],
    owners: ["edu", "institutional-programs", "grid", "enterprise"],
    implementationConsequences: ["institution-program-graph", "cohort-session-delivery", "attendance", "assessment-human-review", "portable-achievement-evidence", "placement-approvals", "institution-command-center", "program-configuration"],
    evidence: ["curriculum-version", "attendance-evidence", "assessment-rubric", "human-completion-decision", "program-report"],
    moneyPath: ["institution-contracts", "workforce-contracts", "education-services", "renewal-expansion"],
    riskControls: ["edu-not-license", "placement-not-approval", "synthetic-data-first", "no-buyer-specific-product-fork", "accessibility"],
    kpis: ["cohort-completion", "assessment-quality", "placement-approval-rate", "program-outcomes", "renewal-rate"],
  },
  {
    id: "professional-injector",
    name: "Professional progression and injector/aesthetics path",
    canonAnchors: ["RN → INJECTOR / AESTHETICS GOVERNED PATH", "An unverified professional cannot publicly offer governed clinical services"],
    blueprintAnchors: ["RN → INJECTOR / AESTHETICS GOVERNED PATH", "jurisdiction / scope / supervision / facility / malpractice gates"],
    owners: ["grid", "identity-trust", "clinical-safety"],
    implementationConsequences: ["credential-gates", "service-eligibility", "availability", "contractor-relationships"],
    evidence: ["license-source", "malpractice-evidence", "supervision-evidence"],
    moneyPath: ["professional-tools", "lawful-booking-economics"],
    riskControls: ["scope-of-practice", "jurisdiction", "facility-policy"],
    kpis: ["verified-professionals", "eligible-services", "safe-fulfillment"],
  },
  {
    id: "clinic-os",
    name: "Clinic OS and operating overlay",
    canonAnchors: ["CLINIC OS — OPERATING LAYER", "Clinic OS is both operating product and ecosystem sensor", "EHR MIGRATION / OVERLAY"],
    blueprintAnchors: ["CLINIC OS — OPERATING LAYER", "ecosystem sensor", "EHR MIGRATION / OVERLAY"],
    owners: ["clinic-os", "operations"],
    implementationConsequences: ["organization", "locations", "staff", "work-queues", "capacity", "bridges", "migration-staging-and-reconciliation"],
    evidence: ["workflow-evidence", "owner-outcomes"],
    moneyPath: ["clinic-saas", "implementation", "expansion"],
    riskControls: ["progressive-migration", "tenant-separation"],
    kpis: ["activation", "workflow-cycle-time", "revenue-recovery"],
  },
  {
    id: "current-visit",
    name: "Current Visit clinical convergence",
    canonAnchors: ["CURRENT VISIT — CLINICAL CONVERGENCE", "ONE-PAGE CURRENT VISIT", "INITIAL → PREVIOUS → TODAY", "VERSIONED BODYMAP", "NEWLY_DOCUMENTED / UNRESOLVED", "PROCEDURE / TREATMENT TIMELINE", "STAFF INTAKE IS SHALLOW, ENCOUNTER-SPECIFIC, AND REUSED", "first-clinic operating provenance"],
    blueprintAnchors: ["CURRENT VISIT — CLINICAL CONVERGENCE", "ONE-PAGE CURRENT VISIT", "INITIAL → PREVIOUS → TODAY", "VERSIONED BODYMAP", "NEWLY_DOCUMENTED / UNRESOLVED", "PROCEDURE / TREATMENT TIMELINE", "STAFF INTAKE IS SHALLOW, ENCOUNTER-SPECIFIC, AND REUSED"],
    owners: ["care", "clinical"],
    implementationConsequences: ["current-visit", "staff-handoff", "clinical-change", "body-map", "scribe-review"],
    evidence: ["signed-records", "clinical-provenance", "audit"],
    moneyPath: ["clinic-retention", "billing-readiness", "software-consolidation"],
    riskControls: ["human-signature", "no-invented-clinical-truth", "versioning"],
    kpis: ["documentation-time", "visit-close-rate", "billing-ready-rate"],
  },
  {
    id: "coverage-financial-case-recurring-care",
    name: "Coverage, financial/legal cases and recurring care",
    canonAnchors: ["COVERAGE ≠ FINANCIAL CASE", "APPOINTMENT SERIES"],
    blueprintAnchors: ["COVERAGE ≠ FINANCIAL CASE", "APPOINTMENT SERIES"],
    owners: ["patient-access", "scheduling", "financial-os"],
    implementationConsequences: ["coverage-period", "financial-case", "appointment-series", "occurrence-exceptions"],
    evidence: ["coverage-verification", "case-documents", "series-rule", "occurrence-audit"],
    moneyPath: ["scheduling-efficiency", "case-billing", "continuity"],
    riskControls: ["no-overwrite-between-cases", "effective-dating", "series-exception-safety"],
    kpis: ["case-linkage-accuracy", "series-completion", "coverage-exception-age"],
  },
  {
    id: "clinical-composition-specialty-configuration",
    name: "Clinical composition, specialty packs and governed configuration",
    canonAnchors: ["KLINIKOS CORE + SPECIALTY PACK + ORGANIZATION CONFIG + LOCATION OVERRIDE", "SPECIALTY PACKS ARE PRODUCTS, NOT FORKS", "SPECIALTY STARTER PATHWAYS ARE CONFIGURATION, NOT CORE FORKS", "CONFIGURATION REGISTRY"],
    blueprintAnchors: ["KLINIKOS CORE + SPECIALTY PACK + ORGANIZATION CONFIG + LOCATION OVERRIDE", "SPECIALTY PACKS ARE PRODUCTS, NOT FORKS", "SPECIALTY STARTER PATHWAYS ARE CONFIGURATION, NOT CORE FORKS", "CONFIGURATION REGISTRY"],
    owners: ["clinical-platform", "product", "enterprise"],
    implementationConsequences: ["clinical-component-registry", "specialty-pack", "configuration-inheritance", "effective-dated-release"],
    evidence: ["pack-version", "configuration-resolution-trace", "clinical-review"],
    moneyPath: ["specialty-pack-revenue", "lower-implementation-cost", "enterprise-expansion"],
    riskControls: ["core-invariants-not-overridable", "clinical-review", "rollback"],
    kpis: ["configuration-reuse", "time-to-specialty-launch", "fork-count", "implementation-margin"],
  },
  {
    id: "no-fault-multispecialty-case",
    name: "No-Fault and Workers' Compensation longitudinal multi-specialty case operating system",
    canonAnchors: ["NO-FAULT LONGITUDINAL MULTI-SPECIALTY CASE", "WORKERS’ COMPENSATION REUSES THE FINANCIAL CASE ARCHITECTURE", "CLOSE VISIT IS EXCEPTION RESOLUTION"],
    blueprintAnchors: ["NO-FAULT LONGITUDINAL MULTI-SPECIALTY CASE", "WORKERS’ COMPENSATION REUSES THE FINANCIAL CASE ARCHITECTURE", "CLOSE VISIT IS EXCEPTION RESOLUTION"],
    owners: ["care", "financial-os", "network"],
    implementationConsequences: ["clinical-case", "financial-case", "specialty-report-exchange", "procedure-timeline", "close-visit-resolution"],
    evidence: ["case-provenance", "report-review", "procedure-evidence", "billing-readiness"],
    moneyPath: ["case-operations", "revenue-integrity", "specialty-network"],
    riskControls: ["clinical-vs-financial-state", "source-attribution", "human-close"],
    kpis: ["case-cycle-time", "unreviewed-report-age", "close-exception-age", "billing-ready-rate"],
  },
  {
    id: "orders-results-reconciliation",
    name: "Universal orders, corrected results, communication and integration reconciliation",
    canonAnchors: ["UNIVERSAL SERVICE ORDER", "RESULT RECEIVED ≠ FINAL ≠ REVIEWED ≠ COMMUNICATED ≠ FOLLOW-UP COMPLETED", "CORRECTED RESULT REQUIRES RE-REVIEW", "INTEGRATION RECONCILIATION WORKBENCH"],
    blueprintAnchors: ["UNIVERSAL SERVICE ORDER", "RESULT RECEIVED ≠ FINAL ≠ REVIEWED ≠ COMMUNICATED ≠ FOLLOW-UP COMPLETED", "CORRECTED RESULT REQUIRES RE-REVIEW", "INTEGRATION RECONCILIATION WORKBENCH"],
    owners: ["care", "integration-hub", "patient-communications"],
    implementationConsequences: ["universal-order", "result-version", "review-obligation", "communication-evidence", "inbox-outbox-reconciliation"],
    evidence: ["external-acknowledgement", "result-source", "review-attribution", "communication-attempt"],
    moneyPath: ["clinic-retention", "network-value", "reduced-leakage"],
    riskControls: ["external-truth", "corrected-result-reopen", "dead-letter-reconciliation", "human-review"],
    kpis: ["order-ack-time", "result-review-time", "communication-close-rate", "reconciliation-backlog"],
  },
  {
    id: "ambient-coding-biller-handoff",
    name: "Ambient documentation, terminology, coding evidence and provider-to-biller handoff",
    canonAnchors: ["CONSENT → VISIT AUDIO / DICTATION", "DOCUMENTED CLINICAL EVIDENCE → CODING ASSISTANCE", "PROVIDER → BILLER STRUCTURED HANDOFF", "TERMINOLOGY RELEASE"],
    blueprintAnchors: ["CONSENT → VISIT AUDIO / DICTATION", "DOCUMENTED CLINICAL EVIDENCE → CODING ASSISTANCE", "PROVIDER → BILLER STRUCTURED HANDOFF", "TERMINOLOGY RELEASE"],
    owners: ["clinical", "zumi", "revenue-cycle"],
    implementationConsequences: ["ambient-consent", "transcript-evidence", "draft-provenance", "terminology-release", "coding-review", "biller-handoff"],
    evidence: ["source-span", "model-run", "human-edit", "provider-signature", "coding-rule-version"],
    moneyPath: ["documentation-efficiency", "billing-readiness", "revenue-integrity"],
    riskControls: ["no-invented-facts", "human-signature", "evidence-linked-codes", "effective-dated-rules"],
    kpis: ["draft-acceptance", "unsupported-code-rate", "handoff-completeness", "documentation-time"],
  },
  {
    id: "quality-measures-preventive-care",
    name: "Deterministic quality measures, HEDIS and preventive-care evidence",
    canonAnchors: ["QUALITY MEASURE / HEDIS FRAMEWORK", "deterministic measure/rule logic owns status"],
    blueprintAnchors: ["QUALITY MEASURE / HEDIS FRAMEWORK", "deterministic measure/rule logic owns status"],
    owners: ["quality", "clinical", "data-governance"],
    implementationConsequences: ["measure-definition", "effective-dated-rule", "population-evaluation", "care-gap-task"],
    evidence: ["measure-version", "input-provenance", "evaluation-trace", "human-resolution"],
    moneyPath: ["quality-subscription", "care-value", "revenue-protection"],
    riskControls: ["no-ai-owned-status", "no-generic-compliance-claim", "measure-scope"],
    kpis: ["measure-coverage", "care-gap-closure", "false-positive-rate"],
  },
  {
    id: "reference-environment-golden-case",
    name: "Synthetic reference environment and source-locked golden clinical case",
    canonAnchors: ["KLINIKOS REFERENCE ENVIRONMENT", "SOURCE-LOCKED SYNTHETIC NO-FAULT GOLDEN CASE", "NO LIVE PATIENT DATA"],
    blueprintAnchors: ["KLINIKOS REFERENCE ENVIRONMENT", "SOURCE-LOCKED SYNTHETIC NO-FAULT GOLDEN CASE", "NO LIVE PATIENT DATA"],
    owners: ["product", "clinical", "quality-assurance"],
    implementationConsequences: ["synthetic-fixtures", "role-based-reference-journey", "forbidden-action-tests", "configuration-switching"],
    evidence: ["golden-journey-test", "synthetic-data-proof", "role-matrix", "runtime-capture"],
    moneyPath: ["sales-proof", "implementation-acceleration", "training"],
    riskControls: ["no-live-patient-data", "no-fake-integration", "role-boundary-tests"],
    kpis: ["journey-pass-rate", "demo-completeness", "configuration-reuse"],
  },
  {
    id: "patient-caregiver",
    name: "Patient, caregiver and longitudinal care",
    canonAnchors: ["PATIENT / CAREGIVER JOURNEY", "Patients are never public Grid supply"],
    blueprintAnchors: ["PATIENT / CAREGIVER JOURNEY", "patient identity remains private"],
    owners: ["care", "patient-experience"],
    implementationConsequences: ["patient-portal", "proxy-access", "intake", "follow-up"],
    evidence: ["consent", "relationship-evidence", "release-audit"],
    moneyPath: ["clinic-value", "patient-payments", "retention"],
    riskControls: ["privacy", "proxy-scope", "minimum-necessary"],
    kpis: ["intake-completion", "follow-up-completion", "no-show-rate"],
  },
  {
    id: "cross-org",
    name: "Cross-organizational healthcare workflows",
    canonAnchors: ["CROSS-ORGANIZATIONAL HEALTHCARE LIFECYCLES", "relationship + purpose + minimum necessary"],
    blueprintAnchors: ["CROSS-ORGANIZATIONAL HEALTHCARE LIFECYCLES", "closed-loop referral"],
    owners: ["network", "integration-hub", "security"],
    implementationConsequences: ["referrals", "consults", "orders-results", "cross-org-relationship"],
    evidence: ["transmission-evidence", "acceptance", "review", "closure"],
    moneyPath: ["network-tools", "enterprise", "reduced-leakage"],
    riskControls: ["purpose-of-use", "consent", "data-minimization"],
    kpis: ["closed-loop-rate", "referral-completion", "result-review-time"],
  },
  {
    id: "medspa-commerce",
    name: "Med Spa clinic + provider network + commerce/resource proof case",
    canonAnchors: ["MED SPA = CLINIC + PROVIDER NETWORK + COMMERCE / RESOURCE NODE", "Regulated clinical inventory is not ordinary public commerce"],
    blueprintAnchors: ["MED SPA = CLINIC + PROVIDER NETWORK + COMMERCE / RESOURCE NODE", "regulated inventory boundary"],
    owners: ["clinic-os", "grid", "commerce"],
    implementationConsequences: ["lead-crm", "services", "rooms-chairs", "inventory", "bookings", "payouts"],
    evidence: ["consent", "lot-expiration", "fulfillment-evidence"],
    moneyPath: ["cash-pay", "memberships", "lawful-commerce", "space-capacity"],
    riskControls: ["scope-of-practice", "regulated-inventory", "adverse-event-workflow"],
    kpis: ["lead-to-booking", "rebooking", "chair-utilization", "inventory-waste"],
  },
  {
    id: "quality-expert-grid",
    name: "Quality Guardian, Rules & Evidence and Expert Grid",
    canonAnchors: ["QUALITY GUARDIAN → EXPERT GRID", "quality-expert provenance use case"],
    blueprintAnchors: ["QUALITY GUARDIAN → EXPERT GRID", "minimum-necessary / time-limited expert access"],
    owners: ["quality", "grid", "zumi"],
    implementationConsequences: ["rules-engine", "quality-signals", "expert-engagement", "evidence-packet"],
    evidence: ["rule-provenance", "human-review", "remediation-evidence"],
    moneyPath: ["expert-services", "quality-subscription", "revenue-protection"],
    riskControls: ["human-judgment", "minimum-necessary", "no-automatic-compliance-claims"],
    kpis: ["issues-detected", "time-to-remediate", "repeat-issue-rate"],
  },
  {
    id: "rcm-financial",
    name: "Financial OS, billing, claims and revenue integrity",
    canonAnchors: ["REVENUE INTEGRITY STATE MACHINE", "PERFORMED → CHARGE EXPECTED → CHARGE PRESENT → CLAIM READY"],
    blueprintAnchors: ["REVENUE INTEGRITY STATE MACHINE", "PERFORMED → CHARGE EXPECTED → CHARGE PRESENT → CLAIM READY"],
    owners: ["financial-os", "rcm"],
    implementationConsequences: ["billing-readiness", "claims", "denials", "remittance", "reconciliation"],
    evidence: ["claim-events", "payment-evidence", "reconciliation"],
    moneyPath: ["revenue-os", "recovered-revenue", "implementation"],
    riskControls: ["financial-state-separation", "no-fake-claim-status"],
    kpis: ["clean-claim-rate", "days-to-payment", "reconciliation-rate", "leakage"],
  },
  {
    id: "payments-settlement",
    name: "Payments, obligations, payout, settlement and entitlements",
    canonAnchors: ["PRICE ≠ QUOTE ≠ CHARGE ≠ INVOICE ≠ PAYMENT", "checkout ≠ payment evidence ≠ entitlement ≠ provisioning ≠ operational external connection", "VERIFIED PAYMENT EVENT → TENANT / SUBSCRIPTION / ENTITLEMENTS"],
    blueprintAnchors: ["PRICE ≠ QUOTE ≠ CHARGE ≠ INVOICE ≠ PAYMENT", "payment-driven provisioning", "VERIFIED PAYMENT EVENT → TENANT / SUBSCRIPTION / ENTITLEMENTS"],
    owners: ["financial-os", "commerce"],
    implementationConsequences: ["offer-registry", "payment-evidence", "entitlements", "payout-settlement"],
    evidence: ["webhook-evidence", "ledger", "reconciliation"],
    moneyPath: ["subscriptions", "implementation", "usage", "lawful-fees"],
    riskControls: ["server-owned-price", "idempotency", "regulated-payments"],
    kpis: ["paid-conversion", "failed-payment", "settlement-lag", "gross-margin"],
  },
  {
    id: "zumi-openai",
    name: "Zumi and OpenAI governed intelligence",
    canonAnchors: ["OPENAI / ZUMI GOVERNED INTELLIGENCE", "OpenAI intelligence, Klinikos authority", "THERE IS ONE ZUMI", "DOMAIN CAPABILITY PACKS"],
    blueprintAnchors: ["OPENAI / ZUMI GOVERNED INTELLIGENCE", "OpenAI intelligence, Klinikos authority", "THERE IS ONE ZUMI", "DOMAIN CAPABILITY PACKS"],
    owners: ["zumi", "ai-platform"],
    implementationConsequences: ["provider-adapter", "policy-gate", "tool-authority", "provenance"],
    evidence: ["model-telemetry", "tool-audit", "partner-evidence-register"],
    moneyPath: ["zumi-plus", "automation", "usage-margin"],
    riskControls: ["human-approval", "phi-eligibility", "provider-abstraction"],
    kpis: ["task-success", "cost-per-task", "human-override", "latency"],
  },
  {
    id: "memory-data-evidence",
    name: "Data, evidence, memory, knowledge and analytics",
    canonAnchors: ["DATA / EVIDENCE / MEMORY / ANALYTICS PLANE", "AI memory never overrides authoritative domain state", "EVIDENCE DURABILITY ≠ INFINITE RETENTION"],
    blueprintAnchors: ["DATA / EVIDENCE / MEMORY / ANALYTICS", "provenance", "EVIDENCE DURABILITY ≠ INFINITE RETENTION"],
    owners: ["data", "analytics", "zumi"],
    implementationConsequences: ["evidence-model", "memory-store", "analytics-events", "knowledge-provenance"],
    evidence: ["source", "effective-date", "version", "authority-class"],
    moneyPath: ["insights", "retention", "enterprise-analytics"],
    riskControls: ["data-classification", "retention", "supersession"],
    kpis: ["evidence-completeness", "analytics-coverage", "stale-memory-rate"],
  },
  {
    id: "integrations-partners",
    name: "Integration Hub, partners and external rails",
    canonAnchors: ["CONNECT → ABSTRACT → CONTROL → INTERNALIZE → REPLACE", "PARTNER / EXTERNAL RAILS"],
    blueprintAnchors: ["CONNECT → ABSTRACT → CONTROL → INTERNALIZE → REPLACE", "PARTNER / EXTERNAL RAILS"],
    owners: ["integration-hub", "partnerships"],
    implementationConsequences: ["adapters", "webhooks", "reconciliation-work", "connection-state"],
    evidence: ["sandbox", "uat", "production-verification", "vendor-contract"],
    moneyPath: ["premium-connections", "enterprise", "software-consolidation"],
    riskControls: ["truthful-integration-status", "vendor-risk", "failure-reconciliation"],
    kpis: ["connection-success", "sync-latency", "error-backlog"],
  },
  {
    id: "security-privacy-legal",
    name: "Security, privacy, legal, confidentiality and trust",
    canonAnchors: ["SECURITY / PRIVACY / LEGAL / TRUST DEFENSE STACK", "Cross-context and cross-tenant data must not leak"],
    blueprintAnchors: ["SECURITY / PRIVACY / LEGAL / TRUST DEFENSE STACK", "browser = experience; server = authority"],
    owners: ["security", "privacy", "legal"],
    implementationConsequences: ["authn", "authz", "audit", "encryption", "secrets", "incident-response", "agreements"],
    evidence: ["security-tests", "audit-log", "vendor-evidence", "counsel-review"],
    moneyPath: ["enterprise-trust", "risk-reduction"],
    riskControls: ["least-privilege", "minimum-necessary", "no-unsupported-compliance-claim"],
    kpis: ["security-findings", "time-to-remediate", "audit-coverage"],
  },
  {
    id: "enterprise-network",
    name: "Enterprise, multi-location, payer/employer/network operations",
    canonAnchors: ["ENTERPRISE / MULTI-LOCATION / NETWORK", "Cross-organization governance"],
    blueprintAnchors: ["ENTERPRISE / MULTI-LOCATION / NETWORK", "delegated administration"],
    owners: ["enterprise", "network"],
    implementationConsequences: ["org-hierarchy", "sso", "delegated-admin", "policy", "reporting"],
    evidence: ["tenant-boundary-tests", "contract-evidence", "procurement-evidence"],
    moneyPath: ["enterprise-acv", "network-expansion"],
    riskControls: ["tenant-isolation", "policy-inheritance", "procurement-gates"],
    kpis: ["locations-per-org", "enterprise-acv", "net-revenue-retention"],
  },
  {
    id: "research-public-health",
    name: "Research, public health and government",
    canonAnchors: ["RESEARCH / PUBLIC HEALTH / GOVERNMENT", "separately governed research purpose"],
    blueprintAnchors: ["RESEARCH / PUBLIC HEALTH / GOVERNMENT", "government procurement"],
    owners: ["enterprise", "government", "data-governance"],
    implementationConsequences: ["purpose-separation", "institutional-reporting", "procurement"],
    evidence: ["contract", "approval", "data-use-evidence"],
    moneyPath: ["government-contracts", "institutional-contracts"],
    riskControls: ["research-purpose", "data-governance", "legal-review"],
    kpis: ["contracts-won", "reporting-compliance", "program-outcomes"],
  },
  {
    id: "pharmacy-device-remote",
    name: "Pharmacy, devices, DME and remote care",
    canonAnchors: ["PHARMACY / DEVICES / REMOTE CARE", "eRx / pharmacy / device rails remain separately governed"],
    blueprintAnchors: ["PHARMACY / DEVICES / REMOTE CARE", "CONNECT external authoritative rails"],
    owners: ["care", "integration-hub"],
    implementationConsequences: ["orders", "device-observations", "remote-care", "external-adapters"],
    evidence: ["order-evidence", "device-source", "external-acknowledgement"],
    moneyPath: ["clinic-value", "premium-integrations"],
    riskControls: ["clinical-authority", "external-truth", "device-security"],
    kpis: ["order-completion", "remote-monitoring-adherence"],
  },
  {
    id: "brand-market-positioning",
    name: "Brand, market thesis and positioning",
    canonAnchors: ["THE OPERATING NETWORK FOR HEALTHCARE", "MARKET / BRAND / CATEGORY POSITIONING"],
    blueprintAnchors: ["MARKET / BRAND / CATEGORY POSITIONING", "unfinished work falls between systems"],
    owners: ["ceo", "marketing", "product"],
    implementationConsequences: ["website", "messaging", "demo", "proof"],
    evidence: ["customer-research", "conversion-data"],
    moneyPath: ["demand-generation", "sales"],
    riskControls: ["no-fake-claims", "protect-crown-jewels"],
    kpis: ["qualified-traffic", "demo-rate", "message-comprehension"],
  },
  {
    id: "market-competition-icp",
    name: "Market intelligence, competition and ICP",
    canonAnchors: ["MARKET INTELLIGENCE / COMPETITION / ICP", "economic buyer / decision-maker / champion / end user / influencer / blocker"],
    blueprintAnchors: ["MARKET INTELLIGENCE / COMPETITION / ICP", "initiative gate"],
    owners: ["strategy", "sales", "marketing"],
    implementationConsequences: ["research-register", "segment-priority", "buyer-map"],
    evidence: ["dated-research", "interviews", "pipeline-data"],
    moneyPath: ["higher-win-rate", "lower-cac"],
    riskControls: ["dated-evidence", "scenario-labeling"],
    kpis: ["win-rate", "sales-cycle", "cac"],
  },
  {
    id: "pricing-monetization",
    name: "Pricing, offers, monetization and unit economics",
    canonAnchors: ["MF-007", "PRICING / MONETIZATION / UNIT ECONOMICS", "$500", "$1,500", "$995/month", "PRICING FABRIC", "ACTIVE_PUBLIC / ACTIVE_PRIVATE / LEGACY_QUOTED / GRANDFATHERED / TARGET / SCENARIO / RETIRED", "HISTORICAL PRICE GENERATION CONTEXT", "TARGET / SCENARIO OFFER CONTEXT", "REVENUE SHOULD PRECEDE AVOIDABLE VARIABLE COST"],
    blueprintAnchors: ["MF-007", "PRICING / MONETIZATION / UNIT ECONOMICS", "Offer Registry", "PRICING FABRIC", "ACTIVE_PUBLIC / ACTIVE_PRIVATE / LEGACY_QUOTED / GRANDFATHERED / TARGET / SCENARIO / RETIRED", "HISTORICAL PRICE GENERATION CONTEXT", "TARGET / SCENARIO OFFER CONTEXT", "REVENUE SHOULD PRECEDE AVOIDABLE VARIABLE COST"],
    owners: ["cfo", "revenue", "product"],
    implementationConsequences: ["offer-registry", "entitlements", "usage-ledger", "margin-reporting"],
    evidence: ["code-owned-prices", "payment-evidence", "cohort-margin"],
    moneyPath: ["subscription", "implementation", "usage", "services", "enterprise"],
    riskControls: ["no-universal-clinical-fee", "legal-review", "server-owned-price"],
    kpis: ["gross-margin", "arpu", "attach-rate", "payback"],
  },
  {
    id: "black-label-experience-conversion",
    name: "Black Label V2 product-wide experience conversion",
    canonAnchors: ["BLACK LABEL V2 IS A PRODUCT-WIDE EXPERIENCE CONVERSION, NOT A THEME", "LIVING HOME IS THE UNIVERSAL AUTHENTICATED OPERATING FRONT DOOR", "PUBLIC HOMEPAGE", "LANDING FUNNEL", "AUTHENTICATED SHELL", "OBJECT STAGE", "INSPECTOR", "LIVING EDGE", "TWO DENSITY MODES", "FIVE DEPTH LEVELS", "DESIGN-TO-PRODUCTION CROSSWALK", "NO DASHBOARD CARD WALL", "BEFORE → NOW → NEXT"],
    blueprintAnchors: ["BLACK LABEL V2 IS A PRODUCT-WIDE EXPERIENCE CONVERSION, NOT A THEME", "LIVING HOME IS THE UNIVERSAL AUTHENTICATED OPERATING FRONT DOOR", "PUBLIC HOMEPAGE", "LANDING FUNNEL", "AUTHENTICATED SHELL", "OBJECT STAGE", "INSPECTOR", "LIVING EDGE", "TWO DENSITY MODES", "FIVE DEPTH LEVELS", "DESIGN-TO-PRODUCTION CROSSWALK", "NO DASHBOARD CARD WALL", "BEFORE → NOW → NEXT"],
    owners: ["experience", "frontend", "accessibility"],
    implementationConsequences: ["screen-contract", "narrative-layout", "context-personality", "responsive-adaptation", "accessibility-verification"],
    evidence: ["route-screenshot", "browser-journey", "accessibility-audit", "responsive-matrix"],
    moneyPath: ["activation", "sales-conversion", "retention"],
    riskControls: ["truthful-status", "no-card-wall", "reduced-motion", "minimum-necessary"],
    kpis: ["task-completion", "time-to-first-value", "accessibility-defects", "mobile-completion"],
  },
  {
    id: "sales-revenue",
    name: "Sales, pipeline and revenue conversion",
    canonAnchors: ["SALES / PIPELINE / REVENUE SYSTEM", "VISITOR → LEAD → QUALIFIED → DISCOVERY → DEMO"],
    blueprintAnchors: ["SALES / PIPELINE / REVENUE SYSTEM", "OUTREACH ≠ PIPELINE ≠ CONTRACT ≠ CASH"],
    owners: ["cro", "sales"],
    implementationConsequences: ["crm", "stages", "follow-up", "proposal", "payment"],
    evidence: ["crm-stage", "signed-agreement", "payment"],
    moneyPath: ["new-arr", "implementation-revenue"],
    riskControls: ["truthful-stage", "no-fake-traction"],
    kpis: ["pipeline", "win-rate", "sales-cycle", "cash-collected"],
  },
  {
    id: "acquisition-distribution",
    name: "Acquisition, distribution, attribution and content",
    canonAnchors: ["ACQUISITION / DISTRIBUTION / ATTRIBUTION", "SOURCE → CAMPAIGN → CONTENT → VISIT → LEAD"],
    blueprintAnchors: ["ACQUISITION / DISTRIBUTION / ATTRIBUTION", "Grid is Klinikos’s primary network-acquisition wedge"],
    owners: ["growth", "marketing", "grid"],
    implementationConsequences: ["utm-attribution", "public-grid", "seo", "partnership-distribution"],
    evidence: ["analytics", "lead-source", "campaign-cost"],
    moneyPath: ["lower-cac", "network-growth"],
    riskControls: ["truthful-content", "privacy-safe-public-discovery"],
    kpis: ["cac", "qualified-leads", "organic-share", "referral-rate"],
  },
  {
    id: "onboarding-retention-cs",
    name: "Onboarding, activation, customer success, retention and expansion",
    canonAnchors: ["ONBOARDING / ACTIVATION / RETENTION / CUSTOMER SUCCESS", "HEALTHY / WATCH / AT-RISK / CRITICAL / EXPANSION"],
    blueprintAnchors: ["ONBOARDING / ACTIVATION / RETENTION / CUSTOMER SUCCESS", "Day 0 / Day 1 / Day 3 / Day 7 / Day 14"],
    owners: ["customer-success", "product-growth"],
    implementationConsequences: ["activation-events", "health-score", "success-plan", "expansion-triggers"],
    evidence: ["usage", "outcomes", "support-history"],
    moneyPath: ["retention", "nrr", "expansion"],
    riskControls: ["no-dark-patterns", "outcome-truth"],
    kpis: ["ttfv", "activation", "logo-retention", "nrr"],
  },
  {
    id: "automation-ops",
    name: "Automation, operations and human approval",
    canonAnchors: ["ELIMINATE → SIMPLIFY → STANDARDIZE → AUTOMATE → DELEGATE → MEASURE", "AUTOMATION / OPERATIONS SYSTEM"],
    blueprintAnchors: ["ELIMINATE → SIMPLIFY → STANDARDIZE → AUTOMATE → DELEGATE → MEASURE", "human approval"],
    owners: ["coo", "zumi", "engineering"],
    implementationConsequences: ["workflows", "agents", "approval-gates", "runbooks"],
    evidence: ["automation-audit", "human-approval", "outcome"],
    moneyPath: ["lower-cogs", "higher-capacity"],
    riskControls: ["consequential-action-gates", "rollback"],
    kpis: ["hours-saved", "automation-success", "exception-rate"],
  },
  {
    id: "capital-credit-investor",
    name: "Capital, funding, business credit and investor readiness",
    canonAnchors: ["CAPITAL / FUNDING / BUSINESS CREDIT / INVESTOR READINESS", "probability × speed × amount × dilution × repayment burden × strategic value"],
    blueprintAnchors: ["CAPITAL / FUNDING / BUSINESS CREDIT / INVESTOR READINESS", "customer-funded implementation"],
    owners: ["cfo", "ceo", "capital"],
    implementationConsequences: ["capital-register", "data-room", "bankability", "application-evidence"],
    evidence: ["actual-applications", "bank-records", "signed-terms"],
    moneyPath: ["customer-capital", "non-dilutive", "debt", "equity"],
    riskControls: ["no-fake-application-facts", "cheapest-capital-first"],
    kpis: ["runway", "capital-cost", "funding-probability"],
  },
  {
    id: "financial-model-cfo",
    name: "Financial model, cash control and company economics",
    canonAnchors: ["CFO / FINANCIAL MODEL / CASH CONTROL", "MRR / ARR / ACV / CAC / LTV / gross margin / payback / churn / NRR"],
    blueprintAnchors: ["CFO / FINANCIAL MODEL / CASH CONTROL", "base / upside / downside"],
    owners: ["cfo", "finance"],
    implementationConsequences: ["13-week-cash", "pnl", "unit-economics", "scenario-model"],
    evidence: ["bank", "payments", "ledger", "contracts"],
    moneyPath: ["cash-discipline", "margin", "runway"],
    riskControls: ["actual-vs-scenario", "cash-reconciliation"],
    kpis: ["runway", "burn", "gross-margin", "cash-collected"],
  },
  {
    id: "defensibility-network-effects",
    name: "Defensibility, network effects and switching value",
    canonAnchors: ["DEFENSIBILITY / NETWORK EFFECTS", "Value Graph", "CLINICAL CHANGE GRAPH", "HEALTHCARE EXECUTION GRAPH", "REVENUE INTEGRITY GRAPH", "CONFIGURATION GRAPH", "EVIDENCE GRAPH"],
    blueprintAnchors: ["DEFENSIBILITY / NETWORK EFFECTS", "USER VALUE → BEHAVIOR CHANGE → EVIDENCE → ECONOMIC VALUE", "CLINICAL CHANGE GRAPH", "HEALTHCARE EXECUTION GRAPH", "REVENUE INTEGRITY GRAPH", "CONFIGURATION GRAPH", "EVIDENCE GRAPH"],
    owners: ["strategy", "product", "network"],
    implementationConsequences: ["reputation", "evidence-history", "relationships", "workflow-depth", "distribution"],
    evidence: ["cohort-retention", "network-density", "workflow-outcomes"],
    moneyPath: ["retention", "pricing-power", "enterprise-value"],
    riskControls: ["no-fake-moat", "data-rights"],
    kpis: ["nrr", "multi-product-attach", "network-density", "switching-intent"],
  },
  {
    id: "scale-unicorn",
    name: "Scale and unicorn-value tests",
    canonAnchors: ["SCALE / UNICORN TEST", "$1M / $10M / $100M / $1B / $10B"],
    blueprintAnchors: ["SCALE / UNICORN TEST", "10 / 100 / 1,000 / 10,000 customers/users / 1M users"],
    owners: ["executive-council", "architecture"],
    implementationConsequences: ["capacity-model", "org-design", "platform-reliability", "market-expansion"],
    evidence: ["load-tests", "financial-model", "retention", "market-data"],
    moneyPath: ["enterprise-value", "scale-economics"],
    riskControls: ["premature-scale", "capital-efficiency"],
    kpis: ["arr", "gross-margin", "nrr", "uptime", "market-penetration"],
  },
  {
    id: "company-dashboard-cadence",
    name: "Executive dashboard, priorities and operating cadence",
    canonAnchors: ["EXECUTIVE DASHBOARD / OPERATING CADENCE", "TODAY / THIS WEEK / THIS MONTH / THIS QUARTER"],
    blueprintAnchors: ["EXECUTIVE DASHBOARD / OPERATING CADENCE", "OBSERVE → RESEARCH → VALIDATE → PRIORITIZE"],
    owners: ["executive-council", "coo"],
    implementationConsequences: ["dashboard", "registers", "owners", "cadence"],
    evidence: ["source-linked-kpis", "decision-log"],
    moneyPath: ["focus", "execution-speed"],
    riskControls: ["no-100-equal-priorities", "owner-accountability"],
    kpis: ["priority-throughput", "blocked-work-age", "cash-impact"],
  },
  {
    id: "production-release-devsecops",
    name: "Production, release, SRE, DevSecOps and resilience",
    canonAnchors: ["PRODUCTION / RELEASE / DEVSECOPS / RESILIENCE", "build ≠ deployed ≠ production verified"],
    blueprintAnchors: ["PRODUCTION / RELEASE / DEVSECOPS / RESILIENCE", "backup / restore / disaster recovery"],
    owners: ["engineering", "security", "sre"],
    implementationConsequences: ["ci", "release-gates", "observability", "backup-restore", "incident-response"],
    evidence: ["exact-head-ci", "deployment", "runtime", "restore-test"],
    moneyPath: ["reliability", "enterprise-readiness"],
    riskControls: ["rollback", "feature-flags", "dependency-security"],
    kpis: ["deployment-frequency", "change-failure-rate", "mttr", "uptime"],
  },
  {
    id: "external-service-economics",
    name: "External service economics and capital-efficient provisioning",
    canonAnchors: ["EXTERNAL-SERVICE ECONOMICS / COST-TO-SERVE", "REVENUE SHOULD PRECEDE AVOIDABLE VARIABLE COST"],
    blueprintAnchors: ["EXTERNAL-SERVICE ECONOMICS / COST-TO-SERVE", "platform infrastructure / customer-owned connections / activate-after-sale"],
    owners: ["cfo", "integration-hub", "product"],
    implementationConsequences: ["vendor-classification", "usage-metering", "provisioning-state"],
    evidence: ["vendor-cost", "usage-ledger", "customer-demand"],
    moneyPath: ["margin", "customer-funded-usage", "reduced-burn"],
    riskControls: ["no-premature-provisioning", "vendor-lock-in-review"],
    kpis: ["cost-to-serve", "gross-margin", "unused-vendor-spend"],
  },
  {
    id: "support-service-operations",
    name: "Support, implementation and service operations",
    canonAnchors: ["SUPPORT / IMPLEMENTATION / SERVICE OPERATIONS", "implementation engagement"],
    blueprintAnchors: ["SUPPORT / IMPLEMENTATION / SERVICE OPERATIONS", "support escalation"],
    owners: ["customer-success", "implementation", "operations"],
    implementationConsequences: ["onboarding-project", "support-case", "sla", "knowledge"],
    evidence: ["case-history", "resolution", "customer-outcome"],
    moneyPath: ["implementation-revenue", "retention", "services"],
    riskControls: ["scope-control", "minimum-necessary-access"],
    kpis: ["time-to-resolution", "implementation-cycle", "csat"],
  },
  {
    id: "enterprise-procurement-trust",
    name: "Enterprise procurement, trust and assurance",
    canonAnchors: ["ENTERPRISE PROCUREMENT / TRUST / ASSURANCE", "evidence before claim"],
    blueprintAnchors: ["ENTERPRISE PROCUREMENT / TRUST / ASSURANCE", "security questionnaire / BAA / DPA / vendor review"],
    owners: ["security", "enterprise-sales", "legal"],
    implementationConsequences: ["trust-center", "evidence-room", "questionnaires", "contracting"],
    evidence: ["control-evidence", "vendor-evidence", "runtime-evidence"],
    moneyPath: ["enterprise-sales", "larger-acv"],
    riskControls: ["no-unsupported-certification", "contract-scope"],
    kpis: ["procurement-cycle", "security-review-pass-rate", "enterprise-win-rate"],
  },
  {
    id: "rfp-procurement-operating-system",
    name: "RFP and procurement operating system",
    canonAnchors: ["MF-006", "RFP / PROCUREMENT OPERATING SYSTEM", "OPPORTUNITY DISCOVERED → BUYER / SOLICITATION", "GO / NO-GO", "EACH BID MUST COMPOUND"],
    blueprintAnchors: ["MF-006", "RFP / PROCUREMENT OPERATING SYSTEM", "OPPORTUNITY DISCOVERED → BUYER / SOLICITATION", "GO / NO-GO", "EACH BID MUST COMPOUND"],
    owners: ["enterprise-sales", "procurement", "legal", "security", "implementation"],
    implementationConsequences: ["opportunity-register", "source-document-ingestion", "requirements-matrix", "capability-gap-map", "bid-workflow", "approval-signature", "submission-evidence", "contract-implementation-reporting", "reusable-evidence-library"],
    evidence: ["solicitation-source", "requirement-trace", "approval", "submission-receipt", "award-loss", "contract", "delivery-report"],
    moneyPath: ["government-contracts", "institutional-contracts", "implementation-revenue", "renewal-expansion"],
    riskControls: ["truthful-capability-map", "no-fake-credentials", "go-no-go", "counsel-review", "no-proposal-product-fork"],
    kpis: ["qualified-bids", "win-rate", "proposal-cycle", "compliance-coverage", "contract-margin", "renewal-rate"],
  },
  {
    id: "marketplace-safety-disputes",
    name: "Marketplace safety, fraud, incidents and disputes",
    canonAnchors: ["MARKETPLACE SAFETY / FRAUD / DISPUTES", "incident / dispute / reputation evidence"],
    blueprintAnchors: ["MARKETPLACE SAFETY / FRAUD / DISPUTES", "trust and anti-gaming"],
    owners: ["grid", "trust-safety", "legal"],
    implementationConsequences: ["reporting", "disputes", "suspension", "risk-scoring", "appeals"],
    evidence: ["incident-evidence", "decision-provenance"],
    moneyPath: ["loss-prevention", "marketplace-trust"],
    riskControls: ["anti-fraud", "appeal-path", "no-pay-to-eligibility"],
    kpis: ["incident-rate", "fraud-loss", "resolution-time"],
  },
  {
    id: "api-developer-ecosystem",
    name: "API, developer and partner ecosystem",
    canonAnchors: ["API / DEVELOPER / PARTNER ECOSYSTEM", "APIs / webhooks / FHIR / HL7 / DICOM / X12 where applicable"],
    blueprintAnchors: ["API / DEVELOPER / PARTNER ECOSYSTEM", "versioned contracts"],
    owners: ["platform", "integration-hub"],
    implementationConsequences: ["api-contracts", "webhooks", "partner-auth", "developer-docs"],
    evidence: ["contract-tests", "integration-tests", "version-history"],
    moneyPath: ["premium-integrations", "ecosystem-distribution"],
    riskControls: ["scoped-auth", "rate-limits", "data-minimization"],
    kpis: ["api-adoption", "integration-time", "error-rate"],
  },
] as const;
