import Link from "next/link";
import {
  Activity, ArrowRight, Building2, CircleAlert, FileCheck2, Handshake, Network,
  Orbit, RadioTower, Route, ShieldCheck, Sparkles, TriangleAlert,
} from "lucide-react";
import { NetworkHandoffActions, NetworkHandoffComposer } from "@/components/clinic/network/network-command-actions";
import type { NetworkCommandWorkspace as NetworkCommandWorkspaceData } from "@/lib/repositories/network-handoff-repository";
import { cn } from "@/lib/utils";

export type NetworkCommandView = "overview" | "map" | "handoffs";

const tabs: Array<{ href: string; label: string; view: NetworkCommandView }> = [
  { href: "/network", label: "Command", view: "overview" },
  { href: "/network/map", label: "Partner map", view: "map" },
  { href: "/network/handoffs", label: "Handoffs", view: "handoffs" },
];

function title(value: string) {
  return value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
}

function formatDate(value: string | null) {
  return value ? new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }).format(new Date(value)) : "Not set";
}

function Signal({ children, tone = "slate" }: { children: React.ReactNode; tone?: "cyan" | "emerald" | "amber" | "rose" | "violet" | "slate" }) {
  const tones = { cyan: "border-cyan-300/20 bg-cyan-300/10 text-cyan-100", emerald: "border-emerald-300/20 bg-emerald-300/10 text-emerald-100", amber: "border-amber-300/20 bg-amber-300/10 text-amber-100", rose: "border-rose-300/20 bg-rose-300/10 text-rose-100", violet: "border-violet-300/20 bg-violet-300/10 text-violet-100", slate: "border-white/10 bg-white/[0.055] text-white/55" };
  return <span className={cn("inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-[8px] font-black uppercase tracking-[.12em]", tones[tone])}>{children}</span>;
}

function Status({ value }: { value: string }) {
  const tone = /active|live|available|received|acknowledged|completed/i.test(value) ? "emerald" : /pending|ready|review|sent|fax|direct|scheduled|demo/i.test(value) ? "amber" : /failed|suspended|cancelled|unavailable/i.test(value) ? "rose" : "slate";
  return <Signal tone={tone}>{title(value)}</Signal>;
}

function Metric({ detail, icon: Icon, label, value, glow }: { detail: string; icon: typeof Network; label: string; value: string; glow: string }) {
  return <article className="relative overflow-hidden rounded-[1.45rem] border border-white/10 bg-white/[0.045] p-4"><span className={cn("absolute -right-6 -top-8 size-24 rounded-full blur-3xl", glow)} /><div className="relative"><Icon className="size-4 text-white/55" /><p className="mt-5 text-3xl font-black tracking-[-.06em] text-white">{value}</p><p className="mt-1 text-[10px] font-extrabold text-white/70">{label}</p><p className="mt-2 text-[8px] leading-4 text-white/30">{detail}</p></div></article>;
}

function NetworkHeader({ view }: { view: NetworkCommandView }) {
  const meta = view === "map" ? ["Relationship intelligence", "The clinic network, made visible.", "See every connected organization, its operating relationship, authority state, capacity, delivery health, and manual fallback without exposing a chart."] : view === "handoffs" ? ["Delivery control", "Every handoff has an owner and a receipt.", "Prepare, send, receive, acknowledge, schedule, complete, fail, or recover a controlled synthetic handoff through explicit human actions."] : ["Network command", "Connected care, visible as it moves.", "Clinicos turns the hidden web around a clinic into a permissioned operating map with consent-aware handoffs and accountable fallback paths."];
    const orbitNodes = [
      "left-3 top-3 border-emerald-300/25 bg-emerald-300/10",
      "bottom-3 left-10 border-violet-300/25 bg-violet-300/10",
      "right-4 top-4 border-amber-300/25 bg-amber-300/10",
      "bottom-2 right-12 border-rose-300/25 bg-rose-300/10",
    ];
    return <><section className="relative overflow-hidden rounded-[2.1rem] border border-white/10 bg-[#07101b] px-5 py-8 shadow-[0_42px_120px_rgba(0,0,0,.42)] sm:px-8 sm:py-10"><div className="absolute inset-0 opacity-[.15] [background-image:linear-gradient(rgba(255,255,255,.08)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.08)_1px,transparent_1px)] [background-size:48px_48px]" /><div className="absolute -right-28 -top-28 size-96 rounded-full border border-cyan-300/15 bg-cyan-300/[0.03] shadow-[0_0_100px_rgba(34,211,238,.12),inset_0_0_100px_rgba(34,211,238,.06)]" /><div className="relative grid gap-8 lg:grid-cols-[1fr_320px] lg:items-end"><div><div className="flex flex-wrap gap-2"><Signal tone="cyan"><RadioTower className="size-2.5" /> Demo</Signal><Signal tone="amber">Human review required</Signal><Signal>PostgreSQL-backed</Signal></div><p className="mt-8 text-[9px] font-black uppercase tracking-[.25em] text-cyan-200">{meta[0]}</p><h2 className="mt-3 max-w-4xl text-4xl font-black tracking-[-.07em] text-white sm:text-6xl">{meta[1]}</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-white/48">{meta[2]}</p></div><div className="relative hidden h-40 lg:block"><div className="absolute left-1/2 top-1/2 grid size-24 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full border border-cyan-300/25 bg-cyan-300/10 shadow-[0_0_70px_rgba(34,211,238,.25)]"><Orbit className="size-9 text-cyan-100" /></div>{orbitNodes.map((classes) => <span className={cn("absolute size-9 rounded-full border", classes)} key={classes} />)}<svg aria-hidden="true" className="absolute inset-0 size-full opacity-45"><path d="M30 28 L160 80 M52 132 L160 80 M290 30 L160 80 M260 136 L160 80" fill="none" stroke="rgb(103 232 249)" strokeDasharray="3 6" /></svg></div></div></section><div className="mt-4 rounded-[1.3rem] border border-amber-300/10 bg-amber-300/[0.045] px-4 py-3 text-[9px] leading-5 text-amber-100/65"><strong className="text-amber-100">Synthetic demo only.</strong> Do not enter real patient information. “Sent connected” means visible inside this controlled ClinicOS demo, not FHIR, HL7, Direct, fax, or vendor acknowledgment.</div><nav aria-label="Network command sections" className="mt-5 flex gap-2 overflow-x-auto pb-1">{tabs.map((tab) => <Link className={cn("shrink-0 rounded-xl border px-3 py-2 text-[10px] font-extrabold transition", view === tab.view ? "border-cyan-300/35 bg-cyan-300/12 text-cyan-100" : "border-white/8 bg-white/[0.035] text-white/45 hover:border-white/15 hover:text-white/75")} href={tab.href} key={tab.view}>{tab.label}</Link>)}<Link className="shrink-0 rounded-xl border border-white/8 bg-white/[0.035] px-3 py-2 text-[10px] font-extrabold text-white/45 hover:border-white/15 hover:text-white/75" href="/network/directory">Directory admin</Link><Link className="shrink-0 rounded-xl border border-violet-300/15 bg-violet-300/[0.06] px-3 py-2 text-[10px] font-extrabold text-violet-100/70" href="/grid">Open Grid</Link></nav></>;
}

function PartnerCard({ partner }: { partner: NetworkCommandWorkspaceData["partners"][number] }) {
  return <article className="rounded-[1.6rem] border border-white/10 bg-white/[0.045] p-5"><div className="flex items-start justify-between gap-3"><span className="grid size-11 place-items-center rounded-2xl border border-cyan-300/15 bg-cyan-300/[0.08] text-cyan-100"><Building2 className="size-5" /></span><div className="flex flex-wrap justify-end gap-1.5"><Status value={partner.status} /><Status value={partner.integrationStatus} /></div></div><p className="mt-5 text-[8px] font-black uppercase tracking-[.16em] text-cyan-200/65">{title(partner.relationshipType)}</p><h3 className="mt-2 text-lg font-black tracking-[-.035em] text-white">{partner.name}</h3><p className="mt-1 text-[9px] text-white/30">{title(partner.type)} · {partner.locations.length} locations · {partner.departments.length} departments</p><div className="mt-4 flex flex-wrap gap-1.5">{partner.services.slice(0, 4).map((service) => <Signal key={service}>{service}</Signal>)}{!partner.services.length && <Signal tone="amber">Services pending profile</Signal>}</div><div className="mt-5 grid grid-cols-3 gap-2"><div className="rounded-xl border border-white/8 bg-black/20 p-3"><p className="text-lg font-black text-white">{partner.pendingHandoffs}</p><p className="mt-1 text-[7px] uppercase tracking-[.1em] text-white/25">Open handoffs</p></div><div className="rounded-xl border border-white/8 bg-black/20 p-3"><p className="text-lg font-black text-white">{partner.referralCount}</p><p className="mt-1 text-[7px] uppercase tracking-[.1em] text-white/25">Referrals</p></div><div className="rounded-xl border border-white/8 bg-black/20 p-3"><p className="text-lg font-black text-white">{partner.capacityAvailable}</p><p className="mt-1 text-[7px] uppercase tracking-[.1em] text-white/25">Capacity</p></div></div><div className="mt-4 space-y-2 border-t border-white/8 pt-4 text-[9px] leading-4 text-white/40"><p><strong className="text-white/65">Contact:</strong> {title(partner.contactMethod)}</p><p><strong className="text-white/65">Manual fallback:</strong> {title(partner.manualFallbackMethod)}</p><p><strong className="text-white/65">Sharing:</strong> {partner.sharingAgreement ? `${title(partner.sharingAgreement.status)} · ${partner.sharingAgreement.dataCategories.length} categories` : "Agreement pending"}</p><p><strong className="text-white/65">Consent categories:</strong> {partner.consentRequiredCategories.join(", ") || "Patient-specific check required"}</p></div><div className="mt-4 flex flex-wrap gap-1.5"><Status value={partner.capacityStatus} />{partner.failedDeliveries > 0 && <Signal tone="rose">{partner.failedDeliveries} failed</Signal>}{partner.auditHistory.length > 0 && <Signal tone="violet">{partner.auditHistory.length} receipts</Signal>}</div></article>;
}

function NetworkMap({ workspace }: { workspace: NetworkCommandWorkspaceData }) {
  return <section className="mt-5 overflow-hidden rounded-[1.8rem] border border-white/10 bg-white/[0.035] p-5 sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[9px] font-black uppercase tracking-[.2em] text-emerald-200">Live relationship model</p><h3 className="mt-2 text-2xl font-black tracking-[-.045em] text-white">Partner constellation</h3><p className="mt-2 max-w-xl text-[10px] leading-5 text-white/40">Lines represent operating relationships, not automatic chart access. Every patient-level handoff still requires purpose, agreement, consent, and audit.</p></div><Signal tone="emerald"><ShieldCheck className="size-3" /> No chart leakage</Signal></div><div className="relative mt-8 min-h-[430px] overflow-hidden rounded-[1.6rem] border border-white/8 bg-[#030812] p-5"><div className="absolute inset-0 opacity-[.14] [background-image:radial-gradient(circle,rgba(103,232,249,.8)_1px,transparent_1px)] [background-size:28px_28px]" /><div className="relative z-10 mx-auto grid min-h-[390px] max-w-5xl place-items-center"><div className="grid w-full gap-4 lg:grid-cols-[1fr_220px_1fr] lg:items-center"><div className="space-y-3">{workspace.partners.filter((_, index) => index % 2 === 0).map((partner) => <div className="rounded-2xl border border-white/10 bg-white/[0.05] p-4" key={partner.id}><div className="flex items-center justify-between gap-2"><p className="text-xs font-black text-white">{partner.name}</p><Status value={partner.status} /></div><p className="mt-2 text-[8px] text-white/30">{title(partner.relationshipType)} · {partner.pendingHandoffs} open</p></div>)}</div><div className="relative grid min-h-44 place-items-center"><span className="absolute size-48 animate-pulse rounded-full border border-cyan-300/10" /><span className="absolute size-36 rounded-full border border-cyan-300/20" /><div className="relative grid size-28 place-items-center rounded-full border border-cyan-300/35 bg-cyan-300/10 text-center shadow-[0_0_80px_rgba(34,211,238,.2)]"><div><Network className="mx-auto size-6 text-cyan-100" /><p className="mt-2 px-2 text-[9px] font-black text-white">{workspace.currentOrganization.name}</p></div></div></div><div className="space-y-3">{workspace.partners.filter((_, index) => index % 2 === 1).map((partner) => <div className="rounded-2xl border border-white/10 bg-white/[0.05] p-4" key={partner.id}><div className="flex items-center justify-between gap-2"><p className="text-xs font-black text-white">{partner.name}</p><Status value={partner.status} /></div><p className="mt-2 text-[8px] text-white/30">{title(partner.relationshipType)} · {partner.capacityAvailable} capacity</p></div>)}</div></div></div></div></section>;
}

function HandoffCard({ handoff, workspace }: { handoff: NetworkCommandWorkspaceData["handoffs"][number]; workspace: NetworkCommandWorkspaceData }) {
  return <article className="rounded-[1.6rem] border border-white/10 bg-white/[0.045] p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap gap-1.5"><Signal tone={handoff.direction === "inbound" ? "violet" : "cyan"}>{handoff.direction}</Signal><Status value={handoff.status} /><Status value={handoff.priority} /></div><h3 className="mt-4 text-base font-black tracking-[-.03em] text-white">{title(handoff.category)}</h3><p className="mt-1 text-[9px] text-white/35">{handoff.sourceOrganizationName} → {handoff.destinationOrganizationName}</p></div><p className="text-right text-[8px] leading-4 text-white/25">Updated<br />{formatDate(handoff.updatedAt)}</p></div><div className="mt-4 grid gap-2 sm:grid-cols-3"><div className="rounded-xl border border-white/8 bg-black/20 p-3"><p className="text-[7px] uppercase tracking-[.12em] text-white/25">Patient</p><p className="mt-1 text-[9px] font-bold text-white/65">{handoff.patientName}</p><p className="mt-1 text-[7px] text-white/25">{handoff.patientMrn}</p></div><div className="rounded-xl border border-white/8 bg-black/20 p-3"><p className="text-[7px] uppercase tracking-[.12em] text-white/25">Authority</p><p className="mt-1 text-[9px] font-bold text-white/65">{title(handoff.purposeOfUse)}</p><p className="mt-1 text-[7px] text-white/25">{handoff.dataCategories.length} minimum categories</p></div><div className="rounded-xl border border-white/8 bg-black/20 p-3"><p className="text-[7px] uppercase tracking-[.12em] text-white/25">Delivery</p><p className="mt-1 text-[9px] font-bold text-white/65">{title(handoff.deliveryMethod)}</p><p className="mt-1 text-[7px] text-white/25">{handoff.humanReviewRequired ? "Human review required" : "Review policy"}</p></div></div><p className="mt-4 text-[10px] leading-5 text-white/48">{handoff.requestedAction}</p>{handoff.failureReason && <p className="mt-3 rounded-xl border border-rose-300/15 bg-rose-300/[0.06] p-3 text-[9px] leading-5 text-rose-100">{handoff.failureReason}</p>}<div className="mt-4 flex flex-wrap gap-1.5">{handoff.dataCategories.map((category) => <Signal key={category}>{title(category)}</Signal>)}<Signal tone="amber">Due {formatDate(handoff.dueAt)}</Signal></div>{handoff.events.length > 0 && <details className="mt-4 rounded-xl border border-white/8 bg-black/15 p-3"><summary className="cursor-pointer text-[8px] font-black uppercase tracking-[.12em] text-white/40">Audit trail · {handoff.events.length} events</summary><div className="mt-3 space-y-2">{handoff.events.map((event) => <div className="flex items-start justify-between gap-3 text-[8px] leading-4 text-white/35" key={event.id}><span><strong className="text-white/55">{title(event.action)}</strong>{event.note ? ` · ${event.note}` : ""}</span><span className="shrink-0">{formatDate(event.createdAt)}</span></div>)}</div></details>}<NetworkHandoffActions canUpdate={workspace.permissions.canUpdate} handoff={handoff} /></article>;
}

function HandoffBoard({ workspace }: { workspace: NetworkCommandWorkspaceData }) {
  return <section className="mt-5"><div className="grid gap-5 xl:grid-cols-[.72fr_1.28fr]"><NetworkHandoffComposer workspace={workspace} /><div className="rounded-[1.7rem] border border-white/10 bg-white/[0.035] p-5 sm:p-6"><div className="flex items-center justify-between gap-3"><div><p className="text-[9px] font-black uppercase tracking-[.2em] text-violet-200">Delivery protocol</p><h3 className="mt-2 text-xl font-black tracking-[-.04em] text-white">Truthful status sequence</h3></div><Route className="size-5 text-violet-200" /></div><div className="mt-5 grid gap-2 sm:grid-cols-2">{[["Connected", "Ready → Sent connected → Received → Acknowledged → Scheduled → Completed"], ["Manual", "Ready → Sent manual → Receipt confirmation → Completed"], ["Fax", "Ready → Fax pending → Received or Failed → Retry"], ["Direct", "Ready → Direct pending → Received or Failed → Retry"]].map(([label, detail]) => <div className="rounded-xl border border-white/8 bg-black/20 p-3" key={label}><p className="text-[9px] font-black text-white/70">{label}</p><p className="mt-2 text-[8px] leading-4 text-white/30">{detail}</p></div>)}</div><div className="mt-4 rounded-xl border border-amber-300/10 bg-amber-300/[0.05] p-3 text-[9px] leading-5 text-amber-100/60"><strong className="text-amber-100">No silent delivery.</strong> Fax and Direct remain pending until a human records receipt. Failed delivery stays visible and recoverable.</div></div></div><div className="mt-5 grid gap-4 xl:grid-cols-2">{workspace.handoffs.map((handoff) => <HandoffCard handoff={handoff} key={handoff.id} workspace={workspace} />)}{!workspace.handoffs.length && <p className="rounded-2xl border border-dashed border-white/10 p-10 text-center text-xs text-white/35 xl:col-span-2">No governed partner handoffs have been prepared.</p>}</div></section>;
}

function Overview({ workspace }: { workspace: NetworkCommandWorkspaceData }) {
  return <><section className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric detail="Active operating relationships" glow="bg-cyan-400/25" icon={Network} label="Connected partners" value={String(workspace.metrics.connectedPartners)} /><Metric detail="Human-owned delivery states" glow="bg-violet-400/25" icon={Route} label="Actions waiting" value={String(workspace.metrics.pendingActions)} /><Metric detail="Visible recovery queue" glow="bg-rose-400/25" icon={TriangleAlert} label="Failed deliveries" value={String(workspace.metrics.failedDeliveries)} /><Metric detail="Synthetic partner availability" glow="bg-emerald-400/25" icon={Activity} label="Open capacity" value={String(workspace.metrics.openCapacity)} /><Metric detail="Documented backup paths" glow="bg-amber-400/25" icon={FileCheck2} label="Manual fallbacks" value={String(workspace.metrics.manualFallbacks)} /></section><NetworkMap workspace={workspace} /><section className="mt-5 grid gap-4 lg:grid-cols-2 2xl:grid-cols-3">{workspace.partners.map((partner) => <PartnerCard key={partner.id} partner={partner} />)}</section><div className="mt-5 grid gap-4 xl:grid-cols-3"><Link className="group rounded-[1.5rem] border border-cyan-300/15 bg-cyan-300/[0.06] p-5" href="/network/handoffs"><Handshake className="size-5 text-cyan-200" /><h3 className="mt-5 text-lg font-black text-white">Compose a governed handoff</h3><p className="mt-2 text-[10px] leading-5 text-white/40">Select patient, partner, purpose, categories, consent path, and delivery method.</p><span className="mt-5 inline-flex items-center gap-2 text-[9px] font-black uppercase tracking-[.12em] text-cyan-200">Open delivery control <ArrowRight className="size-3 transition group-hover:translate-x-1" /></span></Link><Link className="group rounded-[1.5rem] border border-violet-300/15 bg-violet-300/[0.06] p-5" href="/grid"><Sparkles className="size-5 text-violet-200" /><h3 className="mt-5 text-lg font-black text-white">Find network capacity</h3><p className="mt-2 text-[10px] leading-5 text-white/40">Move from relationship map to credential-aware providers, locations, services, and availability.</p><span className="mt-5 inline-flex items-center gap-2 text-[9px] font-black uppercase tracking-[.12em] text-violet-200">Enter the Grid <ArrowRight className="size-3 transition group-hover:translate-x-1" /></span></Link><Link className="group rounded-[1.5rem] border border-amber-300/15 bg-amber-300/[0.06] p-5" href="/network/directory"><CircleAlert className="size-5 text-amber-200" /><h3 className="mt-5 text-lg font-black text-white">Manage relationship authority</h3><p className="mt-2 text-[10px] leading-5 text-white/40">Review connection state, purposes, agreements, integration status, and fallback operations.</p><span className="mt-5 inline-flex items-center gap-2 text-[9px] font-black uppercase tracking-[.12em] text-amber-200">Open directory admin <ArrowRight className="size-3 transition group-hover:translate-x-1" /></span></Link></div></>;
}

export function NetworkCommandWorkspace({ view, workspace }: { view: NetworkCommandView; workspace: NetworkCommandWorkspaceData }) {
  return <div className="-m-4 min-h-[calc(100vh-78px)] bg-[#02060c] p-4 sm:-m-6 sm:p-6 lg:-m-8 lg:p-8"><NetworkHeader view={view} />{view === "overview" && <Overview workspace={workspace} />}{view === "map" && <><NetworkMap workspace={workspace} /><section className="mt-5 grid gap-4 lg:grid-cols-2 2xl:grid-cols-3">{workspace.partners.map((partner) => <PartnerCard key={partner.id} partner={partner} />)}</section></>}{view === "handoffs" && <HandoffBoard workspace={workspace} />}</div>;
}
