import Link from "next/link";
import { ArrowRight, Check, Network, ShieldCheck, Sparkles } from "lucide-react";
import { BrandMark } from "@/components/clinic/brand-mark";

const fragments=["FOLLOW-UP","RESULTS","REFERRALS","PAPERWORK","STAFF OWNERSHIP","REVENUE"];
const surfaces=[
 ["01","OPERATIONS","See the work between systems before it disappears."],
 ["02","REVENUE","Expose missed follow-through, readiness gaps and recovery signals."],
 ["03","NETWORK + GRID","Coordinate provider capacity, referrals, locations and service access."],
 ["04","GOVERNANCE","Keep clinical and regulated decisions under explicit human authority."],
];

function ZumiOrb(){return <div className="zumi-orb" aria-label="Zumi intelligence state: observing"><i className="zumi-node"/><i className="zumi-node"/><i className="zumi-node"/><i className="zumi-node"/></div>}

export default function LandingPage(){return <div className="min-h-screen bg-[#090d12] text-[#f3f5f6]">
<header className="sticky top-0 z-50 border-b border-white/10 bg-[#090d12]/85 backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-[1500px] items-center px-5 sm:px-8 lg:px-12"><Link href="/" className="flex items-center gap-3"><BrandMark/><div><p className="text-sm font-black tracking-[-.04em]">KLINIKOS</p><p className="text-[9px] font-bold uppercase tracking-[.22em] text-white/40">Clinic operating system</p></div></Link><nav className="ml-auto hidden gap-8 text-[10px] font-bold tracking-[.18em] text-white/55 md:flex"><a href="#system">SYSTEM</a><Link href="/capabilities">CAPABILITIES</Link><Link href="/grid/join">GRID</Link><a href="#safety">SAFETY</a></nav><Link href="/sales" className="ml-6 border border-white/25 px-5 py-3 text-[10px] font-black tracking-[.14em] transition-opacity hover:opacity-70">START ANALYSIS</Link></div></header>
<main>
<section className="clinical-grid relative overflow-hidden border-b border-white/10"><div className="mx-auto grid min-h-[860px] max-w-[1500px] items-center gap-16 px-5 py-24 sm:px-8 lg:grid-cols-[1.12fr_.88fr] lg:px-12"><div><p className="mb-8 text-[10px] font-black tracking-[.26em] text-[#43d9ff]">KLINIKOS / OPERATING INTELLIGENCE</p><h1 className="max-w-[900px] text-[clamp(3.8rem,8vw,8.5rem)] font-black leading-[.84] tracking-[-.075em]">YOUR CLINIC ISN&apos;T MISSING SOFTWARE.<br/><span className="text-white/35">IT&apos;S MISSING CONTINUITY.</span></h1><p className="mt-10 max-w-2xl text-lg leading-8 text-white/55">Klinikos connects the work that happens between your systems. Zumi observes operational state, surfaces what is drifting, and prepares the next action for the right human.</p><div className="mt-10 flex flex-wrap gap-3"><Link href="/sales" className="flex items-center gap-3 bg-[#f3f5f6] px-6 py-4 text-[11px] font-black tracking-[.12em] text-[#090d12] transition hover:opacity-85 active:scale-[.98]">START CLINIC OPERATING ANALYSIS <ArrowRight className="size-4"/></Link><Link href="/private-demo" className="border border-white/25 px-6 py-4 text-[11px] font-black tracking-[.12em] transition hover:opacity-70">PRIVATE WORKFLOW REVIEW</Link></div><p className="mt-5 text-[10px] tracking-[.14em] text-white/35">NO PHI REQUIRED · HUMAN REVIEW REQUIRED</p></div><div className="flex flex-col items-center justify-center"><ZumiOrb/><div className="mt-8 w-full max-w-[420px] border-t border-white/15 pt-5"><div className="flex justify-between text-[10px] font-bold tracking-[.16em]"><span className="text-[#43d9ff]">ZUMI / OBSERVING</span><span className="text-white/35">STATE 02</span></div><p className="mt-4 text-sm leading-6 text-white/50">3 operational signals require ownership. Nothing clinical moves without the right human decision.</p></div></div></div></section>
<section className="border-b border-white/10 bg-[#0c1118]"><div className="mx-auto max-w-[1500px] px-5 py-28 sm:px-8 lg:px-12"><div className="grid gap-16 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-[10px] font-black tracking-[.22em] text-white/35">01 / FRAGMENTATION</p><h2 className="mt-5 text-5xl font-black leading-[.92] tracking-[-.06em]">THE WORK DOESN&apos;T FAIL IN ONE SYSTEM.</h2><p className="mt-7 max-w-lg leading-7 text-white/50">It fails in the gaps between calls, forms, referrals, results, billing, staff memory and disconnected software.</p></div><div className="grid grid-cols-2 border-l border-t border-white/10 sm:grid-cols-3">{fragments.map((f,i)=><div key={f} className="min-h-40 border-b border-r border-white/10 p-6"><span className="text-[9px] text-white/25">0{i+1}</span><p className="mt-16 text-[11px] font-black tracking-[.15em] text-white/65">{f}</p></div>)}</div></div></div></section>
<section id="system" className="border-b border-white/10"><div className="mx-auto max-w-[1500px] px-5 py-28 sm:px-8 lg:px-12"><p className="text-[10px] font-black tracking-[.22em] text-[#43d9ff]">02 / CONNECTION</p><div className="mt-8 grid gap-10 lg:grid-cols-2"><h2 className="max-w-2xl text-5xl font-black leading-[.92] tracking-[-.06em] sm:text-7xl">ONE OPERATING LAYER.<br/><span className="text-white/30">THE WORK STAYS VISIBLE.</span></h2><p className="max-w-xl self-end text-base leading-8 text-white/50">Klinikos does not pretend every clinic needs another replacement EHR. It creates continuity across the operational work that existing systems leave behind.</p></div><div className="mt-20 grid border-l border-t border-white/10 md:grid-cols-2">{surfaces.map(([n,t,b])=><div key={t} className="min-h-64 border-b border-r border-white/10 p-8"><p className="text-[10px] font-black tracking-[.18em] text-[#43d9ff]">{n}</p><h3 className="mt-14 text-2xl font-black tracking-[-.04em]">{t}</h3><p className="mt-4 max-w-md text-sm leading-7 text-white/45">{b}</p></div>)}</div></div></section>
<section className="border-b border-white/10 bg-[#f1f0eb] text-[#10151b]"><div className="mx-auto max-w-[1500px] px-5 py-28 sm:px-8 lg:px-12"><div className="grid gap-16 lg:grid-cols-[.72fr_1.28fr]"><div><p className="text-[10px] font-black tracking-[.22em] text-[#1677a8]">03 / INTELLIGENCE</p><h2 className="mt-6 text-5xl font-black leading-[.92] tracking-[-.06em]">ZUMI DOESN&apos;T REPLACE THE OPERATOR.</h2><p className="mt-7 leading-7 text-black/55">It makes operational state legible, shows the evidence, and routes the decision to the person who owns it.</p></div><div className="border border-black/15 bg-white"><div className="flex items-center justify-between border-b border-black/10 p-6"><div><p className="text-[9px] font-black tracking-[.18em] text-[#1677a8]">LIVE OPERATING MAP / SYNTHETIC DATA</p><h3 className="mt-2 text-xl font-black">Monday command state</h3></div><Sparkles className="size-5 text-[#1677a8]"/></div>{[["FOLLOW-UP","3 require ownership","2 overdue"],["REFERRALS","2 loops open","1 no acknowledgment"],["RESULTS","4 awaiting review","Human decision required"],["REVENUE","$8.4k readiness signal","Verify before action"]].map(([a,b,c])=><div key={a} className="grid gap-2 border-b border-black/10 p-6 sm:grid-cols-[.7fr_1fr_1fr]"><p className="text-[10px] font-black tracking-[.14em]">{a}</p><p className="text-sm font-bold">{b}</p><p className="text-sm text-black/45">{c}</p></div>)}</div></div></div></section>
<section id="safety" className="border-b border-white/10"><div className="mx-auto grid max-w-[1500px] gap-16 px-5 py-28 sm:px-8 lg:grid-cols-2 lg:px-12"><div><p className="text-[10px] font-black tracking-[.22em] text-[#43d9ff]">04 / ACCOUNTABILITY</p><h2 className="mt-6 text-5xl font-black leading-[.92] tracking-[-.06em]">INTELLIGENCE THAT KNOWS WHERE ITS AUTHORITY ENDS.</h2></div><div className="space-y-0 border-t border-white/15">{[[ShieldCheck,"HUMAN GOVERNANCE","Clinical judgment, sensitive revenue actions and regulated decisions stay with appropriately authorized people."],[Network,"CONTROLLED CONNECTIONS","External systems connect through governed gateways instead of becoming another uncontrolled silo."],[Check,"VISIBLE STATE","Sources, status, ownership and required review remain visible at the point of action."]].map(([Icon,t,b])=>{const I=Icon as typeof Check;return <div key={String(t)} className="grid gap-4 border-b border-white/15 py-8 sm:grid-cols-[40px_1fr]"><I className="size-5 text-[#43d9ff]"/><div><h3 className="text-sm font-black tracking-[.1em]">{String(t)}</h3><p className="mt-3 text-sm leading-7 text-white/45">{String(b)}</p></div></div>})}</div></div></section>
<section className="bg-[#0d131a]"><div className="mx-auto grid max-w-[1500px] gap-10 px-5 py-24 sm:px-8 lg:grid-cols-[1fr_auto] lg:items-end lg:px-12"><div><p className="text-[10px] font-black tracking-[.22em] text-[#b89a5b]">FOUNDING CLINIC / PRIVATE REVIEW</p><h2 className="mt-5 max-w-4xl text-5xl font-black leading-[.92] tracking-[-.06em] sm:text-7xl">SEE WHAT YOUR CLINIC IS LOSING BETWEEN SYSTEMS.</h2></div><Link href="/sales" className="flex items-center gap-4 border border-[#b89a5b]/70 px-6 py-4 text-[11px] font-black tracking-[.13em] text-[#d2ba82] transition hover:opacity-70">BEGIN OPERATING ANALYSIS <ArrowRight className="size-4"/></Link></div></section>
</main></div>}
