import Link from "next/link";
import { ArrowRight, AudioLines, BadgeCheck, Database, LockKeyhole, Network, ShieldCheck } from "lucide-react";
import { BrandMark } from "@/components/clinic/brand-mark";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { canonicalCapabilityCount, clinicOsDayOneRegistry, completionGateKeys, REGISTRY_CANON_VERSION } from "@/lib/feature-registry-canon";

export default function CapabilitiesPage() {
  return <div className="min-h-screen bg-[#f4f7f7] text-slate-950">
    <header className="sticky top-0 z-20 border-b border-slate-200/80 bg-white/85 backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-7xl items-center px-5 sm:px-8"><Link className="flex items-center gap-3" href="/"><BrandMark /><div><p className="text-sm font-extrabold tracking-[-.03em]">ClinicOS</p><p className="text-[9px] font-bold uppercase tracking-[.18em] text-slate-500">Priority Zero canon</p></div></Link><Button asChild className="ml-auto" size="sm"><Link href="/start">Start free <ArrowRight className="size-4" /></Link></Button></div></header>
    <main>
      <section className="overflow-hidden border-b border-slate-200 bg-[#07131f] text-white"><div className="relative mx-auto max-w-7xl px-5 py-20 sm:px-8"><div className="absolute right-0 top-0 size-96 rounded-full border border-sky-300/15 bg-sky-400/5" /><Badge className="bg-white/10 text-teal-200 ring-white/15"><LockKeyhole className="mr-1.5 size-3" /> Do-not-remove registry</Badge><h1 className="relative mt-6 max-w-4xl text-5xl font-black leading-[.98] tracking-[-.065em] sm:text-7xl">The complete connected-care vision, held in one product constitution.</h1><p className="relative mt-6 max-w-2xl text-base leading-7 text-slate-300">Every discussed feature is Priority Zero. Delivery status remains explicit so a roadmap, manual fallback, or adapter-ready contract is never misrepresented as a live clinical integration.</p><div className="relative mt-9 grid max-w-3xl grid-cols-2 gap-3 sm:grid-cols-4">{[[String(clinicOsDayOneRegistry.length), "Domains"], [canonicalCapabilityCount.toLocaleString(), "Capabilities"], [String(completionGateKeys.length), "Gates each"], [REGISTRY_CANON_VERSION, "Canon"]].map(([value, label]) => <div className="rounded-2xl bg-white/[.07] p-4 ring-1 ring-white/10" key={label}><p className="text-2xl font-black">{value}</p><p className="mt-1 text-[9px] font-bold uppercase tracking-[.12em] text-slate-400">{label}</p></div>)}</div></div></section>
      <section className="mx-auto max-w-7xl px-5 py-16 sm:px-8"><div className="grid gap-4 md:grid-cols-3">{[[Network, "Connected care", "Verified network relationships, longitudinal records, Care Constellation, capacity, closed-loop referrals, and consent."], [AudioLines, "Speak or type", "Push-to-talk voice input with an editable transcript, same-screen processing, human review, and keyboard fallback."], [ShieldCheck, "Completion over theater", "A feature is connected only after interface, persistence, permissions, audit, validation, recovery, fallback, tests, docs, and security evidence."]].map(([Icon, title, body]) => { const FeatureIcon = Icon as typeof Network; return <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-[0_16px_50px_rgba(15,23,42,.05)]" key={String(title)}><FeatureIcon className="size-5 text-teal-600" /><h2 className="mt-5 text-lg font-extrabold">{String(title)}</h2><p className="mt-3 text-sm leading-6 text-slate-600">{String(body)}</p></div>; })}</div></section>
      <section className="mx-auto max-w-7xl px-5 pb-20 sm:px-8"><div className="mb-8"><p className="text-[10px] font-extrabold uppercase tracking-[.18em] text-teal-700">All domains</p><h2 className="mt-2 text-3xl font-black tracking-[-.045em]">Priority Zero means permanent, not falsely complete.</h2></div><div className="grid gap-3 lg:grid-cols-2">{clinicOsDayOneRegistry.map((section) => <article className="rounded-2xl border border-slate-200 bg-white p-5" key={section.slug}><div className="flex items-start gap-4"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-slate-950 text-xs font-black text-white">{String(section.number).padStart(2, "0")}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="text-sm font-extrabold">{section.title}</h3><Badge tone={section.deliveryStatus === "CONNECTED" ? "teal" : section.deliveryStatus === "DEMO" || section.deliveryStatus === "FOUNDATION" ? "sky" : "slate"}>{section.deliveryStatus.replace("_", " ")}</Badge></div><p className="mt-2 text-[11px] leading-5 text-slate-500">{section.mandate}</p><div className="mt-3 flex flex-wrap items-center gap-3 text-[9px] font-bold uppercase tracking-[.1em] text-slate-400"><span className="flex items-center gap-1"><BadgeCheck className="size-3 text-teal-600" /> {section.features.length} capabilities</span><span className="flex items-center gap-1"><Database className="size-3 text-sky-600" /> {section.databaseObjects.length} data contracts</span><span>{section.deliveryMode}</span></div></div></div></article>)}</div></section>
    </main>
  </div>;
}
