import { clinicCommercialOffers, clinicPlans, commercialAddOns, eduPlans, serviceEngagements } from "@/lib/commercial/klinikos-commercial";

export type StripeUniverseClassification =
  | "ACTIVE_PUBLIC"
  | "ACTIVE_PRIVATE"
  | "TARGET_TEST"
  | "DYNAMIC_POLICY"
  | "NOT_MONETIZED";

export type StripeUniverseBilling = "one_time" | "monthly" | "annual" | "dynamic" | "custom" | "none";

export type StripeUniverseOffer = {
  key: string;
  name: string;
  plane: "healthcare" | "economic_resource" | "lifecycle" | "infrastructure" | "company_compounding";
  audience: "person" | "professional" | "patient" | "clinic" | "organization" | "institution" | "partner" | "marketplace";
  classification: StripeUniverseClassification;
  billing: StripeUniverseBilling;
  amountCents: number | null;
  lookupKey: string | null;
  publicPaymentLink: boolean;
  automaticCollection: boolean;
  automaticEntitlement: "allowed_when_server_policy_matches" | "never" | "not_applicable";
  priceVersion: "2026-09-01.v2";
  note: string;
};

const VERSION = "2026-09-01.v2" as const;

/**
 * Stripe is a commercial projection of the Klinikos universe, never an authority system.
 * A successful payment can prove payment. It cannot prove identity, license, credential,
 * clinical authority, PHI permission, patient consent, legal eligibility, or completion.
 */
export const stripeUniverseOffers: readonly StripeUniverseOffer[] = [
  {
    key: "operational_audit",
    name: clinicCommercialOffers.privateWorkflowReview.name,
    plane: "company_compounding",
    audience: "clinic",
    classification: "ACTIVE_PUBLIC",
    billing: "one_time",
    amountCents: clinicCommercialOffers.privateWorkflowReview.priceCents,
    lookupKey: "klinikos_operational_audit_one_time_v1",
    publicPaymentLink: true,
    automaticCollection: true,
    automaticEntitlement: "not_applicable",
    priceVersion: VERSION,
    note: "Paid diagnostic wedge with standalone value; credit-forward policy remains separate from payment collection.",
  },
  {
    key: "implementation_blueprint",
    name: clinicCommercialOffers.foundingEvaluation.name,
    plane: "company_compounding",
    audience: "clinic",
    classification: "ACTIVE_PUBLIC",
    billing: "one_time",
    amountCents: clinicCommercialOffers.foundingEvaluation.priceCents,
    lookupKey: "klinikos_implementation_blueprint_one_time_v1",
    publicPaymentLink: true,
    automaticCollection: true,
    automaticEntitlement: "not_applicable",
    priceVersion: VERSION,
    note: "Implementation planning product; does not itself activate production or regulated capability.",
  },
  {
    key: "founding_clinic_implementation",
    name: clinicCommercialOffers.foundingImplementation.name,
    plane: "company_compounding",
    audience: "clinic",
    classification: "ACTIVE_PRIVATE",
    billing: "one_time",
    amountCents: clinicCommercialOffers.foundingImplementation.priceCents,
    lookupKey: "klinikos_founding_implementation_starting_v1",
    publicPaymentLink: false,
    automaticCollection: true,
    automaticEntitlement: "never",
    priceVersion: VERSION,
    note: "Starting anchor only; final scope is quoted because migration, locations, integrations and implementation burden vary.",
  },
  ...(["core", "growth", "scale"] as const).flatMap((tier) => {
    const plan = clinicPlans[tier];
    return [
      {
        key: `clinic_${tier}_monthly`,
        name: `${plan.name} Monthly`,
        plane: "infrastructure" as const,
        audience: "clinic" as const,
        classification: "ACTIVE_PUBLIC" as const,
        billing: "monthly" as const,
        amountCents: plan.monthlyPriceCents,
        lookupKey: `klinikos_clinic_${tier}_monthly_v1`,
        publicPaymentLink: true,
        automaticCollection: true,
        automaticEntitlement: "allowed_when_server_policy_matches" as const,
        priceVersion: VERSION,
        note: "Recurring Clinic OS subscription; production PHI, integrations and regulated capabilities remain separately gated.",
      },
      {
        key: `clinic_${tier}_annual`,
        name: `${plan.name} Annual`,
        plane: "infrastructure" as const,
        audience: "clinic" as const,
        classification: "ACTIVE_PUBLIC" as const,
        billing: "annual" as const,
        amountCents: plan.annualPriceCents,
        lookupKey: `klinikos_clinic_${tier}_annual_v1`,
        publicPaymentLink: true,
        automaticCollection: true,
        automaticEntitlement: "allowed_when_server_policy_matches" as const,
        priceVersion: VERSION,
        note: "15% annual commitment savings relative to the monthly anchor.",
      },
    ];
  }),
  {
    key: "zumi_intelligence_plus",
    name: commercialAddOns.intelligencePlus.name,
    plane: "infrastructure",
    audience: "organization",
    classification: "ACTIVE_PRIVATE",
    billing: "monthly",
    amountCents: 35_000,
    lookupKey: "klinikos_zumi_intelligence_plus_monthly_base_v1",
    publicPaymentLink: false,
    automaticCollection: true,
    automaticEntitlement: "allowed_when_server_policy_matches",
    priceVersion: VERSION,
    note: "Base add-on anchor; customer-funded variable usage follows included allowance and bounded-overage policy.",
  },
  {
    key: "revenue_os_monthly",
    name: commercialAddOns.revenueOS.name,
    plane: "economic_resource",
    audience: "organization",
    classification: "ACTIVE_PRIVATE",
    billing: "monthly",
    amountCents: 75_000,
    lookupKey: "klinikos_revenue_os_monthly_base_v1",
    publicPaymentLink: false,
    automaticCollection: true,
    automaticEntitlement: "allowed_when_server_policy_matches",
    priceVersion: VERSION,
    note: "Starting recurring anchor; exact scope depends on revenue workflows and implementation.",
  },
  {
    key: "revenue_os_setup",
    name: `${commercialAddOns.revenueOS.name} Setup`,
    plane: "company_compounding",
    audience: "organization",
    classification: "ACTIVE_PRIVATE",
    billing: "one_time",
    amountCents: 250_000,
    lookupKey: "klinikos_revenue_os_setup_base_v1",
    publicPaymentLink: false,
    automaticCollection: true,
    automaticEntitlement: "never",
    priceVersion: VERSION,
    note: "Starting setup anchor; implementation completion remains an evidenced operational event, not a payment event.",
  },
  {
    key: "network_monthly",
    name: commercialAddOns.network.name,
    plane: "economic_resource",
    audience: "organization",
    classification: "ACTIVE_PRIVATE",
    billing: "monthly",
    amountCents: 30_000,
    lookupKey: "klinikos_network_monthly_base_v1",
    publicPaymentLink: false,
    automaticCollection: true,
    automaticEntitlement: "allowed_when_server_policy_matches",
    priceVersion: VERSION,
    note: "Organization network tooling; payment never creates relationship, chart access, credential truth or regulated eligibility.",
  },
  {
    key: "network_setup",
    name: `${commercialAddOns.network.name} Setup`,
    plane: "company_compounding",
    audience: "organization",
    classification: "ACTIVE_PRIVATE",
    billing: "one_time",
    amountCents: 100_000,
    lookupKey: "klinikos_network_setup_base_v1",
    publicPaymentLink: false,
    automaticCollection: true,
    automaticEntitlement: "never",
    priceVersion: VERSION,
    note: "Starting setup anchor for configured organizational network participation.",
  },
  {
    key: "edu_plus_monthly",
    name: eduPlans.plus.name,
    plane: "lifecycle",
    audience: "person",
    classification: "ACTIVE_PUBLIC",
    billing: "monthly",
    amountCents: 2_900,
    lookupKey: "klinikos_edu_plus_monthly_v1",
    publicPaymentLink: true,
    automaticCollection: true,
    automaticEntitlement: "allowed_when_server_policy_matches",
    priceVersion: VERSION,
    note: "Midpoint of the approved $19–39/month learner range. Purchase unlocks learning capability, never a license or regulated-work eligibility.",
  },
  {
    key: "edu_plus_annual",
    name: `${eduPlans.plus.name} Annual`,
    plane: "lifecycle",
    audience: "person",
    classification: "ACTIVE_PUBLIC",
    billing: "annual",
    amountCents: 29_600,
    lookupKey: "klinikos_edu_plus_annual_v1",
    publicPaymentLink: true,
    automaticCollection: true,
    automaticEntitlement: "allowed_when_server_policy_matches",
    priceVersion: VERSION,
    note: "Approximately 15% annual commitment savings relative to $29/month.",
  },
  {
    key: "edu_course_standard",
    name: "Klinikos EDU Course",
    plane: "lifecycle",
    audience: "person",
    classification: "ACTIVE_PUBLIC",
    billing: "one_time",
    amountCents: 9_900,
    lookupKey: "klinikos_edu_course_standard_v1",
    publicPaymentLink: true,
    automaticCollection: true,
    automaticEntitlement: "allowed_when_server_policy_matches",
    priceVersion: VERSION,
    note: "Standard public course anchor inside the approved $49–199 range; specialty courses may have different approved prices.",
  },
  {
    key: "edu_pathway_standard",
    name: "Klinikos EDU Pathway",
    plane: "lifecycle",
    audience: "person",
    classification: "ACTIVE_PUBLIC",
    billing: "one_time",
    amountCents: 29_900,
    lookupKey: "klinikos_edu_pathway_standard_v1",
    publicPaymentLink: true,
    automaticCollection: true,
    automaticEntitlement: "allowed_when_server_policy_matches",
    priceVersion: VERSION,
    note: "Standard public pathway anchor inside the approved $199–499 range; pathway completion does not guarantee placement, licensure or Grid eligibility.",
  },
  {
    key: "professional_pro_monthly",
    name: "Klinikos Professional Pro",
    plane: "lifecycle",
    audience: "professional",
    classification: "TARGET_TEST",
    billing: "monthly",
    amountCents: 4_900,
    lookupKey: "klinikos_professional_pro_monthly_v1",
    publicPaymentLink: false,
    automaticCollection: true,
    automaticEntitlement: "allowed_when_server_policy_matches",
    priceVersion: VERSION,
    note: "Test-market professional productivity tier for advanced profile, availability, Zumi, career evidence and opportunity tooling. Verification itself stays free/non-purchasable.",
  },
  {
    key: "professional_pro_annual",
    name: "Klinikos Professional Pro Annual",
    plane: "lifecycle",
    audience: "professional",
    classification: "TARGET_TEST",
    billing: "annual",
    amountCents: 49_900,
    lookupKey: "klinikos_professional_pro_annual_v1",
    publicPaymentLink: false,
    automaticCollection: true,
    automaticEntitlement: "allowed_when_server_policy_matches",
    priceVersion: VERSION,
    note: "Test-market annual professional tier, approximately 15% below twelve monthly payments.",
  },
  {
    key: "professional_business_monthly",
    name: "Klinikos Professional Business",
    plane: "company_compounding",
    audience: "professional",
    classification: "TARGET_TEST",
    billing: "monthly",
    amountCents: 19_900,
    lookupKey: "klinikos_professional_business_monthly_v1",
    publicPaymentLink: false,
    automaticCollection: true,
    automaticEntitlement: "allowed_when_server_policy_matches",
    priceVersion: VERSION,
    note: "Test-market bridge from independent professional to operator: customer/work tracking, business analytics, Grid supply tools and professional Zumi support.",
  },
  {
    key: "professional_business_annual",
    name: "Klinikos Professional Business Annual",
    plane: "company_compounding",
    audience: "professional",
    classification: "TARGET_TEST",
    billing: "annual",
    amountCents: 202_900,
    lookupKey: "klinikos_professional_business_annual_v1",
    publicPaymentLink: false,
    automaticCollection: true,
    automaticEntitlement: "allowed_when_server_policy_matches",
    priceVersion: VERSION,
    note: "Test-market annual business tier, approximately 15% below twelve monthly payments.",
  },
  {
    key: "healthcare_business_launch",
    name: "Klinikos Healthcare Business Launch",
    plane: "company_compounding",
    audience: "professional",
    classification: "TARGET_TEST",
    billing: "one_time",
    amountCents: 150_000,
    lookupKey: "klinikos_healthcare_business_launch_v1",
    publicPaymentLink: false,
    automaticCollection: true,
    automaticEntitlement: "not_applicable",
    priceVersion: VERSION,
    note: "Test-market guided launch package for operating setup, tooling, insurance/resource navigation and go-to-market readiness; not legal, clinical or licensure authority.",
  },
  {
    key: "operations_growth_audit",
    name: serviceEngagements.audit.name,
    plane: "company_compounding",
    audience: "organization",
    classification: "ACTIVE_PRIVATE",
    billing: "one_time",
    amountCents: 250_000,
    lookupKey: "klinikos_operations_growth_audit_standard_v1",
    publicPaymentLink: false,
    automaticCollection: true,
    automaticEntitlement: "not_applicable",
    priceVersion: VERSION,
    note: "Standard private anchor inside the approved $1,500–5,000 engagement range; final scope may be quoted higher or lower within policy.",
  },
  {
    key: "optimization_retainer",
    name: serviceEngagements.retainer.name,
    plane: "company_compounding",
    audience: "organization",
    classification: "ACTIVE_PRIVATE",
    billing: "monthly",
    amountCents: 250_000,
    lookupKey: "klinikos_optimization_retainer_standard_v1",
    publicPaymentLink: false,
    automaticCollection: true,
    automaticEntitlement: "not_applicable",
    priceVersion: VERSION,
    note: "Standard private anchor inside the approved $1,500–5,000/month service range.",
  },
  {
    key: "enterprise_implementation",
    name: "Klinikos Enterprise Implementation",
    plane: "company_compounding",
    audience: "institution",
    classification: "ACTIVE_PRIVATE",
    billing: "custom",
    amountCents: 3_000_000,
    lookupKey: "klinikos_enterprise_implementation_starting_v1",
    publicPaymentLink: false,
    automaticCollection: true,
    automaticEntitlement: "never",
    priceVersion: VERSION,
    note: "Starting implementation anchor from current enterprise plan; contract, scope and milestones govern final billing.",
  },
  {
    key: "institutional_edu_seat",
    name: "Klinikos EDU Institutional Learner Seat",
    plane: "lifecycle",
    audience: "institution",
    classification: "TARGET_TEST",
    billing: "one_time",
    amountCents: 20_000,
    lookupKey: "klinikos_edu_institutional_seat_v1",
    publicPaymentLink: false,
    automaticCollection: true,
    automaticEntitlement: "allowed_when_server_policy_matches",
    priceVersion: VERSION,
    note: "Test-market institutional seat anchor derived from current workforce proposal economics; cohorts, instruction, support and implementation are quoted separately.",
  },
  {
    key: "grid_resource_transaction",
    name: "Grid Resource Transaction",
    plane: "economic_resource",
    audience: "marketplace",
    classification: "DYNAMIC_POLICY",
    billing: "dynamic",
    amountCents: null,
    lookupKey: null,
    publicPaymentLink: false,
    automaticCollection: true,
    automaticEntitlement: "not_applicable",
    priceVersion: VERSION,
    note: "Use Stripe Connect only after server-owned resource-class, jurisdiction, fee-splitting, payout, refund and dispute policy resolves the lawful economics. No universal take rate.",
  },
  {
    key: "customer_funded_usage",
    name: "Customer-funded usage and allowances",
    plane: "economic_resource",
    audience: "organization",
    classification: "DYNAMIC_POLICY",
    billing: "dynamic",
    amountCents: null,
    lookupKey: null,
    publicPaymentLink: false,
    automaticCollection: true,
    automaticEntitlement: "allowed_when_server_policy_matches",
    priceVersion: VERSION,
    note: "Prepaid or bounded usage for AI, voice, SMS, email, maps, document processing, storage and integrations. Never an unlimited post-paid blank check.",
  },
  ...[
    ["person_identity", "Klinikos person identity"],
    ["credential_truth", "Credential or license verification truth"],
    ["clinical_authority", "Clinical or prescriptive authority"],
    ["phi_access", "PHI access or record-release authority"],
    ["grid_eligibility", "Grid regulated-work eligibility"],
    ["patient_consent", "Patient consent"],
    ["reputation_truth", "Verified experience or reputation evidence"],
  ].map(([key, name]) => ({
    key,
    name,
    plane: "healthcare" as const,
    audience: "person" as const,
    classification: "NOT_MONETIZED" as const,
    billing: "none" as const,
    amountCents: null,
    lookupKey: null,
    publicPaymentLink: false,
    automaticCollection: false,
    automaticEntitlement: "never" as const,
    priceVersion: VERSION,
    note: "Authority/truth layer. Payment must never manufacture, purchase or override this state.",
  })),
] as const;

export function activeStripeUniverseOffers() {
  return stripeUniverseOffers.filter((offer) => offer.classification === "ACTIVE_PUBLIC" || offer.classification === "ACTIVE_PRIVATE");
}

export function publicStripeUniverseOffers() {
  return stripeUniverseOffers.filter((offer) => offer.classification === "ACTIVE_PUBLIC" && offer.publicPaymentLink);
}

export function assertStripeUniverseCatalog() {
  const lookupKeys = stripeUniverseOffers.flatMap((offer) => (offer.lookupKey ? [offer.lookupKey] : []));
  if (new Set(lookupKeys).size !== lookupKeys.length) throw new Error("Stripe universe lookup keys must be unique.");
  for (const offer of stripeUniverseOffers) {
    if (offer.classification === "NOT_MONETIZED" && (offer.amountCents !== null || offer.automaticCollection || offer.publicPaymentLink)) {
      throw new Error(`Non-monetized authority ${offer.key} cannot become a purchasable Stripe offer.`);
    }
    if (offer.publicPaymentLink && offer.classification !== "ACTIVE_PUBLIC") {
      throw new Error(`Only ACTIVE_PUBLIC offers may expose a public Stripe Payment Link: ${offer.key}.`);
    }
  }
  return true;
}
