import Link from "next/link";
import { ArrowLeft, ShieldCheck } from "lucide-react";
import { BrandMark } from "@/components/clinic/brand-mark";
import { getLegalDocument } from "@/lib/legal/document-registry";

const sections = [
  ["1. Evaluation license", "Klinikos grants a limited, revocable, non-transferable right to view the product and related materials solely for legitimate evaluation, qualification, implementation planning, approved collaboration, or authorized use. No ownership interest or broader license is granted."],
  ["2. Confidential and proprietary material", "Non-public product architecture, workflows, designs, methods, documentation, implementation materials, pricing logic, operating models, demonstrations and commercial information are proprietary to Klinikos or its licensors and must be treated as confidential when identified as confidential or reasonably understood to be confidential."],
  ["3. Restricted conduct", "You may not copy, scrape, systematically extract, reverse engineer, decompile, reproduce, republish, sell, sublicense, train a competing product on, or use protected Klinikos material to create a substantially similar competing product except where a restriction is prohibited by applicable law."],
  ["4. No patient information in evaluation environments", "Unless Klinikos expressly confirms an approved production environment and applicable agreements are complete, do not enter real patient information, protected health information, regulated health data, or production credentials into demo or evaluation environments."],
  ["5. Human review and clinical responsibility", "Klinikos does not transfer licensed clinical judgment to software. Clinical, prescribing, coding, claim, credentialing, record-release and other regulated actions remain subject to appropriate human review and authorization."],
  ["6. Feedback", "If you voluntarily provide product feedback, Klinikos may use that feedback to improve its products and services without transferring ownership of your pre-existing intellectual property."],
  ["7. Security and access", "Do not attempt unauthorized access, bypass controls, probe other tenants, expose credentials, interfere with service availability, or use the service to access information you are not authorized to receive."],
  ["8. Separate commercial agreements", "Clinic implementations, GRID participation, contractor relationships, production healthcare use, paid services and vendor-connected deployments may require additional agreements, policies, approvals or business associate terms. These access terms do not replace those agreements."],
  ["9. Changes and versioning", "Klinikos may update these access terms. Material acceptance events should be associated with a version and date. Continued access after a required re-acceptance may be conditioned on accepting the updated version."],
];

export default function AccessTermsPage() {
  const definition = getLegalDocument("access_terms");
  if (!definition) throw new Error("Canonical Access Terms metadata is unavailable.");

  return <main className="min-h-screen bg-[#f7f8fa] text-slate-950"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex h-20 max-w-5xl items-center px-5 sm:px-8"><Link className="flex items-center gap-3" href="/"><BrandMark /><div><p className="text-sm font-extrabold">Klinikos</p><p className="text-[11px] font-bold uppercase tracking-[.18em] text-[#9a7a1f]">Legal</p></div></Link><Link className="ml-auto flex items-center gap-2 text-xs font-bold text-slate-600" href="/access"><ArrowLeft className="size-4" /> Access gate</Link></div></header><article className="mx-auto max-w-4xl px-5 py-14 sm:px-8"><ShieldCheck className="size-9 text-[#9a7a1f]" /><p className="mt-6 text-[11px] font-extrabold uppercase tracking-[.2em] text-[#9a7a1f]">Version {definition.version} · Draft effective date <time dateTime={definition.effectiveDate}>{definition.effectiveDate}</time></p><h1 className="mt-3 text-4xl font-extrabold tracking-[-.05em] sm:text-5xl">{definition.title}</h1><p className="mt-6 text-sm leading-7 text-slate-600">These terms govern access to non-public Klinikos product demonstrations, evaluation materials and proprietary product surfaces. They are designed to document the conditions of access, not to eliminate rights that cannot lawfully be waived. Production and commercial use may require separate agreements.</p><div className="mt-10 divide-y divide-slate-200 border-y border-slate-200">{sections.map(([title, body]) => <section className="py-7" key={title}><h2 className="text-lg font-extrabold tracking-[-.025em]">{title}</h2><p className="mt-3 text-sm leading-7 text-slate-600">{body}</p></section>)}</div><p className="mt-8 text-xs leading-6 text-slate-500">This repository copy is product-facing terms language and should receive jurisdiction-specific legal review before being relied on as a final commercial agreement.</p></article></main>;
}
