import { ArrowRight, BadgeCheck, Check, CircleAlert, Crown, GitBranch, Handshake, Layers3 } from "lucide-react";
import { CinematicReveal } from "@/components/sales/cinematic-reveal";
import { SalesIntakeForm } from "@/components/sales/sales-intake-form";
import { SalesSiteShell } from "@/components/sales/sales-site-shell";
import { StatusPill } from "@/components/sales/status-pill";

export default function FoundingClinicPage() {
  return (
    <SalesSiteShell>
      <section className="mx-auto max-w-[1500px] px-5 pb-24 pt-20 sm:px-8 lg:px-12 lg:pt-28">
        <CinematicReveal className="max-w-5xl"><div className="flex flex-wrap gap-2"><StatusPill status="Human review required" /><StatusPill status="Requires production review" /></div><p className="mt-8 text-[10px] font-black uppercase tracking-[.24em] text-amber-200">Founding clinic pathway</p><h1 className="mt-5 text-balance text-6xl font-black leading-[.94] tracking-[-.07em] sm:text-8xl">Help shape the operating layer independent clinics deserve.</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-slate-400">Small clinics should have big-system control without big-system cost. The founding pathway evaluates fit before any implementation commitment.</p></CinematicReveal>

        <div className="mt-20 grid gap-6 lg:grid-cols-2">
          <CinematicReveal className="relative overflow-hidden rounded-[34px] border border-cyan-300/15 bg-[linear-gradient(145deg,rgba(34,211,238,.08),rgba(255,255,255,.025))] p-7 sm:p-10" delay={0.08}><GitBranch className="size-7 text-cyan-300" /><div className="mt-10 flex items-end justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-cyan-300">Founding Clinic Evaluation</p><h2 className="mt-3 text-3xl font-black tracking-[-.05em]">Map the real clinic.</h2></div><p className="text-4xl font-black tracking-[-.06em]">$1,500</p></div><div className="mt-8 space-y-4">{["Private workflow demo", "Workflow map", "Software cost review", "Operational pain-point review", "Implementation recommendation"].map((item) => <p className="flex items-center gap-3 text-sm text-slate-300" key={item}><Check className="size-4 text-cyan-300" />{item}</p>)}</div><p className="mt-8 rounded-2xl border border-cyan-300/15 bg-cyan-300/[.05] p-4 text-xs leading-6 text-cyan-100/70">The full $1,500 is credited toward the $8,000 founding contribution if the clinic proceeds.</p><a className="mt-7 flex h-13 items-center justify-center gap-2 rounded-2xl bg-white text-xs font-black text-slate-950 hover:bg-cyan-200" href="#evaluation">Request evaluation <ArrowRight className="size-4" /></a></CinematicReveal>
          <CinematicReveal className="relative overflow-hidden rounded-[34px] border border-amber-300/15 bg-[linear-gradient(145deg,rgba(245,158,11,.08),rgba(255,255,255,.025))] p-7 sm:p-10" delay={0.14}><Crown className="size-7 text-amber-200" /><div className="mt-10 flex items-end justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-amber-200">Founding Clinic Program</p><h2 className="mt-3 text-3xl font-black tracking-[-.05em]">Build with the network.</h2></div><p className="text-4xl font-black tracking-[-.06em]">$8,000</p></div><div className="mt-8 space-y-4">{["Preferred founding-clinic pricing", "Priority onboarding sequence", "Clinic-specific implementation planning", "Structured feedback and workflow review", "Early-stage product participation"].map((item) => <p className="flex items-center gap-3 text-sm text-slate-300" key={item}><BadgeCheck className="size-4 text-amber-200" />{item}</p>)}</div><p className="mt-8 rounded-2xl border border-amber-300/15 bg-amber-300/[.05] p-4 text-xs leading-6 text-amber-100/70">Target future pricing is around $500/month after launch, depending on approved scope and usage. This is a target, not a binding quote.</p><a className="mt-7 flex h-13 items-center justify-center gap-2 rounded-2xl border border-white/15 text-xs font-black hover:border-amber-200/40 hover:bg-amber-200/10" href="#evaluation">Apply for founding review <ArrowRight className="size-4" /></a></CinematicReveal>
        </div>

        <CinematicReveal className="mt-8 flex items-start gap-4 rounded-[28px] border border-rose-300/15 bg-rose-300/[.045] p-6 sm:p-8" delay={0.18}><CircleAlert className="mt-1 size-5 shrink-0 text-rose-200" /><div><p className="text-sm font-black text-rose-100">Early-stage disclosure</p><p className="mt-2 text-xs leading-6 text-slate-400">Clinicos is an engineering foundation and synthetic demonstration environment. A founding contribution does not activate production PHI use, certify compliance, guarantee integrations, guarantee revenue, or authorize clinical deployment. Scope, security, contracts, vendor connections, and production readiness require separate human review.</p></div></CinematicReveal>

        <div className="mt-20 grid gap-px overflow-hidden rounded-[30px] border border-white/10 bg-white/10 sm:grid-cols-3">{[[Layers3, "Evaluate", "Map the real workflow and cost structure."], [Handshake, "Agree", "Define scope, gates, ownership, and manual fallbacks."], [Crown, "Build", "Move through reviewed slices with preferred onboarding."]].map(([Icon, title, body], index) => <div className="bg-[#070b10] p-7" key={title as string}><p className="text-[9px] font-black text-slate-600">0{index + 1}</p><Icon className="mt-8 size-5 text-emerald-300" /><h3 className="mt-5 text-sm font-black">{title as string}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{body as string}</p></div>)}</div>
      </section>

      <section className="border-y border-white/[.08] bg-black/20" id="evaluation"><div className="mx-auto max-w-[1500px] px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="mb-10 max-w-3xl"><p className="text-[10px] font-black uppercase tracking-[.22em] text-cyan-300">Founding fit intake</p><h2 className="mt-4 text-4xl font-black tracking-[-.055em] sm:text-5xl">Start with the workflow. Earn the next step.</h2></div><SalesIntakeForm defaultOffer="founding_clinic_evaluation" /></div></section>
    </SalesSiteShell>
  );
}
