import Link from "next/link";
import { ArrowLeft, MapPinned, ShieldCheck, Sparkles } from "lucide-react";
import { BrandMark } from "@/components/clinic/brand-mark";
import { ContractorEnrollmentForm } from "@/components/clinic/grid/contractor-enrollment-form";
import { Badge } from "@/components/ui/badge";

export const metadata = { title: "Join Clinicos GRID" };

export default function GridContractorJoinPage() {
  return <main className="min-h-screen bg-[#f5f7f5]"><header className="mx-auto flex h-20 max-w-7xl items-center px-5 sm:px-8"><Link className="flex items-center gap-3" href="/"><BrandMark /><div><p className="text-sm font-extrabold text-slate-950">Clinicos GRID</p><p className="text-[9px] font-bold uppercase tracking-[.18em] text-slate-500">by Zumi</p></div></Link><Link className="ml-auto flex items-center gap-2 text-xs font-bold text-slate-600" href="/"><ArrowLeft className="size-4" /> Back to Clinicos</Link></header><section className="border-y border-slate-200 bg-[#081923] text-white"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-14 sm:px-8 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><Badge className="bg-white/10 text-teal-200 ring-white/15"><MapPinned className="mr-1.5 size-3" /> Independent contractor path</Badge><h1 className="mt-6 text-5xl font-black leading-[.96] tracking-[-.065em] sm:text-6xl">Bring your license. Choose how you work.</h1></div><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-white/[.07] p-5 ring-1 ring-white/10"><ShieldCheck className="size-5 text-teal-300" /><p className="mt-4 text-sm font-extrabold">Human approval first</p><p className="mt-2 text-xs leading-6 text-slate-300">License and malpractice evidence are reviewed before account or booking access becomes active.</p></div><div className="rounded-2xl bg-white/[.07] p-5 ring-1 ring-white/10"><Sparkles className="size-5 text-lime-300" /><p className="mt-4 text-sm font-extrabold">Zumi guidance, your decision</p><p className="mt-2 text-xs leading-6 text-slate-300">Zumi helps with administrative readiness. It does not make clinical, hiring, or booking decisions.</p></div></div></div></section><section className="mx-auto grid max-w-7xl gap-10 px-5 py-12 sm:px-8 lg:grid-cols-[.62fr_1.38fr]"><aside className="lg:sticky lg:top-8 lg:self-start"><p className="text-[10px] font-extrabold uppercase tracking-[.18em] text-teal-700">For nurses and injectors like Tiffany</p><h2 className="mt-3 text-3xl font-black tracking-[-.05em] text-slate-950">One application for the details GRID needs.</h2><ul className="mt-6 space-y-3 text-sm leading-6 text-slate-600">{["Nurse/injector contractor identity", "State license and malpractice evidence", "Mobile, clinic-chair, and partner-location preferences", "Recurring availability and travel radius", "Admin approval before activation", "Booking choices and transparent payout estimates"].map((item) => <li className="flex gap-3" key={item}><span className="mt-2 size-1.5 shrink-0 rounded-full bg-teal-500" />{item}</li>)}</ul><p className="mt-6 rounded-2xl bg-amber-50 p-4 text-[11px] leading-6 text-amber-900">Demo safety: do not enter real patient information. Use synthetic license and policy references until the production security and compliance environment is approved.</p></aside><ContractorEnrollmentForm /></section></main>;
}
